### PR TITLE
vsr: correctness, don't prepare-ok until the log view is durable

### LINKED ISSUE #757: Crash: 6196862537461562170
<strong>Commit:</strong> ```76c62007bd1e5f48cd8e5ee016e02823542fc489``` <br><br><strong>Branches:</strong> main<br><br><strong>Duration to run seed in ReleaseSafe mode:</strong> 6s<br><br><strong>Stack Trace:</strong><br>
```
thread panic: reached unreachable code
src/vsr/replica.zig:0:0: in vsr.replica.DVCQuorum.quorum_headers (simulator)
src/vsr/replica.zig:1527:61: in vsr.replica.ReplicaType(state_machine.StateMachineType(testing.storage.Storage,(struct constants.StateMachineConfig constant)),testing.cluster.message_bus.MessageBus,testing.storage.Storage,testing.time.Time,testing.aof.AOF).on_message (simulator)
const op_head = switch (DVCQuorum.quorum_headers(

src/testing/cluster/network.zig:247:39: in testing.cluster.network.Network.deliver_message (simulator)
target_bus.on_message_callback(target_bus, target_message);

src/testing/packet_simulator.zig:339:49: in testing.cluster.ClusterType(state_machine.StateMachineType).tick (simulator)
link_packet.callback(link_packet.packet, path);

src/simulator.zig:355:31: in main (simulator)
simulator.cluster.tick();

zig/lib/std/start.zig:561:37: in std.start.posixCallMainAndExit (simulator)
const result = root.main() catch |err| {

zig/lib/std/start.zig:322:5: in std.start._start (simulator)
@call(.{ .modifier = .never_inline }, posixCallMainAndExit, .{});

debug: exit with signal: 6. Indicates a crash bug.


```
<br><strong>Debug Logs:</strong><br><details><summary>Tail</summary><br>
```debug: Replaying seed 6196862537461562170 in Debug mode with full debug logging enabled...


SEED=6196862537461562170

replicas=2
standbys=1
clients=4
request_probability=93%
idle_on_probability=4%
idle_off_probability=16%
one_way_delay_mean=9 ticks
one_way_delay_min=0 ticks
packet_loss_probability=17%
path_maximum_capacity=4 messages
path_clog_duration_mean=8 ticks
path_clog_probability=0%
packet_replay_probability=11%
partition_mode=PartitionMode.uniform_size
partition_symmetry=PartitionSymmetry.symmetric
partition_probability=1%
unpartition_probability=6%
partition_stability=122 ticks
unpartition_stability=3 ticks
read_latency_min=1
read_latency_mean=10
write_latency_min=0
write_latency_mean=89
read_fault_probability=0%
write_fault_probability=9%
crash_probability=0.00002%
crash_stability=555 ticks
restart_probability=0.0002%
restart_stability=795 ticks
 1/.1V1/__1C0:__4Jo0/_1J!0:4Wo45056Gf4/4Pp0/3Pq
 0 $ # #
 2|.1V1/__1C0:__5Jo0/_5J!0:3Wo45056Gf
 1 $ ##
 0  \ v1V0/__0C0:__0Jo0/_0J!0:1Wo45056Gf
 1  \v2V0/__1C0:__5Jo0/_0J!0:5Wo45056Gf
```
</details>

### PR DESCRIPTION
**Pull request by matklad**
Before the fix, replica can switch to a view, send a `prepare_ok` before
`log_view_durable` is updated, and crash. After restart, it will then
incorrectly infer that it crashed during view change and will use SV to
infer the head message. This then can lead to prepare_oked message being
nacked in a subsequent view change.

I also added a comment explaining the overall `open` flow, as it took me a while to puzzle out how exactly are we recovering

SEED: 6196862537461562170
closes: #757

## Pre-merge checklist

Performance:

* [X] I am very sure this PR could not affect performance.

### CODE REVIEW

**Comment by matklad** [comment]
I wanted to write a `replica_test` for this, but that seems tricky. This really depends on the interleaving between disk writes and network messages, and I don't see an easy way to control disk writes. I tried blocking all writes to `vsr.Zone.superbock`, but that got the whole test stuck (although I now realize that I don't understand why taht happens)

**Comment by sentientwaffle** [comment]
Yes, precise control of disk writes is on my "nice-to-have... someday" list.

As far as getting stuck, my guess is its something like: Until view-durable-update finishes, the replica's outgoing messages keep getting dropped.

File: src/vsr/replica.zig [hunk 1]
```diff
@@ -5836,11 +5848,12 @@ pub fn ReplicaType(
                     return;
                 }
 
-                // For DVCs and SVCs we must wait for the log_view to be durable:
+                // For DVCs, SVCs anr preapare_oks we must wait for the log_view to be durable:
```
Comment (sentientwaffle) [inline src/vsr/replica.zig]:
```suggestion
                // For DVCs, SVCs, and prepare_oks we must wait for the log_view to be durable:
```

File: src/vsr/replica.zig [hunk 2]
```diff
@@ -6252,7 +6265,7 @@ pub fn ReplicaType(
                 const dvc_headers = message_body_as_view_headers(dvc);
                 const dvc_nacks = std.bit_set.IntegerBitSet(128){ .mask = dvc.header.context };
                 for (dvc_headers.slice) |*header, i| {
-                    log.debug(
+                    log.err(
```
Comment (sentientwaffle) [inline src/vsr/replica.zig]: Why `log.err`?

Comment (matklad) [reply src/vsr/replica.zig]: stray debug print!

**Review by sentientwaffle — APPROVED** [review]
