### PR TITLE
Fix tigerbeetle version, correct zero check in src/shell.zig

### LINKED ISSUE #1097: Version isn't being correctly set for `tigerbeetle version`
See https://github.com/tigerbeetle/tigerbeetle/pull/1043.

### PR DESCRIPTION
**Pull request by eatonphil**
In addition to the zero check being backwards, we weren't propagating .git into the build environment in a few places so the version wouldn't have been set correctly in Docker for example. It may never have been.

Closes https://github.com/tigerbeetle/tigerbeetle/issues/1097

### CODE REVIEW

File: src/shell.zig [hunk 1]
```diff
@@ -192,7 +192,7 @@ pub fn exec_stdout(shell: *Shell, comptime cmd: []const u8, cmd_args: anytype) !
     errdefer shell.arena.allocator().free(res.stdout);
 
     switch (res.term) {
-        .Exited => |code| if (code == 0) return error.NonZeroExitStatus,
+        .Exited => |code| if (code != 0) return error.NonZeroExitStatus,
```
Comment (eatonphil) [inline src/shell.zig]: @matklad this is the meat of the problem. :)

File: src/shell.zig [hunk 2]
```diff
@@ -201,11 +201,11 @@ pub fn exec_stdout(shell: *Shell, comptime cmd: []const u8, cmd_args: anytype) !
 }
 
 /// Returns current git commit hash as an ASCII string.
-pub fn git_commit(shell: *Shell) ![40]u8 {
+pub fn git_commit(shell: *Shell) ![]const u8 {
```
Comment (eatonphil) [inline src/shell.zig:214]: I'm not sure if this is important. Returning a slice made build.zig simpler.

File: build.zig [hunk 3]
```diff
@@ -20,12 +20,8 @@ pub fn build(b: *std.Build) !void {
...
 
     // The "tigerbeetle version" command includes the build-time commit hash.
-    options.addOption(
-        ?[]const u8,
-        "git_commit",
-        if (shell.git_commit()) |commit| @as([]const u8, &commit) else |_| null,
-    );
-    options.addOption(?[]const u8, "git_tag", shell.git_tag() catch null);
+    options.addOption(?[]const u8, "git_commit", try shell.git_commit());
+    options.addOption([]const u8, "git_tag", try shell.git_tag());
```
Comment (eatonphil) [inline build.zig:24]: Switch these to `try` so they don't hide the error message on failure.

File: src/shell.zig (hunk 1 above)
Comment (eatonphil) [reply src/shell.zig]: Oh, you already knew that. :)

File: src/shell.zig [hunk 4]
```diff
@@ -201,16 +211,18 @@ pub fn exec_stdout(shell: *Shell, comptime cmd: []const u8, cmd_args: anytype) !
...
+    try shell.exec("git fetch --tags", .{});
```
Comment (matklad) [inline src/shell.zig]: fetching tags from the network is a slow, failable operation. Given that we run this on every build, it seems better to avoid maybe ask the caller to fetch the repo with tags instead?

File: build.zig (hunk 3 above)
Comment (matklad) [reply build.zig:24]: Yeah, I think it's OK to assume that we have git during building!

File: src/shell.zig (hunk 4 above)
Comment (eatonphil) [reply src/shell.zig]: > Given that we run this on every build

Yes, however, locally it's going to rarely do anything. Do you still think we should drop it?

```
$ time git fetch --tags
remote: Enumerating objects: 16, done.
remote: Counting objects: 100% (16/16), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 16 (delta 10), reused 13 (delta 10), pack-reused 0
Unpacking objects: 100% (16/16), 5.68 KiB | 528.00 KiB/s, done.
From github.com:tigerbeetledb/tigerbeetle
 + 77184c64...b87c81c8 batiati-eytzinger                                                       -> origin/batiati-eytzinger  (forced update)
 * [new branch]        gh-readonly-queue/main/pr-1140-6378bbe359c0ae2721344ac867ac521f2e5db66a -> origin/gh-readonly-queue/main/pr-1140-6378bbe359c0ae2721344ac867ac521f2e5db66a
 + 80a01ed5...16fd8150 matklad/alligned-free                                                   -> origin/matklad/alligned-free  (forced update)
 + c5ec87c0...8f9bbff5 matklad/tmp-tigerbeetle                                                 -> origin/matklad/tmp-tigerbeetle  (forced update)
git fetch --tags  0.08s user 0.05s system 18% cpu 0.688 total
$ time git fetch --tags
git fetch --tags  0.07s user 0.04s system 18% cpu 0.620 total
$ time git fetch --tags
git fetch --tags  0.07s user 0.04s system 18% cpu 0.593 total
$ time git fetch --tags
git fetch --tags  0.07s user 0.04s system 18% cpu 0.572 total
```

Comment (matklad) [reply src/shell.zig]: It's going to ping GitHub server every time, and, depending on where you are, that might be quite slow: 

```
λ n 3 t git fetch --tags
Run 1

real 2.13s
cpu  196.23ms (140.76ms user + 55.47ms sys)
rss  96.70mb
Run 2

real 2.25s
cpu  196.53ms (156.44ms user + 40.09ms sys)
rss  96.45mb
Run 3

real 2.16s
cpu  195.90ms (147.55ms user + 48.35ms sys)
rss  96.89mb
```

Comment (eatonphil) [reply src/shell.zig]: Ok! I'll move it into the ci steps then.

Comment (matklad) [reply src/shell.zig]: I guess there's also a considiration that we want `zig build` to work if there's no internet connection.

Comment (eatonphil) [reply src/shell.zig]: That will depend on how you cloned it then. Since although we clone in GitHub actions, it doesn't have any tags and got describe --tags fails, so the build fails.

However, if we drop the hard check then it can be easy to reintroduce this bug of TigerBeetle version not being set correctly. Unless we add new tests for after a release.

Comment (matklad) [reply src/shell.zig]: FWIW, that's what I use to fetch tags to gh builders:

https://github.com/matklad/once_cell/blob/3cd65494663f003b9b2e0be5b37b3426e543f72a/.github/workflows/ci.yaml#L22-L23

Maybe there's a better way, I don't remeber how I came up with that snippet

Comment (eatonphil) [reply src/shell.zig]: Ok!

Comment (eatonphil) [reply src/shell.zig]: Well now it started succeeding without me needing to fetch anything. Wonderful! That means it may fail sometime in the future. But I'm not sure which steps would fail.

Comment (eatonphil) [reply src/shell.zig]: Nevermind! It's `git tag --describe --always` that handles it without needing to fetch. We're all set.

File: build.zig [hunk 5]
```diff
@@ -20,12 +20,8 @@ pub fn build(b: *std.Build) !void {
     defer shell.destroy();
 
     // The "tigerbeetle version" command includes the build-time commit hash.
-    options.addOption(
-        ?[]const u8,
-        "git_commit",
-        if (shell.git_commit()) |commit| @as([]const u8, &commit) else |_| null,
-    );
-    options.addOption(?[]const u8, "git_tag", shell.git_tag() catch null);
+    options.addOption(?[]const u8, "git_commit", try shell.git_commit());
```
Comment (matklad) [inline build.zig]:
```suggestion
    options.addOption([]const u8, "git_commit", try shell.git_commit());
```

File: src/shell.zig [hunk 6]
```diff
@@ -192,7 +192,17 @@ pub fn exec_stdout(shell: *Shell, comptime cmd: []const u8, cmd_args: anytype) !
     errdefer shell.arena.allocator().free(res.stdout);
 
     switch (res.term) {
-        .Exited => |code| if (code == 0) return error.NonZeroExitStatus,
+        .Exited => |code| if (code != 0) {
+            std.debug.print(
+                \\Debugging failure (stdout): {s}
+                \\Debugging failure (stderr): {s}
```
Comment (matklad) [inline src/shell.zig:198]: :heart:

**Review by matklad — DISMISSED** [review]

File: build.zig (hunk 5 above)
Comment (eatonphil) [reply build.zig]: Accepted locally along with a related change needed in src/tigerbeetle/main.zig. Thanks!

**Review by matklad — APPROVED** [review]
