### PR TITLE
lsm: fix false positive fuzz failure

### LINKED ISSUE #1876: LSM segmented array fails the fuzz
```
$ ./zig/zig build -Drelease fuzz -- --seed=13934190539457735373 lsm_segmented_array

info(fuzz): Fuzz seed = 13934190539457735373
expected u32@7f99ec14e0bc, found null
error: TestExpectedEqual
```

Haven't looking into this yet

### PR DESCRIPTION
**Pull request by matklad**
For this seed, the array ends up containing maxInt purely by accident.

Seed: ./zig/zig build -Drelease fuzz -- --seed=13934190539457735373 lsm_segmented_array

Closes #1876

### CODE REVIEW

File: src/lsm/segmented_array.zig [hunk 1]
```diff
@@ -1253,7 +1253,11 @@ fn FuzzContextType(
                     context.array.search(math.maxInt(Key)),
                     .ascending,
                 );
-                try testing.expectEqual(iterator_end.next(), null);
+                try testing.expectEqual(
```
Comment (matklad) [inline src/lsm/segmented_array.zig]: I wanted to add symmetric case for 0, but it looks like that actually reveals a bug in our code :fearful: 

https://github.com/tigerbeetle/tigerbeetle/pull/1887

Comment (matklad) [reply src/lsm/segmented_array.zig]: Ah, no, this is surprising, but I think correct. The second commit adds this to a fuzzer in the right way.

File: src/lsm/segmented_array.zig [hunk 2]
```diff
@@ -1255,6 +1255,21 @@ fn FuzzContextType(
                 );
                 try testing.expectEqual(iterator_end.next(), null);
             }
+
+            {
+                // 0 is not symmetric with maxInt, because `array.search` doesn't take direction
+                // into account.
```
Comment (sentientwaffle) [inline src/lsm/segmented_array.zig:1261]: :exploding_head: Surprising!

I double-checked the call sites to see if they were buggy:

`ForestTableIterator.next()` is fine, it only ever iterates ascending.

`ManifestLevel.iterator_start()` is more confusing. I _think_ the code is correct thanks to `iterator_start_boundary()`, but this might be accidental.

It has a comment which notes this behavior:

```
            // Ascending:  Find the first table where table.key_max ≤ iterator.key_min.
            // Descending: Find the first table where table.key_max ≤ iterator.key_max.
            const target = level.keys.search(switch (direction) {
                .ascending => key_min,
                .descending => key_max,
            });
```

...And I think in the comment, the inequalities are backwards?

Comment (matklad) [reply src/lsm/segmented_array.zig:1261]: My reading that it is correct rather because of this logic

https://github.com/tigerbeetle/tigerbeetle/pull/1886/commits/6555946ad2431385145ae9a858447c145994f929

But year, the inequalities are indeed backwards, will fix

Comment (matklad) [reply src/lsm/segmented_array.zig:1261]: Yes, I think `iterator_start_boundary` deals with equal keys, but that case actually works in a normal way here. what needsspecial handling is when the smallest key is greater than what we have

**Review by sentientwaffle — DISMISSED** [review]
Aside from the (preexisting) backwards comment in `ManifestLevel` this LGTM.

**Review by sentientwaffle — APPROVED** [review]
