### PR TITLE
LSM Fixes (via fuzzer)

### LINKED ISSUE #184: lsm_forest_fuzz: 4075310295854600248
At 2a134ecea5b546e138a2e781c0b8df50d981557b.

```
debug(lsm_forest_fuzz): Running fuzz_ops[14384] == FuzzOp{ .get_account = 6 }
thread 23939 panic: attempt to use null value
/home/jamie/tigerbeetle/src/lsm/forest_fuzz.zig:231:56: 0x27b1bc in Environment.run (lsm_forest_fuzz)
                            std.mem.asBytes(lsm_account.?),
                                                       ^
/home/jamie/tigerbeetle/src/lsm/forest_fuzz.zig:264:24: 0x2721b9 in fuzz (lsm_forest_fuzz)
    try Environment.run(&storage, fuzz_ops);
                       ^
/home/jamie/tigerbeetle/src/lsm/forest_fuzz.zig:414:13: 0x269c26 in main (lsm_forest_fuzz)
    try fuzz(fuzz_ops);
            ^
/nix/store/g94blv8pk5z0h4maivk3ymcrafrcbwl8-zig-0.9.1/lib/zig/std/start.zig:561:37: 0x262d0a in std.start.callMain (lsm_forest_fuzz)
            const result = root.main() catch |err| {
                                    ^
/nix/store/g94blv8pk5z0h4maivk3ymcrafrcbwl8-zig-0.9.1/lib/zig/std/start.zig:495:12: 0x2438fe in std.start.callMainWithArgs (lsm_forest_fuzz)
    return @call(.{ .modifier = .always_inline }, callMain, .{});
           ^
/nix/store/g94blv8pk5z0h4maivk3ymcrafrcbwl8-zig-0.9.1/lib/zig/std/start.zig:409:17: 0x242996 in std.start.posixCallMainAndExit (lsm_forest_fuzz)
    std.os.exit(@call(.{ .modifier = .always_inline }, callMainWithArgs, .{ argc, argv, envp }));
                ^
/nix/store/g94blv8pk5z0h4maivk3ymcrafrcbwl8-zig-0.9.1/lib/zig/std/start.zig:322:5: 0x2427a2 in std.start._start (lsm_forest_fuzz)
    @call(.{ .modifier = .never_inline }, posixCallMainAndExit, .{});
    ^
The following command terminated unexpectedly:
cd /home/jamie/tigerbeetle && /home/jamie/tigerbeetle/zig-cache/o/7c816c2d3f9fb064b650a8d398257bf3/lsm_forest_fuzz --seed 4075310295854600248
error: the following build command failed with exit code 1:
/home/jamie/tigerbeetle/zig-cache/o/04e062ed50064d3f166819b2149e5107/build /nix/store/g94blv8pk5z0h4maivk3ymcrafrcbwl8-zig-0.9.1/bin/zig /home/jamie/tigerbeetle /home/jamie/tigerbeetle/zig-cache /home/jamie/.cache/zig lsm_forest_fuzz -- --seed 4075310295854600248
```

### LINKED ISSUE #185: lsm_forest_fuzz: 13117012641703417096
At 2a134ecea5b546e138a2e781c0b8df50d981557b.

```
thread 20286 panic: attempt to use null value
/home/jamie/tigerbeetle/src/lsm/groove.zig:762:38: 0x32f0c7 in lsm.groove.PrefetchWorker.lookup_object_callback (lsm_forest_fuzz)
                const object = result.?;
                                     ^
/home/jamie/tigerbeetle/src/lsm/tree.zig:334:25: 0x32ee3d in lsm.tree.TreeType(lsm.table.TableType(u64,tigerbeetle.Account,lsm.groove.ObjectTreeHelpers(tigerbeetle.Account).compare_keys,lsm.groove.ObjectTreeHelpers(tigerbeetle.Account).key_from_value,18446744073709551615,lsm.groove.ObjectTreeHelpers(tigerbeetle.Account).tombstone,lsm.groove.ObjectTreeHelpers(tigerbeetle.Account).tombstone_from_key),test.storage.Storage,[]const u8{65,99,99,111,117,110,116}).lookup_from_levels (lsm_forest_fuzz)
                callback(context, null);
                        ^
/home/jamie/tigerbeetle/src/lsm/groove.zig:744:69: 0x2ffcf1 in lsm.groove.PrefetchWorker.lookup_id_callback (lsm_forest_fuzz)
                    worker.context.groove.objects.lookup_from_levels(
                                                                    ^
/home/jamie/tigerbeetle/src/lsm/groove.zig:684:39: 0x2b22db in lsm.groove.PrefetchWorker.lookup_start_next (lsm_forest_fuzz)
                    lookup_id_callback(&worker.lookup_id, id_tree_value);
                                      ^
/home/jamie/tigerbeetle/src/lsm/groove.zig:642:45: 0x2a1825 in lsm.groove.PrefetchContext.start_workers (lsm_forest_fuzz)
                    worker.lookup_start_next();
                                            ^
/home/jamie/tigerbeetle/src/lsm/groove.zig:611:34: 0x2936a5 in lsm.groove.GrooveType(test.storage.Storage,tigerbeetle.Account,(struct state_machine.struct:33:14 constant)).prefetch (lsm_forest_fuzz)
            context.start_workers();
                                 ^
/home/jamie/tigerbeetle/src/lsm/forest_fuzz.zig:185:24: 0x291a21 in Environment.prefetch_account (lsm_forest_fuzz)
        groove.prefetch(Getter.prefetch_callback, &getter.prefetch_context);
                       ^
/home/jamie/tigerbeetle/src/lsm/forest_fuzz.zig:220:41: 0x27afc7 in Environment.run (lsm_forest_fuzz)
                    env.prefetch_account(id);
                                        ^
/home/jamie/tigerbeetle/src/lsm/forest_fuzz.zig:264:24: 0x2721b9 in fuzz (lsm_forest_fuzz)
    try Environment.run(&storage, fuzz_ops);
                       ^
/home/jamie/tigerbeetle/src/lsm/forest_fuzz.zig:414:13: 0x269c26 in main (lsm_forest_fuzz)
    try fuzz(fuzz_ops);
            ^
/nix/store/g94blv8pk5z0h4maivk3ymcrafrcbwl8-zig-0.9.1/lib/zig/std/start.zig:561:37: 0x262d0a in std.start.callMain (lsm_forest_fuzz)
            const result = root.main() catch |err| {
                                    ^
/nix/store/g94blv8pk5z0h4maivk3ymcrafrcbwl8-zig-0.9.1/lib/zig/std/start.zig:495:12: 0x2438fe in std.start.callMainWithArgs (lsm_forest_fuzz)
    return @call(.{ .modifier = .always_inline }, callMain, .{});
           ^
/nix/store/g94blv8pk5z0h4maivk3ymcrafrcbwl8-zig-0.9.1/lib/zig/std/start.zig:409:17: 0x242996 in std.start.posixCallMainAndExit (lsm_forest_fuzz)
    std.os.exit(@call(.{ .modifier = .always_inline }, callMainWithArgs, .{ argc, argv, envp }));
                ^
/nix/store/g94blv8pk5z0h4maivk3ymcrafrcbwl8-zig-0.9.1/lib/zig/std/start.zig:322:5: 0x2427a2 in std.start._start (lsm_forest_fuzz)
    @call(.{ .modifier = .never_inline }, posixCallMainAndExit, .{});
    ^
The following command terminated unexpectedly:
cd /home/jamie/tigerbeetle && /home/jamie/tigerbeetle/zig-cache/o/7c816c2d3f9fb064b650a8d398257bf3/lsm_forest_fuzz --seed 13117012641703417096
error: the following build command failed with exit code 1:
/home/jamie/tigerbeetle/zig-cache/o/04e062ed50064d3f166819b2149e5107/build /nix/store/g94blv8pk5z0h4maivk3ymcrafrcbwl8-zig-0.9.1/bin/zig /home/jamie/tigerbeetle /home/jamie/tigerbeetle/zig-cache /home/jamie/.cache/zig lsm_forest_fuzz -- --seed 13117012641703417096
```

### LINKED ISSUE #187: lsm_forest_fuzz: 10048288728635360357
At 2a134ecea5b546e138a2e781c0b8df50d981557b.

```
thread 15685 panic: reached unreachable code
/nix/store/g94blv8pk5z0h4maivk3ymcrafrcbwl8-zig-0.9.1/lib/zig/std/debug.zig:225:14: 0x23fa7b in std.debug.assert (lsm_forest_fuzz)
    if (!ok) unreachable; // assertion failure
             ^
/home/jamie/tigerbeetle/src/lsm/manifest_log.zig:357:27: 0x442e75 in lsm.manifest_log.ManifestLogType(test.storage.Storage,lsm.manifest.TableInfoType(lsm.table.TableType(lsm.composite_key.CompositeKey(u64),lsm.composite_key.Value,lsm.composite_key.CompositeKey(u64).compare_keys,lsm.composite_key.CompositeKey(u64).key_from_value,(struct lsm.composite_key.CompositeKey(u64) constant),lsm.composite_key.CompositeKey(u64).tombstone,lsm.composite_key.CompositeKey(u64).tombstone_from_key))).write_block (lsm_forest_fuzz)
                    assert(manifest_log.entry_count < entry_count_max);
                          ^
/home/jamie/tigerbeetle/src/lsm/manifest_log.zig:344:37: 0x3dbc77 in lsm.manifest_log.ManifestLogType(test.storage.Storage,lsm.manifest.TableInfoType(lsm.table.TableType(lsm.composite_key.CompositeKey(u64),lsm.composite_key.Value,lsm.composite_key.CompositeKey(u64).compare_keys,lsm.composite_key.CompositeKey(u64).key_from_value,(struct lsm.composite_key.CompositeKey(u64) constant),lsm.composite_key.CompositeKey(u64).tombstone,lsm.composite_key.CompositeKey(u64).tombstone_from_key))).flush (lsm_forest_fuzz)
            manifest_log.write_block();
                                    ^
/home/jamie/tigerbeetle/src/lsm/manifest_log.zig:428:31: 0x38e09f in lsm.manifest_log.ManifestLogType(test.storage.Storage,lsm.manifest.TableInfoType(lsm.table.TableType(lsm.composite_key.CompositeKey(u64),lsm.composite_key.Value,lsm.composite_key.CompositeKey(u64).compare_keys,lsm.composite_key.CompositeKey(u64).key_from_value,(struct lsm.composite_key.CompositeKey(u64) constant),lsm.composite_key.CompositeKey(u64).tombstone,lsm.composite_key.CompositeKey(u64).tombstone_from_key))).compact (lsm_forest_fuzz)
            manifest_log.flush(compact_flush_callback);
                              ^
/home/jamie/tigerbeetle/src/lsm/manifest.zig:552:42: 0x36f651 in lsm.manifest.ManifestType(lsm.table.TableType(lsm.composite_key.CompositeKey(u64),lsm.composite_key.Value,lsm.composite_key.CompositeKey(u64).compare_keys,lsm.composite_key.CompositeKey(u64).key_from_value,(struct lsm.composite_key.CompositeKey(u64) constant),lsm.composite_key.CompositeKey(u64).tombstone,lsm.composite_key.CompositeKey(u64).tombstone_from_key),test.storage.Storage).compact (lsm_forest_fuzz)
            manifest.manifest_log.compact(manifest_log_compact_callback);
                                         ^
/home/jamie/tigerbeetle/src/lsm/tree.zig:933:34: 0x34bcc8 in lsm.tree.TreeType(lsm.table.TableType(lsm.composite_key.CompositeKey(u64),lsm.composite_key.Value,lsm.composite_key.CompositeKey(u64).compare_keys,lsm.composite_key.CompositeKey(u64).key_from_value,(struct lsm.composite_key.CompositeKey(u64) constant),lsm.composite_key.CompositeKey(u64).tombstone,lsm.composite_key.CompositeKey(u64).tombstone_from_key),test.storage.Storage,[]const u8{65,99,99,111,117,110,116,46,99,114,101,100,105,116,115,95,112,111,115,116,101,100}).compact_done (lsm_forest_fuzz)
            tree.manifest.compact(compact_manifest_callback);
                                 ^
/home/jamie/tigerbeetle/src/lsm/tree.zig:814:67: 0x31d1ca in lsm.tree.TreeType(lsm.table.TableType(lsm.composite_key.CompositeKey(u64),lsm.composite_key.Value,lsm.composite_key.CompositeKey(u64).compare_keys,lsm.composite_key.CompositeKey(u64).key_from_value,(struct lsm.composite_key.CompositeKey(u64) constant),lsm.composite_key.CompositeKey(u64).tombstone,lsm.composite_key.CompositeKey(u64).tombstone_from_key),test.storage.Storage,[]const u8{65,99,99,111,117,110,116,46,99,114,101,100,105,116,115,95,112,111,115,116,101,100}).compact_tick_done (lsm_forest_fuzz)
            if (tree.compaction_io_pending == 0) tree.compact_done();
                                                                  ^
/home/jamie/tigerbeetle/src/lsm/tree.zig:785:35: 0x34b661 in lsm.tree.TreeType(lsm.table.TableType(lsm.composite_key.CompositeKey(u64),lsm.composite_key.Value,lsm.composite_key.CompositeKey(u64).compare_keys,lsm.composite_key.CompositeKey(u64).key_from_value,(struct lsm.composite_key.CompositeKey(u64) constant),lsm.composite_key.CompositeKey(u64).tombstone,lsm.composite_key.CompositeKey(u64).tombstone_from_key),test.storage.Storage,[]const u8{65,99,99,111,117,110,116,46,99,114,101,100,105,116,115,95,112,111,115,116,101,100}).compact_tick_callback_table_immutable (lsm_forest_fuzz)
            tree.compact_tick_done();
                                  ^
/home/jamie/tigerbeetle/src/lsm/compaction.zig:465:21: 0x38cb82 in lsm.compaction.CompactionType(lsm.table.TableType(lsm.composite_key.CompositeKey(u64),lsm.composite_key.Value,lsm.composite_key.CompositeKey(u64).compare_keys,lsm.composite_key.CompositeKey(u64).key_from_value,(struct lsm.composite_key.CompositeKey(u64) constant),lsm.composite_key.CompositeKey(u64).tombstone,lsm.composite_key.CompositeKey(u64).tombstone_from_key),test.storage.Storage,lsm.table_immutable.TableImmutableIteratorType).cpu_merge_start (lsm_forest_fuzz)
            callback(compaction);
                    ^
/home/jamie/tigerbeetle/src/lsm/compaction.zig:434:71: 0x36e6f5 in lsm.compaction.CompactionType(lsm.table.TableType(lsm.composite_key.CompositeKey(u64),lsm.composite_key.Value,lsm.composite_key.CompositeKey(u64).compare_keys,lsm.composite_key.CompositeKey(u64).key_from_value,(struct lsm.composite_key.CompositeKey(u64) constant),lsm.composite_key.CompositeKey(u64).tombstone,lsm.composite_key.CompositeKey(u64).tombstone_from_key),test.storage.Storage,lsm.table_immutable.TableImmutableIteratorType).io_finish (lsm_forest_fuzz)
            if (compaction.io_pending == 0) compaction.cpu_merge_start();
                                                                      ^
/home/jamie/tigerbeetle/src/lsm/compaction.zig:401:42: 0x38c990 in lsm.compaction.write_callback.callback (lsm_forest_fuzz)
                    _compaction.io_finish();
                                         ^
/home/jamie/tigerbeetle/src/lsm/grid.zig:333:37: 0x4181f9 in lsm.grid.GridType(test.storage.Storage).write_block_callback (lsm_forest_fuzz)
            completed_write.callback(completed_write);
                                    ^
/home/jamie/tigerbeetle/src/test/storage.zig:294:23: 0x2a7d41 in test.storage.Storage.write_sectors_finish (lsm_forest_fuzz)
        write.callback(write);
                      ^
/home/jamie/tigerbeetle/src/test/storage.zig:188:41: 0x29d5de in test.storage.Storage.tick (lsm_forest_fuzz)
            storage.write_sectors_finish(write);
                                        ^
/home/jamie/tigerbeetle/src/lsm/forest_fuzz.zig:106:25: 0x2917a8 in Environment.tick (lsm_forest_fuzz)
        env.storage.tick();
                        ^
/home/jamie/tigerbeetle/src/lsm/forest_fuzz.zig:112:52: 0x27f004 in Environment.tick_until_state_change (lsm_forest_fuzz)
        while (env.state == current_state) env.tick();
                                                   ^
/home/jamie/tigerbeetle/src/lsm/forest_fuzz.zig:163:36: 0x291b53 in Environment.compact (lsm_forest_fuzz)
        env.tick_until_state_change(.forest_compacting, .forest_open);
                                   ^
/home/jamie/tigerbeetle/src/lsm/forest_fuzz.zig:211:32: 0x27b067 in Environment.run (lsm_forest_fuzz)
                    env.compact(op);
                               ^
/home/jamie/tigerbeetle/src/lsm/forest_fuzz.zig:264:24: 0x2721b9 in fuzz (lsm_forest_fuzz)
    try Environment.run(&storage, fuzz_ops);
                       ^
/home/jamie/tigerbeetle/src/lsm/forest_fuzz.zig:414:13: 0x269c26 in main (lsm_forest_fuzz)
    try fuzz(fuzz_ops);
            ^
/nix/store/g94blv8pk5z0h4maivk3ymcrafrcbwl8-zig-0.9.1/lib/zig/std/start.zig:561:37: 0x262d0a in std.start.callMain (lsm_forest_fuzz)
            const result = root.main() catch |err| {
                                    ^
/nix/store/g94blv8pk5z0h4maivk3ymcrafrcbwl8-zig-0.9.1/lib/zig/std/start.zig:495:12: 0x2438fe in std.start.callMainWithArgs (lsm_forest_fuzz)
    return @call(.{ .modifier = .always_inline }, callMain, .{});
           ^
/nix/store/g94blv8pk5z0h4maivk3ymcrafrcbwl8-zig-0.9.1/lib/zig/std/start.zig:409:17: 0x242996 in std.start.posixCallMainAndExit (lsm_forest_fuzz)
    std.os.exit(@call(.{ .modifier = .always_inline }, callMainWithArgs, .{ argc, argv, envp }));
                ^
/nix/store/g94blv8pk5z0h4maivk3ymcrafrcbwl8-zig-0.9.1/lib/zig/std/start.zig:322:5: 0x2427a2 in std.start._start (lsm_forest_fuzz)
    @call(.{ .modifier = .never_inline }, posixCallMainAndExit, .{});
    ^
The following command terminated unexpectedly:
cd /home/jamie/tigerbeetle && /home/jamie/tigerbeetle/zig-cache/o/7c816c2d3f9fb064b650a8d398257bf3/lsm_forest_fuzz --seed 10048288728635360357
error: the following build command failed with exit code 1:
/home/jamie/tigerbeetle/zig-cache/o/04e062ed50064d3f166819b2149e5107/build /nix/store/g94blv8pk5z0h4maivk3ymcrafrcbwl8-zig-0.9.1/bin/zig /home/jamie/tigerbeetle /home/jamie/tigerbeetle/zig-cache /home/jamie/.cache/zig lsm_forest_fuzz -- --seed 10048288728635360357
```

### PR DESCRIPTION
**Pull request by sentientwaffle**
### [LSM: Fix immutable table snapshot](https://github.com/tigerbeetledb/tigerbeetle/commit/d98ed5c5d13228380b4eb791357e60c1a8634325)

The immutable table was not being read until after it had been compacted the first time.
`compaction_table_immutable.snapshot` was the correct value (or off by one, but close enough to work) — but it isn't set until the first compaction, so we were using an `undefined` snapshot.

- At the end of the fourth beat, the immutable table's `snapshot_min` should be the op of the first beat of the compaction that just finished. (This was correctly documented in `compaction.zig`, but incorrectly implemented).
- Snapshot comparison is inclusive.
- Fixes https://github.com/tigerbeetledb/tigerbeetle/issues/184.
- Fixes https://github.com/tigerbeetledb/tigerbeetle/issues/185.

---
### [LSM: ManifestLog: Fix entry_count/blocks invariant](https://github.com/tigerbeetledb/tigerbeetle/commit/4c7e88352e189050615de39f78c87dbb23e859b2)

Invariant: When `ManifestLog.entry_count == entry_count_max`, immediately close the block and reset. (So outside of `append()`, `entry_count < entry_count_max`).

This invariant was checked in `write`, but not implemented in `append()`.

For consistency, when `entry_count == 0`, there is no open block. This was sometimes (but not always) true before.

- Fixes https://github.com/tigerbeetledb/tigerbeetle/issues/187.

---
Also, [Scripts: fuzz scripts use sh instead of bash](https://github.com/tigerbeetledb/tigerbeetle/commit/0e1c9a13a00a1ee6fe79d1e785a14e80cb9e760e)

### CODE REVIEW

**Comment by jorangreef** [comment]
Another bug I think that we could add to this PR:
* When opening `ManifestLog` blocks, we don't queue partially full blocks for compaction. This mirrors the fix that you recently did when writing blocks, but now on the open path.

File: scripts/fuzz_repeatedly.sh [hunk 1]
```diff
@@ -1,5 +1,5 @@
-#!/usr/bin/env bash
-set -eEuo pipefail
+#!/usr/bin/env sh
+set -eu
 
 # Repeatedly runs some zig build command with different seeds and stores the output in the current directory.
 # Eg `fuzz_repeatedly.sh lsm_forest_fuzz` will run `zig build lsm_forest_fuzz -- seed $SEED > fuzz_lsm_forest_fuzz_${SEED}`
```
Comment (jorangreef) [inline scripts/fuzz_repeatedly.sh:5]: Rename to `fuzz_loop.sh` (easier to type, less syllables to speak, also a noun)?

File: src/lsm/manifest_log.zig [hunk 2]
```diff
@@ -282,11 +287,8 @@ pub fn ManifestLogType(comptime Storage: type, comptime TableInfo: type) type {
             assert(table.snapshot_min > 0);
             assert(table.snapshot_max > table.snapshot_min);
 
-            if (manifest_log.blocks.empty()) {
-                manifest_log.acquire_block();
-            } else if (manifest_log.entry_count == entry_count_max) {
-                assert(manifest_log.blocks.count > 0);
-                manifest_log.close_block();
+            if (manifest_log.entry_count == 0) {
+                assert(manifest_log.blocks.count == manifest_log.blocks_closed);
```
Comment (jorangreef) [inline src/lsm/manifest_log.zig:291]: Much nicer like this:
* Both conditions are all in terms of `entry_count` now.
* We collapse two branches into one.
* We no longer have a TOCTOU between appending to a block and closing a block.

Comment (jorangreef) [reply src/lsm/manifest_log.zig:291]: I'm puzzled why I did it the other way! 😁

Comment (jorangreef) [reply src/lsm/manifest_log.zig:291]: Ah, I think it was because the append might not happen at the same time as when we flush the block. So the other way we can handle 1 more insert, without needing the blocks ring buffer to have a whole new completely empty block allocated.

But this way is still better.

File: src/lsm/manifest_log.zig [hunk 3]
```diff
@@ -375,6 +381,7 @@ pub fn ManifestLogType(comptime Storage: type, comptime TableInfo: type) type {
             const entry_count = block_entry_count(block);
 
             if (manifest_log.blocks_closed == 1 and manifest_log.blocks.count == 1) {
+                // This might be the last block of a checkpoint, which can be a partial block.
```
Comment (jorangreef) [inline src/lsm/manifest_log.zig:384]: Great comment. Just helped me figure this out again.

File: src/lsm/tree.zig [hunk 4]
```diff
@@ -294,7 +290,7 @@ pub fn TreeType(comptime TreeTable: type, comptime Storage: type, comptime tree_
                 // This simplifies the mutable table and eliminates compaction for duplicate puts.
             }
 
-            if (!tree.table_immutable.free and tree.table_immutable.snapshot_min < snapshot) {
+            if (!tree.table_immutable.free and tree.table_immutable.snapshot_min <= snapshot) {
```
Comment (jorangreef) [inline src/lsm/tree.zig:293]: Because `snapshot_min/max` are both inclusive now.

Are there any other places in the source where we might still have the same bug for either of these?

File: src/lsm/tree.zig [hunk 5]
```diff
@@ -933,18 +929,19 @@ pub fn TreeType(comptime TreeTable: type, comptime Storage: type, comptime tree_
             tree.manifest.compact(compact_manifest_callback);
         }
 
+        /// Called after the fourth/last beat.
```
Comment (jorangreef) [inline src/lsm/tree.zig]:
```suggestion
        /// Called after the last beat of a compaction measure.
```

Since the beats in a measure are typically > 4.

File: src/lsm/tree.zig [hunk 6]
```diff
@@ -933,18 +929,19 @@ pub fn TreeType(comptime TreeTable: type, comptime Storage: type, comptime tree_
...
         fn compact_mutable_table_into_immutable(tree: *Tree) void {
-            // Ensure mutable table can be flushed into immutable table.
             if (tree.table_mutable.count() == 0) return;
             assert(tree.table_immutable.free);
+            assert((tree.compaction_op + 1) % config.lsm_batch_multiple == 0);
```
Comment (jorangreef) [inline src/lsm/tree.zig:935]: We should hoist these two assertions to the top, since they should always be true, even in the event of the early return.

File: src/lsm/tree.zig [hunk 7]
```diff
@@ -933,18 +929,19 @@ pub fn TreeType(comptime TreeTable: type, comptime Storage: type, comptime tree_
...
 
             // Sort the mutable table values directly into the immutable table's array.
             const values_max = tree.table_immutable.values_max();
             const values = tree.table_mutable.sort_into_values_and_clear(values_max);
             assert(values.ptr == values_max.ptr);
 
-            // Take a manifest snapshot and setup the immutable table with the sorted values.
-            const snapshot_min = tree.compaction_table_immutable.snapshot;
+            const snapshot_min = compaction_snapshot_for_op(tree.compaction_op) + 1;
```
Comment (jorangreef) [inline src/lsm/tree.zig:945]: Can we explain the plus one with a comment?

If my understanding is correct, it's because:

`// The immutable table should be visible to the next measure.`

However, I think we may have a bug in the plus one—i.e. don't we need to add a full measure's worth of ops?

File: src/lsm/tree.zig (hunk 4 above)
Comment (sentientwaffle) [reply src/lsm/tree.zig:293]: > Because `snapshot_min/max` are both inclusive now.

Exactly.

I grepped through and didn't see any others. Usually we compare snapshots via `TableInfo.invisible`, which is already inclusive.

File: src/lsm/tree.zig (hunk 6 above)
Comment (sentientwaffle) [reply src/lsm/tree.zig:935]: Good point!

File: src/lsm/tree.zig (hunk 7 above)
Comment (sentientwaffle) [reply src/lsm/tree.zig:945]: > However, I think we may have a bug in the plus one—i.e. don't we need to add a full measure's worth of ops?

Right now it just needs to be less-than-or-equal to `prefetch_snapshot_max` so that it is read by `lookup_from_memory()` (which we assert on the next line — since `prefetch_snapshot_max` is monotonically increasing, this will always hold). Adding `lsm_batch_multiple` instead of `1` would also work (in that case it would be equal to the `prefetch_snapshot_max`, I think). Or even omit both. My reason for the +1 was to mirror `snapshot_min` of a compaction's output tables (which this sort-of is, if you squint). (The reason we are computing `compaction_snapshot_for_op(tree.compaction_op) + 1` here instead of using `compaction.snapshot + 1` is the `compaction` may not have been run in the last measure, in which case its snapshot is invalid).

:thinking: But it depends how read snapshots will work, which I don't have a good picture of yet.

**Comment by sentientwaffle** [comment]
> When opening ManifestLog blocks, we don't queue partially full blocks for compaction. This mirrors the fix that you recently did when writing blocks, but now on the open path.

The [fix](https://github.com/tigerbeetledb/tigerbeetle/commit/c7b254ff2673dbbd7333df99232250fd801e6e11) you are referring to _was_ for the open path: https://github.com/tigerbeetledb/tigerbeetle/blob/09cf0ecf2ddcb190e6c8092afc2fa36641a69a35/src/lsm/manifest_log.zig#L251-L253

Is there another bug here?

**Comment by jorangreef** [comment]
> The [fix](https://github.com/tigerbeetledb/tigerbeetle/commit/c7b254ff2673dbbd7333df99232250fd801e6e11) you are referring to was for the open path.

Great, I double-checked this this morning but was looking at the wrong commit. We're good!

File: src/lsm/tree.zig (hunk 7 above)
Comment (jorangreef) [reply src/lsm/tree.zig:945]: Let's walk and talk through this tomorrow. My mental model is not yet clear enough.

**Review by jorangreef — APPROVED** [review]
