### PR TITLE
vsr: liveness, nack prepares from before log view 

### LINKED ISSUE #1510: Liveness: 15677965580699030051
<strong>Commit:</strong> ```7f92126c74c715c295503e7b41f56cef552a550c``` <br><br><strong>Branches:</strong> main<br><br><strong>Duration to run seed in ReleaseSafe mode:</strong> 2m22s<br><br><strong>Debug Logs:</strong><br><details><summary>Tail</summary><br>
```debug: Replaying seed 15677965580699030051 in Debug mode with full debug logging enabled...


SEED=15677965580699030051

replicas=3
standbys=1
clients=7
request_probability=5%
idle_on_probability=14%
idle_off_probability=19%
one_way_delay_mean=10 ticks
one_way_delay_min=0 ticks
packet_loss_probability=23%
path_maximum_capacity=10 messages
path_clog_duration_mean=464 ticks
path_clog_probability=1%
packet_replay_probability=47%
partition_mode=testing.packet_simulator.PartitionMode.isolate_single
partition_symmetry=testing.packet_simulator.PartitionSymmetry.symmetric
partition_probability=2%
unpartition_probability=3%
partition_stability=100 ticks
unpartition_stability=8 ticks
read_latency_min=1
read_latency_mean=8
write_latency_min=0
write_latency_mean=81
read_fault_probability=4%
write_fault_probability=4%
crash_probability=0.00002%
crash_stability=873 ticks
restart_probability=0.0002%
restart_stability=946 ticks
 1/.1V0/__1/__1C0:__4Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?4/4Pp2/3Rq
 2\.1V0/__1/__1C0:__5Jo0/_3J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.1V0/__1/__1C0:__4Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 1/.1V0/__2/__2C0:__5Jo0/_1J!0:_31Wo <__0:__0>0Ga0G!0G?4/4Pp1/3Rq
 2\.1V0/__2/__2C0:__6Jo0/_2J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.1V0/__2/__2C0:__4Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 0\ .1V0/__1/__2C0:__4Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 0\ .1V0/__2/__2C0:__4Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 2/.14V0/__3/__3C0:__6Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?4/4Pp2/3Rq
 3|.14V0/__3/__3C0:__6Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 1\.14V0/__3/__3C0:__6Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 2/.14V0/__4/__4C0:__7Jo0/_1J!0:_31Wo <__0:__0>0Ga0G!0G?4/4Pp1/3Rq
 2/.14V0/__5/__5C0:__8Jo0/_2J!0:_31Wo <__0:__0>0Ga0G!0G?4/4Pp0/3Rq
 2/.14V0/__6/__6C0:__8Jo0/_2J!0:_31Wo <__0:__0>0Ga0G!0G?3/4Pp0/3Rq
 1\.14V0/__4/__6C0:__6Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 1\.14V0/__5/__6C0:__6Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 1\.14V0/__6/__6C0:__6Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 0/ v15V0/__3/__6C0:__7Jo0/_1J!0:_31Wo <__0:__0>0Ga0G!0G?
 0/ v15V0/__4/__6C0:__7Jo0/_1J!0:_31Wo <__0:__0>0Ga0G!0G?
 0/ v15V0/__5/__6C0:__7Jo0/_1J!0:_31Wo <__0:__0>0Ga0G!0G?
 0/ v15V0/__6/__6C0:__7Jo0/_1J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.18V0/__4/__6C0:__9Jo0/_2J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.18V0/__5/__6C0:__9Jo0/_2J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.18V0/__6/__6C0:__9Jo0/_2J!0:_31Wo <__0:__0>0Ga0G!0G?
 2/.26V0/__7/__7C0:_10Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?4/4Pp3/3Rq
 0/ v27V0/__7/__7C0:_11Jo0/_1J!0:_31Wo <__0:__0>0Ga0G!0G?
 1/v31V0/__7/__7C0:_11Jo0/_1J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.32V0/__7/__7C0:_11Jo0/_1J!0:_31Wo <__0:__0>0Ga0G!0G?
 2/.32V0/__8/__8C0:_11Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?4/4Pp2/3Rq
 2/.32V0/__9/__9C0:_12Jo0/_1J!0:_31Wo <__0:__0>0Ga0G!0G?4/4Pp1/3Rq
 2/.32V0/_10/_10C0:_13Jo0/_2J!0:_31Wo <__0:__0>0Ga0G!0G?4/4Pp0/3Rq
 2/.32V0/_11/_11C0:_13Jo0/_2J!0:_31Wo <__0:__0>0Ga0G!0G?3/4Pp0/3Rq
 0\ .32V0/__8/__8C0:_12Jo0/_1J!0:_31Wo <__0:__0>0Ga0G!0G?
 0\ .32V0/__9/__9C0:_13Jo0/_2J!0:_31Wo <__0:__0>0Ga0G!0G?
 0\ .32V0/_10/_11C0:_13Jo0/_2J!0:_31Wo <__0:__0>0Ga0G!0G?
 0\ .32V0/_11/_11C0:_13Jo0/_2J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.32V0/__8/_11C0:_11Jo0/_1J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.32V0/__9/_11C0:_11Jo0/_1J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.32V0/_10/_11C0:_11Jo0/_1J!0:_31Wo <__0:__0>0Ga0G!0G?
 1\.32V0/__8/_11C0:_14Jo0/_3J!0:_31Wo <__0:__0>0Ga0G!0G?
 1\.32V0/__9/_11C0:_14Jo0/_3J!0:_31Wo <__0:__0>0Ga0G!0G?
 1\.32V0/_10/_11C0:_14Jo0/_3J!0:_31Wo <__0:__0>0Ga0G!0G?
 1\.32V0/_11/_11C0:_14Jo0/_3J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.32V0/_11/_11C0:_14Jo0/_2J!0:_31Wo <__0:__0>0Ga0G!0G?
 1/.40V0/_12/_12C0:_15Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?4/4Pp2/3Rq
 1/.40V0/_13/_13C0:_16Jo0/_1J!0:_31Wo <__0:__0>0Ga0G!0G?4/4Pp1/3Rq
 2\.40V0/_12/_12C0:_16Jo0/_1J!0:_31Wo <__0:__0>0Ga0G!0G?
 2\.40V0/_13/_13C0:_17Jo0/_2J!0:_31Wo <__0:__0>0Ga0G!0G?
 1/.40V0/_14/_14C0:_17Jo0/_2J!0:_31Wo <__0:__0>0Ga0G!0G?4/4Pp0/3Rq
 1/.40V0/_15/_15C0:_17Jo0/_2J!0:_31Wo <__0:__0>0Ga0G!0G?3/4Pp0/3Rq
 2\.40V0/_14/_15C0:_17Jo0/_2J!0:_31Wo <__0:__0>0Ga0G!0G?
 2\.40V0/_15/_15C0:_17Jo0/_2J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.40V0/_12/_15C0:_15Jo0/_1J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.40V0/_13/_15C0:_15Jo0/_1J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.40V0/_14/_15C0:_15Jo0/_1J!0:_31Wo <__0:__0>0Ga0G!0G?
 0/ v42V0/_12/_15C0:_18Jo0/_3J!0:_31Wo <__0:__0>0Ga0G!0G?
 0/ v42V0/_13/_15C0:_18Jo0/_3J!0:_31Wo <__0:__0>0Ga0G!0G?
 0/ v42V0/_14/_15C0:_18Jo0/_3J!0:_31Wo <__0:__0>0Ga0G!0G?
 0/ v42V0/_15/_15C0:_18Jo0/_3J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.40V0/_15/_15C0:_15Jo0/_1J!0:_31Wo <__0:__0>14Ga0G!0G?
 2/.50V0/_16/_16C0:_19Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?4/4Pp3/3Rq
 0\ .50V0/_16/_16C0:_20Jo0/_2J!0:_31Wo <__0:__0>15Ga0G!0G?
 1\.50V0/_16/_16C0:_19Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.50V0/_16/_16C0:_19Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 0/ .57V0/_17/_17C0:_20Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?4/4Pp1/3Rq
 2\.57V0/_17/_17C0:_20Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 0/ .57V0/_18/_18C0:_21Jo0/_1J!0:_31Wo <__0:__0>15Ga0G!0G?4/4Pp0/3Rq
 2\.57V0/_18/_18C0:_20Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.57V0/_17/_18C0:_22Jo0/_2J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.57V0/_18/_18C0:_22Jo0/_2J!0:_31Wo <__0:__0>15Ga0G!0G?
 1/v58V0/_17/_18C0:_22Jo0/_2J!0:_31Wo <__0:__0>15Ga0G!0G?
 1/v58V0/_18/_18C0:_22Jo0/_2J!0:_31Wo <__0:__0>15Ga0G!0G?
 0/ .66V0/_19/_19C0:_22Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?4/4Pp1/3Rq
 2\.66V0/_19/_19C0:_22Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.66V0/_19/_19C0:_23Jo0/_2J!0:_31Wo <__0:__0>15Ga0G!0G?
 1\.66V0/_19/_19C0:_22Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 1/.70V0/_20/_20C0:_23Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?4/4Pp3/3Rq
 2\.70V0/_20/_20C0:_24Jo0/_2J!0:_31Wo <__0:__0>15Ga0G!0G?
 0\ .70V0/_20/_20C0:_23Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 1/.70V0/_21/_21C0:_24Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?4/4Pp3/3Rq
 1/.70V0/_22/_22C0:_25Jo0/_1J!0:_31Wo <__0:__0>15Ga0G!0G?4/4Pp2/3Rq
 3|.70V0/_20/_22C0:_26Jo0/_3J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_21/_22C0:_26Jo0/_3J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_22/_22C0:_26Jo0/_3J!0:_31Wo <__0:__0>15Ga0G!0G?
 0\ .70V0/_21/_22C0:_26Jo0/_2J!0:_31Wo <__0:__0>15Ga0G!0G?
 0\ .70V0/_22/_22C0:_26Jo0/_2J!0:_31Wo <__0:__0>15Ga0G!0G?
 1/.70V0/_23/_23C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?4/4Pp2/3Rq
 0\ .70V0/_23/_23C0:_26Jo0/_2J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_23/_23C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 2\.70V0/_21/_23C0:_26Jo0/_2J!0:_31Wo <__0:__0>15Ga0G!0G?
 2\.70V0/_22/_23C0:_26Jo0/_2J!0:_31Wo <__0:__0>15Ga0G!0G?
 2\.70V0/_23/_23C0:_26Jo0/_2J!0:_31Wo <__0:__0>15Ga0G!0G?
 1/.70V0/_24/_24C0:_27Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?4/4Pp2/3Rq
 1/.70V0/_25/_25C0:_28Jo0/_1J!0:_31Wo <__0:__0>15Ga0G!0G?4/4Pp1/3Rq
 0\ .70V0/_24/_25C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 0\ .70V0/_25/_25C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_24/_25C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_25/_25C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 2\.70V0/_24/_25C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 2\.70V0/_25/_25C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3 $ ##
 2/.74V0/_26/_26C0:_29Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?4/4Pp0/3Rq
 2/.74V0/_27/_27C0:_29Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?3/4Pp0/3Rq
 2 [ /.74V0/_27/_27C0:_29Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?2/4Pp0/3Rq
 1\.74V0/_26/_27C0:_29Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 1\.74V0/_27/_27C0:_29Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 1 [ \.74V0/_27/_27C0:_29Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 0\ .74V0/_26/_27C0:_30Jo0/_1J!0:_31Wo <__0:__0>15Ga0G!0G?
 0\ .74V0/_27/_27C0:_30Jo0/_1J!0:_31Wo <__0:__0>15Ga0G!0G?
 0 [ \ .74V0/_27/_27C0:_30Jo0/_1J!0:_31Wo <__0:__0>15Ga0G!0G?
 2 ] /.74V23/_27/_27C0:_31Jo0/_2J!0:_31Wo <__0:__0>17Ga0G!0G?4/4Pp0/3Rq
 2/.74V23/_28/_28C0:_31Jo0/_2J!0:_31Wo <__0:__0>17Ga0G!0G?4/4Pp0/3Rq
 2/.74V23/_29/_29C0:_31Jo0/_2J!0:_31Wo <__0:__0>18Ga0G!0G?3/4Pp0/3Rq
 2/.74V23/_30/_30C0:_31Jo0/_1J!0:_31Wo <__0:__0>18Ga0G!0G?2/4Pp0/3Rq
 2/.74V23/_31/_31C3:_34Jo0/_3J!0:_33Wo <__0:__0>18Ga0G!0G?4/4Pp0/3Rq
 1 ] \.74V23/_27/_31C0:_29Jo0/_0J!0:_31Wo <__0:__0>17Ga0G!0G?
 0 ] \ .74V23/_27/_31C0:_31Jo0/_0J!0:_31Wo <__0:__0>17Ga0G!0G?
 0\ .74V23/_28/_31C0:_31Jo0/_0J!0:_31Wo <__0:__0>17Ga0G!0G?
 0\ .74V23/_29/_31C0:_31Jo0/_0J!0:_31Wo <__0:__0>18Ga0G!0G?
 0\ .74V23/_30/_31C0:_31Jo0/_0J!0:_31Wo <__0:__0>18Ga0G!0G?
 0\ .74V23/_31/_31C0:_31Jo0/_0J!0:_31Wo <__0:__0>18Ga0G!0G?
 1\.74V23/_28/_31C1:_32Jo0/_2J!1:_32Wo <__0:__0>17Ga0G!0G?
 1\.74V23/_29/_31C1:_32Jo0/_2J!1:_32Wo <__0:__0>18Ga0G!0G?
 1\.74V23/_30/_31C1:_32Jo0/_2J!1:_32Wo <__0:__0>18Ga0G!0G?
 1\.74V23/_31/_31C1:_32Jo0/_2J!1:_32Wo <__0:__0>18Ga0G!0G?
 0 $ # #
 0  / h75V23/_23/_31C16:_35Jo 15/15J!4:_35Wo <__0:__0>nullGa0G!0G?
 3  |.70V0/__0/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>nullGa0G!0G?
 3|.70V0/__1/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__2/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__3/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__4/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__5/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__6/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__7/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__8/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__9/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_10/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_11/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_12/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_13/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_14/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_15/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>14Ga0G!0G?
 3|.70V0/_16/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_17/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_18/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_19/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_20/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_21/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_22/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 2 $ ##
 2  \v559V23/_23/_31C4:_35Jo0/_0J!4:_35Wo <__0:__0>nullGa0G!0G?
 2 $ ##
 2  \v904V23/_23/_31C4:_35Jo0/_0J!4:_35Wo <__0:__0>nullGa0G!0G?
 2 $ ##
 2  \v1014V23/_23/_31C4:_35Jo0/_0J!4:_35Wo <__0:__0>nullGa0G!0G?
 1 $ ##
 1  /v1222V23/_23/_31C2:_35Jo0/_0J!2:_35Wo <__0:__0>nullGa0G!0G?
 2 $ ##
 2  /v1556V23/_23/_31C4:_35Jo0/_0J!4:_35Wo <__0:__0>nullGa0G!0G?
 2/v1556V23/_24/_31C4:_35Jo0/_0J!4:_35Wo <__0:__0>17Ga0G!0G?
 2/v1556V23/_25/_31C4:_35Jo0/_0J!4:_35Wo <__0:__0>17Ga0G!0G?
 2/v1556V23/_26/_31C4:_35Jo0/_0J!4:_35Wo <__0:__0>17Ga0G!0G?
 2/v1556V23/_27/_31C4:_35Jo0/_0J!4:_35Wo <__0:__0>17Ga0G!0G?
 2/v1556V23/_28/_31C4:_35Jo0/_0J!4:_35Wo <__0:__0>17Ga0G!0G?
 2/v1556V23/_29/_31C4:_35Jo0/_0J!4:_35Wo <__0:__0>18Ga0G!0G?
 2/v1556V23/_30/_31C4:_35Jo0/_0J!4:_35Wo <__0:__0>18Ga0G!0G?
 2/v1556V23/_31/_31C4:_35Jo0/_0J!4:_35Wo <__0:__0>18Ga0G!0G?
 0 $ # #
 0  / h75V23/_23/_31C16:_35Jo 15/15J!4:_35Wo <__0:__0>nullGa0G!0G?
 1 $ ##
 1  \v2660V23/_23/_31C2:_35Jo0/_0J!2:_35Wo <__0:__0>nullGa0G!0G?
 3 $ ##
 1 $ ##
 3  |.70V0/__0/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>nullGa0G!0G?
 3|.70V0/__1/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__2/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__3/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__4/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__5/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__6/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__7/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__8/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__9/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_10/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_11/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_12/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_13/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_14/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_15/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>14Ga0G!0G?
 3|.70V0/_16/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_17/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_18/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_19/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_20/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_21/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_22/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 1  \v2816V23/_23/_31C2:_35Jo0/_0J!2:_35Wo <__0:__0>nullGa0G!0G?
 1 $ ##
 1  \v3185V23/_23/_31C2:_35Jo0/_0J!2:_35Wo <__0:__0>nullGa0G!0G?
 1 $ ##
 1  \v3977V23/_23/_31C2:_35Jo0/_0J!2:_35Wo <__0:__0>nullGa0G!0G?
 1 $ ##
 1  /v4342V23/_23/_31C2:_35Jo0/_0J!2:_35Wo <__0:__0>nullGa0G!0G?
 2 $ ##
 2  \v4645V23/_23/_31C4:_35Jo0/_0J!4:_35Wo <__0:__0>nullGa0G!0G?
 3 $ ##
 3  |.70V0/__0/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>nullGa0G!0G?
 3|.70V0/__1/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__2/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__3/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__4/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__5/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__6/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__7/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__8/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__9/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_10/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_11/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_12/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_13/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_14/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_15/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>14Ga0G!0G?
 3|.70V0/_16/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_17/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_18/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_19/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_20/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_21/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_22/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 1 $ ##
 3 $ ##
 3  |.70V0/__0/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>nullGa0G!0G?
 3|.70V0/__1/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__2/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__3/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__4/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__5/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__6/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__7/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__8/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__9/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_10/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_11/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_12/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_13/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_14/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_15/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>14Ga0G!0G?
 3|.70V0/_16/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_17/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_18/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_19/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_20/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_21/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_22/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 1  \v6822V23/_23/_31C2:_35Jo0/_0J!2:_35Wo <__0:__0>nullGa0G!0G?
 3 $ ##
 3  |.70V0/__0/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>nullGa0G!0G?
 3|.70V0/__1/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__2/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__3/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__4/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__5/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__6/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__7/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__8/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__9/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_10/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_11/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_12/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_13/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_14/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_15/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>14Ga0G!0G?
 3|.70V0/_16/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_17/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_18/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_19/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_20/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_21/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_22/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 1 $ ##
 0 $ # #
 1  /v8671V23/_23/_31C2:_35Jo0/_0J!2:_35Wo <__0:__0>nullGa0G!0G?
 0  / h75V23/_23/_31C16:_35Jo 15/15J!4:_35Wo <__0:__0>nullGa0G!0G?
 2 $ ##
 3 $ ##
 2  \v9750V23/_23/_31C4:_35Jo0/_0J!4:_35Wo <__0:__0>nullGa0G!0G?
 1 $ ##
 1  \v10445V23/_23/_31C2:_35Jo0/_0J!2:_35Wo <__0:__0>nullGa0G!0G?
 3  |.70V0/__0/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>nullGa0G!0G?
 3|.70V0/__1/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__2/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__3/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__4/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__5/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__6/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__7/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__8/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__9/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_10/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_11/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_12/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_13/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_14/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_15/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>14Ga0G!0G?
 3|.70V0/_16/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_17/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_18/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_19/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_20/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_21/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_22/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 1 $ ##
 1  /v10903V23/_23/_31C2:_35Jo0/_0J!2:_35Wo <__0:__0>nullGa0G!0G?
 1 $ ##
 3 $ ##
 1  \v10946V23/_23/_31C2:_35Jo0/_0J!2:_35Wo <__0:__0>nullGa0G!0G?
 1 $ ##
 2 $ ##
 3  |.70V0/__0/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>nullGa0G!0G?
 3|.70V0/__1/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__2/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__3/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__4/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__5/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__6/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__7/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__8/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__9/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_10/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_11/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_12/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_13/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_14/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_15/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>14Ga0G!0G?
 3|.70V0/_16/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_17/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_18/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_19/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_20/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_21/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_22/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 2  \v11091V23/_23/_31C4:_35Jo0/_0J!4:_35Wo <__0:__0>nullGa0G!0G?
 3 $ ##
 3  |.70V0/__0/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>nullGa0G!0G?
 3|.70V0/__1/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__2/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__3/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__4/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__5/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__6/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__7/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__8/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__9/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_10/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_11/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_12/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_13/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_14/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_15/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>14Ga0G!0G?
 3|.70V0/_16/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_17/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_18/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_19/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_20/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_21/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_22/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 1  \v11091V23/_23/_31C2:_35Jo0/_0J!2:_35Wo <__0:__0>nullGa0G!0G?
 2 $ ##
 2  \v11458V23/_23/_31C4:_35Jo0/_0J!4:_35Wo <__0:__0>nullGa0G!0G?
 1 $ ##
 1  \v11540V23/_23/_31C2:_35Jo0/_0J!2:_35Wo <__0:__0>nullGa0G!0G?
 3 $ ##
 3  |.70V0/__0/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>nullGa0G!0G?
 3|.70V0/__1/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__2/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__3/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__4/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__5/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__6/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__7/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__8/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__9/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_10/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_11/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_12/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_13/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_14/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_15/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>14Ga0G!0G?
 3|.70V0/_16/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_17/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_18/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_19/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_20/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_21/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_22/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3 $ ##
 2 $ ##
 2  /v12116V23/_23/_31C4:_35Jo0/_0J!4:_35Wo <__0:__0>nullGa0G!0G?
 2/v12116V23/_24/_31C4:_35Jo0/_0J!4:_35Wo <__0:__0>17Ga0G!0G?
 2/v12116V23/_25/_31C4:_35Jo0/_0J!4:_35Wo <__0:__0>17Ga0G!0G?
 2/v12116V23/_26/_31C4:_35Jo0/_0J!4:_35Wo <__0:__0>17Ga0G!0G?
 2/v12116V23/_27/_31C4:_35Jo0/_0J!4:_35Wo <__0:__0>17Ga0G!0G?
 2/v12116V23/_28/_31C4:_35Jo0/_0J!4:_35Wo <__0:__0>17Ga0G!0G?
 2/v12116V23/_29/_31C4:_35Jo0/_0J!4:_35Wo <__0:__0>18Ga0G!0G?
 2/v12116V23/_30/_31C4:_35Jo0/_0J!4:_35Wo <__0:__0>18Ga0G!0G?
 2/v12116V23/_31/_31C4:_35Jo0/_0J!4:_35Wo <__0:__0>18Ga0G!0G?
 2 $ ##
 2  \v12544V23/_23/_31C4:_35Jo0/_0J!4:_35Wo <__0:__0>nullGa0G!0G?
 3  |.70V0/__0/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>nullGa0G!0G?
 3|.70V0/__1/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__2/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__3/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__4/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__5/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__6/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__7/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__8/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__9/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_10/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_11/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_12/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_13/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_14/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_15/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>14Ga0G!0G?
 3|.70V0/_16/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_17/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_18/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_19/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_20/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_21/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_22/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 1 $ ##
 1  \v13293V23/_23/_31C2:_35Jo0/_0J!2:_35Wo <__0:__0>nullGa0G!0G?
 1 $ ##
 1  \v13619V23/_23/_31C2:_35Jo0/_0J!2:_35Wo <__0:__0>nullGa0G!0G?
 2 $ ##
 2  /v13679V23/_23/_31C4:_35Jo0/_0J!4:_35Wo <__0:__0>nullGa0G!0G?
 2/v13679V23/_24/_31C4:_35Jo0/_0J!4:_35Wo <__0:__0>17Ga0G!0G?
 2/v13679V23/_25/_31C4:_35Jo0/_0J!4:_35Wo <__0:__0>17Ga0G!0G?
 2/v13679V23/_26/_31C4:_35Jo0/_0J!4:_35Wo <__0:__0>17Ga0G!0G?
 2/v13679V23/_27/_31C4:_35Jo0/_0J!4:_35Wo <__0:__0>17Ga0G!0G?
 2/v13679V23/_28/_31C4:_35Jo0/_0J!4:_35Wo <__0:__0>17Ga0G!0G?
 2/v13679V23/_29/_31C4:_35Jo0/_0J!4:_35Wo <__0:__0>18Ga0G!0G?
 2/v13679V23/_30/_31C4:_35Jo0/_0J!4:_35Wo <__0:__0>18Ga0G!0G?
 2/v13679V23/_31/_31C4:_35Jo0/_0J!4:_35Wo <__0:__0>18Ga0G!0G?
 1 $ ##
 1  \v13905V23/_23/_31C2:_35Jo0/_0J!2:_35Wo <__0:__0>nullGa0G!0G?
 0 $ # #
 0  / h75V23/_23/_31C16:_35Jo 15/15J!4:_35Wo <__0:__0>nullGa0G!0G?
 3 $ ##
 2 $ ##
 3  |.70V0/__0/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>nullGa0G!0G?
 3|.70V0/__1/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__2/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__3/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__4/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__5/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__6/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__7/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__8/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__9/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_10/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_11/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_12/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_13/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_14/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_15/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>14Ga0G!0G?
 3|.70V0/_16/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_17/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_18/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_19/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_20/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_21/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_22/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 2  \v15166V23/_23/_31C4:_35Jo0/_0J!4:_35Wo <__0:__0>nullGa0G!0G?
 1 $ ##
 3 $ ##
 3  |.70V0/__0/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>nullGa0G!0G?
 3|.70V0/__1/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__2/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__3/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__4/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__5/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__6/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__7/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__8/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__9/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_10/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_11/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_12/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_13/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_14/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_15/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>14Ga0G!0G?
 3|.70V0/_16/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_17/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_18/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_19/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_20/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_21/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_22/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 1  /v15472V23/_23/_31C2:_35Jo0/_0J!2:_35Wo <__0:__0>nullGa0G!0G?
 0 $ # #
 0  / h75V23/_23/_31C16:_35Jo 15/15J!4:_35Wo <__0:__0>nullGa0G!0G?
 0 $ # #
 0  / h75V23/_23/_31C16:_35Jo 15/15J!4:_35Wo <__0:__0>nullGa0G!0G?
 3 $ ##
 1 $ ##
 1  \v16692V23/_23/_31C2:_35Jo0/_0J!2:_35Wo <__0:__0>nullGa0G!0G?
 3  |.70V0/__0/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>nullGa0G!0G?
 3|.70V0/__1/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__2/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__3/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__4/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__5/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__6/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__7/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__8/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/__9/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_10/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_11/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_12/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_13/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_14/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.70V0/_15/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>14Ga0G!0G?
 3|.70V0/_16/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_17/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_18/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_19/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_20/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_21/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 3|.70V0/_22/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
 0 $ # #
 0  / h75V23/_23/_31C16:_35Jo 15/15J!4:_35Wo <__0:__0>nullGa0G!0G?
 2 $ ##
 2  \v17964V23/_23/_31C4:_35Jo0/_0J!4:_35Wo <__0:__0>nullGa0G!0G?
no liveness, final cluster state (requests_max=96 requests_replied=24):
 0/ h75V23/_23/_31C16:_35Jo 15/15J!4:_35Wo <__0:__0>17Ga0G!0G?
 1\v18317V23/_23/_31C2:_35Jo0/_0J!2:_35Wo <__0:__0>17Ga0G!0G?
 2/v18317V23/_23/_31C4:_35Jo0/_0J!4:_35Wo <__0:__0>17Ga0G!0G?
 3|.70V0/_22/_22C0:_26Jo0/_0J!0:_31Wo <__0:__0>15Ga0G!0G?
you can reproduce this failure with seed=15677965580699030051
unable to complete requests_committed_max before ticks_max
debug: exit with code: 128


```
</details>

### PR DESCRIPTION
**Pull request by matklad**
A DVC with a log-view `v` includes _some_ of the
potentially committed messages for views `≥v`.

However, it will include all potentially committed
messages from views `<v`:

log-view=v means that a replica accepted an SV
message for that view (or the replica was a
primary for that view). In any case, the starting
headers for that view were durably persisted by
the replica.

So all those headers must be a part of DVC the
replica subsequently sends.

This means that if

- we are deciding whether we should truncate op=x
- we _don't_ know the canonical header for op=x
- and we have an uncanonical DVC with a header for op=x with view<log_view_canonical

That DVC is a nack for `op=x`. We don't know which
header would be canonical, but it definitely isn't
the one from the DVC.

Seed: 15677965580699030051
Closes: https://github.com/tigerbeetle/tigerbeetle/issues/1510

### CODE REVIEW

File: src/vsr/replica.zig [hunk 1]
```diff
@@ -8967,11 +8968,17 @@ const DVCQuorum = struct {
...
-                    nacks += 1;
+                } else if (vsr.Headers.dvc_header_type(header) == .valid) {
+                    if (header_canonical != null and header_canonical.?.checksum != header.checksum) {
+                        // The op is nacked implicitly, because the replica has a different header.
+                        nacks += 1;
+                    }
+                    if (header_canonical == null and header.view <= log_view_canonical) {
+                        assert(dvc.header.log_view < log_view_canonical);
+                        // The op is nacked implicitly, because the header have already been
+                        // truncated in the latest log_view.
```
Comment (sentientwaffle) [inline src/vsr/replica.zig]: Parse error :smile: 
Is "header" meant to be plural? Otherwise replace "have" with "has".

File: src/vsr/replica.zig [hunk 2]
```diff
@@ -8967,11 +8968,17 @@ const DVCQuorum = struct {
...
-                {
-                    // The op is nacked implicitly, because the replica has a different header.
-                    nacks += 1;
+                } else if (vsr.Headers.dvc_header_type(header) == .valid) {
+                    if (header_canonical != null and header_canonical.?.checksum != header.checksum) {
+                        // The op is nacked implicitly, because the replica has a different header.
+                        nacks += 1;
+                    }
+                    if (header_canonical == null and header.view <= log_view_canonical) {
+                        assert(dvc.header.log_view < log_view_canonical);
```
Comment (sentientwaffle) [inline src/vsr/replica.zig:8978]: Just explaining this for my future self:

- We know that `dvc.header.log_view != log_view_canonical` (this DVC not canonical), since otherwise `header_canonical` would be equal to this current `header`, not `null`.
- `dvc.header.log_view` can't be _greater_ than `log_view_canonical` since `log_view_canonical` is (by definition) the highest log view of all DVCs in the quorum.

File: src/vsr/replica_test.zig [hunk 3]
```diff
@@ -857,6 +857,63 @@ test "Cluster: view-change: primary with dirty log" {
     // try expectEqual(b2.status(), .normal);
 }
 
+test "Cluster: view-change: nack older view" {
+    // a0 prepares (but does not commit) three ops (`x`, `x + 1`, `x + 2`) at view `v`.
+    // b1 prepares (but does not commit) the same ops at view `v + 1`.
```
Comment (sentientwaffle) [inline src/vsr/replica_test.zig:862]: Both to check my understanding and clarify: The ops are the same, but these are different 'versions' of the ops (prepared in a different view than `a0`).

File: src/vsr/replica_test.zig [hunk 4]
```diff
@@ -1511,6 +1568,25 @@ const TestReplicas = struct {
         for (paths.const_slice()) |path| t.cluster.network.link_filter(path).remove(command);
     }
 
+    pub fn filter(
+        t: *const TestReplicas,
+        peer: ProcessSelector,
+        direction: LinkDirection,
+        comptime drop_message_fn: ?fn (message: *Message) bool,
+    ) void {
```
Comment (sentientwaffle) [inline src/vsr/replica_test.zig:1576]: :tada:

File: src/vsr/replica.zig [hunk 5]
```diff
@@ -8967,11 +8968,17 @@ const DVCQuorum = struct {
...
-                    header_canonical != null and header_canonical.?.checksum != header.checksum)
-                {
-                    // The op is nacked implicitly, because the replica has a different header.
-                    nacks += 1;
+                } else if (vsr.Headers.dvc_header_type(header) == .valid) {
+                    if (header_canonical != null and header_canonical.?.checksum != header.checksum) {
+                        // The op is nacked implicitly, because the replica has a different header.
+                        nacks += 1;
+                    }
+                    if (header_canonical == null and header.view <= log_view_canonical) {
```
Comment (sentientwaffle) [inline src/vsr/replica.zig]: :thinking: Why `<= log_view_canonical` rather than `< log_view_canonical`?

First of all: Isn't `header.view <= log_view_canonical` _always_ true for `header` (even outside this branch)?
If `header.view > log_view_canonical`, then that means that `header` was prepared in a newer-than-canonical view, which means that this DVC's `log_view` should be greater than `log_view_canonical`, which is impossible.

(On that note, can we `assert(header.view <= log_view_canonical);` we define `const header =` above?)

And second: The conjunction `header_canonical == null and header.view == log_view_canonical` should be impossible, since `header.view == log_view_canonical` implies that this DVC's `log_view` is exactly `log_view_canonical`. But if this DVC's `log_view` is `log_view_canonical`, then this DVC is canonical, so `header_canonical == header`, and therefore `header_canonical != null`.

File: src/vsr/replica_test.zig (hunk 3 above)
Comment (matklad) [reply src/vsr/replica_test.zig:862]: Exactly!

File: src/vsr/replica_test.zig (hunk 4 above)
Comment (matklad) [reply src/vsr/replica_test.zig:1576]: TBH, I am not a huge fan of this API, Zig makes passing functions in painful. And there's some extra nastiness around the `Packet` type which is abstract at the level of PacketSimulator

I considered adding a more locked-down API which would require passing just a slice of op-numbers to pass/drop, but figured that we'll need fully general predicate API anyway at some point.

Comment (sentientwaffle) [reply src/vsr/replica_test.zig:1576]: Yeah, I imagine that most uses will be "drop prepares with these ops" or "drop acks with these ops".

File: src/vsr/replica.zig (hunk 5 above)
Comment (matklad) [reply src/vsr/replica.zig]: Typo! Should definitely be just `<`!

Amusingly, it was `<` in the first version: 

https://github.com/tigerbeetle/tigerbeetle/pull/1517/files#diff-e95e4dc6c1aae349e798cfeed22ad01f830cce0e654e6b4b765b3e7b0c677b6aR8977

, but I forgot about that WIP PR when preparing this version.

**Review by sentientwaffle — APPROVED** [review]
