### PR TITLE
References the `native` subfolder so external files required by CGO aren't pruned.

### LINKED ISSUE #3158: Golang client vendor issue
## Problem
When building the go application using a vendor directory, the build fails due to the vendor command not copying the headers:

## How to reproduce

1. In any go application using the latest golang client, run `go mod vendor`
2. build or run the application

### Here is the output on my machine
```bash
$ go run main.go  
# github.com/tigerbeetle/tigerbeetle-go/pkg/types
vendor/github.com/tigerbeetle/tigerbeetle-go/pkg/types/bindings.go:9:10: fatal error: ../native/tb_client.h: No such file or directory
    9 | #include "../native/tb_client.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

Doing so without the vendor directory (or with `-mod=mod` flag) will solve the issue but vendor directory is not used anymore.

### Here is my go.mod

```go.mod
module tbtest

go 1.24.4

require github.com/tigerbeetle/tigerbeetle-go v0.16.53 // indirect
```

### PR DESCRIPTION
**Pull request by batiati**
Related: https://github.com/golang/go/issues/26366

We could remove the `native` folder and move all files to the root. See ["#including source files in subdirectories is a bad idea"](https://go-review.googlesource.com/c/go/+/125297/5/src/cmd/cgo/doc.go).

But we prefer to keep the root clean and minimal, so we embrace the `native` subfolder and declare a dummy package there to force references.

Additionally, now the compiled library carries the platform as part of the filename instead of using subfolders, avoiding the need to declare packages to force reference each subfolder.

Closes https://github.com/tigerbeetle/tigerbeetle/issues/3158

### CODE REVIEW

File: build.zig [hunk 1]
```diff
@@ -5,6 +5,7 @@ const Query = std.Target.Query;
 const Mode = std.builtin.Mode;
 
 const config = @import("./src/config.zig");
+const stdx = @import("./src/stdx/stdx.zig");
```
Comment (matklad) [inline build.zig]: Hm, yeah, I'd maybe avoid this! This is not too bad, but, still, it'll cause the build system to read all those stdx file, and then to stat them on each build execution (I _think_ zig parses even unused `@import`s? Not sure here).

File: build.zig [hunk 2]
```diff
@@ -1298,10 +1299,20 @@ fn build_go_client(
...
+        const file_name: []const u8, const extension: []const u8 = stdx.cut(
+            lib.out_lib_filename,
+            ".",
+        ).?;
+
         // NB: New way to do lib.setOutputDir(). The ../ is important to escape zig-cache/.
         step_clients_go.dependOn(&b.addInstallFile(
             lib.getEmittedBin(),
-            b.pathJoin(&.{ "../src/clients/go/pkg/native/", name, lib.out_filename }),
+            std.fmt.allocPrint(b.allocator, "../src/clients/go/pkg/native/{s}_{s}.{s}", .{
```
Comment (matklad) [inline build.zig]: I think there's `b.fmt`?

File: build.zig (hunk 1 above)
Comment (matklad) [reply build.zig]: Or maybe not? It's not like  `@import("std")` would behave differently (which probably means that I am wrong, and Zig won't actually parse more than necessary here). I guess I am just confused, would be happy with either approach!

**Review by matklad — APPROVED** [review]

**Comment by matklad** [comment]
Looking at the build_go and publish_go, I _think_ it should work fine but still should maybe manually check on Monday that the release is ok!

**Comment by batiati** [comment]
> Looking at the build_go and publish_go, I _think_ it should work fine but still should maybe manually check on Monday that the release is ok!

It should be ok, nothing changed in the published repo, as we still have the same `native` folder.
Anyway, I'll keep an eye on it Monday.
