### PR TITLE
Trust committed ops

### LINKED ISSUE #100: Correctness: 4296338862809504700
<strong>Commit:</strong> 0ac50f181e373f6e5b6465d0b3935986442d8cc4<br>
<strong>Parameters:</strong><br>
```
seed=4296338862809504700
replicas=3
clients=3
request_probability=68%
idle_on_probability=7%
idle_off_probability=19%
one_way_delay_mean=3 ticks
one_way_delay_min=1 ticks
packet_loss_probability=12%
path_maximum_capacity=19 messages
path_clog_duration_mean=193 ticks
path_clog_probability=1%
packet_replay_probability=44%
partition_mode=PartitionMode.uniform_size
partition_probability=2%
unpartition_probability=2%
partition_stability=183 ticks
unpartition_stability=1 ticks
read_latency_min=0
read_latency_mean=9
write_latency_min=0
write_latency_mean=80
read_fault_probability=3%
write_fault_probability=0%
crash_probability=0.01%
crash_stability=190 ticks
restart_probability=1%
restart_stability=395 ticks
```

<strong>Stack Trace:</strong><br>
```
thread panic: reached unreachable code
zig/lib/std/debug.zig:225:14: in std.debug.assert (simulator)
if (!ok) unreachable; // assertion failure

src/vsr/replica.zig:2285:19: in vsr.replica.Replica(test.state_machine.StateMachine,test.message_bus.MessageBus,test.storage.Storage,test.time.Time).commit_op (simulator)
assert(self.state_machine.commit_timestamp &lt; prepare.header.timestamp);

src/vsr/replica.zig:2247:27: in vsr.replica.Replica(test.state_machine.StateMachine,test.message_bus.MessageBus,test.storage.Storage,test.time.Time).commit_ops_commit (simulator)
self.commit_op(prepare.?);

src/vsr/journal.zig:875:26: in vsr.journal.Journal(vsr.replica.Replica(test.state_machine.StateMachine,test.message_bus.MessageBus,test.storage.Storage,test.time.Time),test.storage.Storage).read_prepare_with_op_and_checksum_callback (simulator)
read.callback(replica, read.message, read.destination_replica);

src/test/storage.zig:225:22: in test.storage.Storage.read_sectors_finish (simulator)
read.callback(read);

src/test/storage.zig:175:40: in test.storage.Storage.tick (simulator)
storage.read_sectors_finish(read);

src/simulator.zig:236:25: in main (simulator)
storage.tick();

zig/lib/std/start.zig:561:37: in std.start.callMain (simulator)
const result = root.main() catch |err| {

zig/lib/std/start.zig:495:12: in std.start.callMainWithArgs (simulator)
return @call(.{ .modifier = .always_inline }, callMain, .{});

zig/lib/std/start.zig:409:17: in std.start.posixCallMainAndExit (simulator)
std.os.exit(@call(.{ .modifier = .always_inline }, callMainWithArgs, .{ argc, argv, envp }));

zig/lib/std/start.zig:322:5: in std.start._start (simulator)
@call(.{ .modifier = .never_inline }, posixCallMainAndExit, .{});
```
<strong>Debug Logs:</strong><br>
<details><summary>Tail</summary><br>

```
[debug] (vsr): 335511138666577538158140751966064872959: request_timeout backing off
[debug] (vsr): 335511138666577538158140751966064872959: request_timeout after=86..80 (rtt=30 min=10 max=1000 attempts=2)
[debug] (client): 335511138666577538158140751966064872959: on_request_timeout: resending request=7 checksum=103341896402299122564620713873323123980
[debug] (client): 335511138666577538158140751966064872959: sending request to replica 0: Header{ .checksum = 103341896402299122564620713873323123980, .checksum_body = 98081761841810822994326224503485043631, .parent = 295722455584224246722095867023767655631, .client = 335511138666577538158140751966064872959, .context = 1, .request = 7, .cluster = 0, .epoch = 0, .view = 31, .op = 0, .commit = 0, .timestamp = 0, .size = 128, .replica = 0, .command = Command.request, .operation = Operation(3), .version = 0 }
[debug] (network): send_message: Process{ .client = 335511138666577538158140751966064872959 } &gt; Process{ .replica = 0 }: Command.request
[debug] (packet_simulator): replayed packet from=3 to=0
[debug] (network): deliver_message: Process{ .client = 335511138666577538158140751966064872959 } &gt; Process{ .replica = 0 }: Command.request
[debug] (replica): 0: on_message: view=33 status=Status.normal Header{ .checksum = 103341896402299122564620713873323123980, .checksum_body = 98081761841810822994326224503485043631, .parent = 295722455584224246722095867023767655631, .client = 335511138666577538158140751966064872959, .context = 1, .request = 7, .cluster = 0, .epoch = 0, .view = 31, .op = 0, .commit = 0, .timestamp = 0, .size = 128, .replica = 0, .command = Command.request, .operation = Operation(3), .version = 0 }
[err] (replica): 0: on_request: ignoring new request (client bug)
[err] (packet_simulator): dropped packet from=3 to=0.
[debug] (packet_simulator): reverse path clogged
[debug] (packet_simulator): Path path.source=4 path.target=3 clogged for ticks=105
[debug] (packet_simulator): reverse path clogged
[debug] (packet_simulator): Path path.source=5 path.target=3 clogged for ticks=129
[debug] (vsr): 1: prepare_timeout fired
[debug] (vsr): 1: prepare_timeout backing off
[debug] (vsr): 1: prepare_timeout after=134..95 (rtt=30 min=10 max=1000 attempts=4)
[debug] (replica): 1: on_prepare_timeout: waiting for replica 0
[debug] (replica): 1: on_prepare_timeout: waiting for replica 2
[debug] (replica): 1: on_prepare_timeout: replicating to replica 0
[debug] (replica): 1: sending prepare to replica 0: Header{ .checksum = 274640755804917375998870706212380760139, .checksum_body = 197688710245638009225329894310189579105, .parent = 280919655732552742998137919384557100881, .client = 216211608991384047144981724848319393637, .context = 164199344481104444325627298724669288032, .request = 6, .cluster = 0, .epoch = 0, .view = 31, .op = 17, .commit = 15, .timestamp = 210690000000, .size = 1048576, .replica = 1, .command = Command.prepare, .operation = Operation(3), .version = 0 }
[debug] (network): send_message: Process{ .replica = 1 } &gt; Process{ .replica = 0 }: Command.prepare
[debug] (vsr): 0: ping_timeout fired
[debug] (vsr): 0: ping_timeout reset
[debug] (replica): 0: sending ping to replica 1: Header{ .checksum = 331381902754807014041750051262112387157, .checksum_body = 98081761841810822994326224503485043631, .parent = 0, .client = 0, .context = 0, .request = 0, .cluster = 0, .epoch = 0, .view = 33, .op = 213350000000, .commit = 0, .timestamp = 0, .size = 128, .replica = 0, .command = Command.ping, .operation = Operation.reserved, .version = 0 }
[debug] (network): send_message: Process{ .replica = 0 } &gt; Process{ .replica = 1 }: Command.ping
[debug] (replica): 0: sending ping to replica 2: Header{ .checksum = 331381902754807014041750051262112387157, .checksum_body = 98081761841810822994326224503485043631, .parent = 0, .client = 0, .context = 0, .request = 0, .cluster = 0, .epoch = 0, .view = 33, .op = 213350000000, .commit = 0, .timestamp = 0, .size = 128, .replica = 0, .command = Command.ping, .operation = Operation.reserved, .version = 0 }
[debug] (network): send_message: Process{ .replica = 0 } &gt; Process{ .replica = 2 }: Command.ping
[debug] (vsr): 0: commit_timeout fired
[debug] (vsr): 0: commit_timeout reset
[debug] (replica): 0: sending commit to replica 1: Header{ .checksum = 184077064347450765758370563638427619193, .checksum_body = 98081761841810822994326224503485043631, .parent = 0, .client = 0, .context = 78014756875457191332436470636089908915, .request = 0, .cluster = 0, .epoch = 0, .view = 33, .op = 0, .commit = 16, .timestamp = 0, .size = 128, .replica = 0, .command = Command.commit, .operation = Operation.reserved, .version = 0 }
[debug] (network): send_message: Process{ .replica = 0 } &gt; Process{ .replica = 1 }: Command.commit
[debug] (replica): 0: sending commit to replica 2: Header{ .checksum = 184077064347450765758370563638427619193, .checksum_body = 98081761841810822994326224503485043631, .parent = 0, .client = 0, .context = 78014756875457191332436470636089908915, .request = 0, .cluster = 0, .epoch = 0, .view = 33, .op = 0, .commit = 16, .timestamp = 0, .size = 128, .replica = 0, .command = Command.commit, .operation = Operation.reserved, .version = 0 }
[debug] (network): send_message: Process{ .replica = 0 } &gt; Process{ .replica = 2 }: Command.commit
[debug] (vsr): 0: repair_timeout fired
[debug] (vsr): 0: repair_timeout reset
[err] (packet_simulator): dropped packet (different partitions): from=0 to=1
[debug] (packet_simulator): delivering packet from=0 to=2
[debug] (network): deliver_message: Process{ .replica = 0 } &gt; Process{ .replica = 2 }: Command.commit
[debug] (replica): 2: on_message: view=33 status=Status.normal Header{ .checksum = 184077064347450765758370563638427619193, .checksum_body = 98081761841810822994326224503485043631, .parent = 0, .client = 0, .context = 78014756875457191332436470636089908915, .request = 0, .cluster = 0, .epoch = 0, .view = 33, .op = 0, .commit = 16, .timestamp = 0, .size = 128, .replica = 0, .command = Command.commit, .operation = Operation.reserved, .version = 0 }
[debug] (replica): 2: on_commit: checksum verified
[debug] (vsr): 2: normal_status_timeout reset
[debug] (vsr): 2: ping_timeout fired
[debug] (vsr): 2: ping_timeout reset
[debug] (replica): 2: sending ping to replica 0: Header{ .checksum = 153987012347772732798740438845075575400, .checksum_body = 98081761841810822994326224503485043631, .parent = 0, .client = 0, .context = 0, .request = 0, .cluster = 0, .epoch = 0, .view = 33, .op = 213360000000, .commit = 0, .timestamp = 0, .size = 128, .replica = 2, .command = Command.ping, .operation = Operation.reserved, .version = 0 }
[debug] (network): send_message: Process{ .replica = 2 } &gt; Process{ .replica = 0 }: Command.ping
[debug] (replica): 2: sending ping to replica 1: Header{ .checksum = 153987012347772732798740438845075575400, .checksum_body = 98081761841810822994326224503485043631, .parent = 0, .client = 0, .context = 0, .request = 0, .cluster = 0, .epoch = 0, .view = 33, .op = 213360000000, .commit = 0, .timestamp = 0, .size = 128, .replica = 2, .command = Command.ping, .operation = Operation.reserved, .version = 0 }
[debug] (network): send_message: Process{ .replica = 2 } &gt; Process{ .replica = 1 }: Command.ping
[debug] (vsr): 2: repair_timeout fired
[debug] (vsr): 2: repair_timeout reset
[debug] (replica): 2: repair_prepare: op=17 checksum=149727808271441180061851336637491398996 (already writing)
[debug] (replica): 2: repair_prepare: op=16 checksum=78014756875457191332436470636089908915 (committed, dirty)
[debug] (replica): 2: sending request_prepare to replica 1: Header{ .checksum = 99658369549599612680296458974308543284, .checksum_body = 98081761841810822994326224503485043631, .parent = 0, .client = 0, .context = 78014756875457191332436470636089908915, .request = 0, .cluster = 0, .epoch = 0, .view = 33, .op = 16, .commit = 0, .timestamp = 1, .size = 128, .replica = 2, .command = Command.request_prepare, .operation = Operation.reserved, .version = 0 }
[debug] (network): send_message: Process{ .replica = 2 } &gt; Process{ .replica = 1 }: Command.request_prepare
[debug] (packet_simulator): replayed packet from=0 to=2
[debug] (network): deliver_message: Process{ .replica = 0 } &gt; Process{ .replica = 2 }: Command.ping
[debug] (replica): 2: on_message: view=33 status=Status.normal Header{ .checksum = 331381902754807014041750051262112387157, .checksum_body = 98081761841810822994326224503485043631, .parent = 0, .client = 0, .context = 0, .request = 0, .cluster = 0, .epoch = 0, .view = 33, .op = 213350000000, .commit = 0, .timestamp = 0, .size = 128, .replica = 0, .command = Command.ping, .operation = Operation.reserved, .version = 0 }
[debug] (replica): 2: sending pong to replica 0: Header{ .checksum = 267061128552841115517827031854522065704, .checksum_body = 98081761841810822994326224503485043631, .parent = 0, .client = 0, .context = 0, .request = 0, .cluster = 0, .epoch = 0, .view = 33, .op = 213350000000, .commit = 0, .timestamp = 213360000000, .size = 128, .replica = 2, .command = Command.pong, .operation = Operation.reserved, .version = 0 }
[debug] (network): send_message: Process{ .replica = 2 } &gt; Process{ .replica = 0 }: Command.pong
[err] (packet_simulator): dropped packet (different partitions): from=1 to=0
[err] (packet_simulator): dropped packet (different partitions): from=2 to=1
[err] (packet_simulator): dropped packet (different partitions): from=0 to=1
[debug] (packet_simulator): reverse path clogged
[debug] (packet_simulator): Path path.source=4 path.target=3 clogged for ticks=76
[debug] (packet_simulator): replayed packet from=0 to=2
[debug] (network): deliver_message: Process{ .replica = 0 } &gt; Process{ .replica = 2 }: Command.ping
[debug] (replica): 2: on_message: view=33 status=Status.normal Header{ .checksum = 331381902754807014041750051262112387157, .checksum_body = 98081761841810822994326224503485043631, .parent = 0, .client = 0, .context = 0, .request = 0, .cluster = 0, .epoch = 0, .view = 33, .op = 213350000000, .commit = 0, .timestamp = 0, .size = 128, .replica = 0, .command = Command.ping, .operation = Operation.reserved, .version = 0 }
[debug] (replica): 2: sending pong to replica 0: Header{ .checksum = 264015090071536491558522598688121977794, .checksum_body = 98081761841810822994326224503485043631, .parent = 0, .client = 0, .context = 0, .request = 0, .cluster = 0, .epoch = 0, .view = 33, .op = 213350000000, .commit = 0, .timestamp = 213390000000, .size = 128, .replica = 2, .command = Command.pong, .operation = Operation.reserved, .version = 0 }
[debug] (network): send_message: Process{ .replica = 2 } &gt; Process{ .replica = 0 }: Command.pong
[err] (packet_simulator): dropped packet (different partitions): from=2 to=1
[debug] (journal): 2: write_sectors: offset=0 len=4096 unlocked
[debug] (journal): 2: write_header: op=17 sectors[0..4096]
[debug] (journal): 2: write_sectors: offset=0 len=4096 locked
[debug] (journal): 2: write: view=31 op=19 len=128: 282971753754517860133480224027787062378 entry changed while writing headers
[debug] (packet_simulator): reverse path clogged
[debug] (packet_simulator): Path path.source=5 path.target=1 clogged for ticks=98
[err] (packet_simulator): dropped packet from=0 to=2.
[debug] (packet_simulator): reverse path clogged
[debug] (packet_simulator): Path path.source=4 path.target=0 clogged for ticks=165
[debug] (packet_simulator): reverse path clogged
[debug] (packet_simulator): Path path.source=5 path.target=1 clogged for ticks=115
[debug] (journal): 2: write_sectors: offset=0 len=4096 unlocked
[debug] (journal): 2: write: view=30 op=17 len=1048576: 149727808271441180061851336637491398996 complete, marking clean
[debug] (replica): 2: send_prepare_ok: op=17 checksum=149727808271441180061851336637491398996
[debug] (replica): 2: sending prepare_ok to replica 0: Header{ .checksum = 217678308463251147144023215365490091882, .checksum_body = 98081761841810822994326224503485043631, .parent = 78014756875457191332436470636089908915, .client = 216211608991384047144981724848319393637, .context = 149727808271441180061851336637491398996, .request = 6, .cluster = 0, .epoch = 0, .view = 33, .op = 17, .commit = 14, .timestamp = 199580000000, .size = 128, .replica = 2, .command = Command.prepare_ok, .operation = Operation(3), .version = 0 }
[debug] (network): send_message: Process{ .replica = 2 } &gt; Process{ .replica = 0 }: Command.prepare_ok
[debug] (vsr): 2: repair_timeout reset
[debug] (replica): 2: repair_prepare: op=16 checksum=78014756875457191332436470636089908915 (committed, dirty)
[debug] (replica): 2: sending request_prepare to replica 0: Header{ .checksum = 99658369549599612680296458974308543284, .checksum_body = 98081761841810822994326224503485043631, .parent = 0, .client = 0, .context = 78014756875457191332436470636089908915, .request = 0, .cluster = 0, .epoch = 0, .view = 33, .op = 16, .commit = 0, .timestamp = 1, .size = 128, .replica = 2, .command = Command.request_prepare, .operation = Operation.reserved, .version = 0 }
[debug] (network): send_message: Process{ .replica = 2 } &gt; Process{ .replica = 0 }: Command.request_prepare
[err] (packet_simulator): unpartitioned network: partition={ false, false, false }
[debug] (packet_simulator): reverse path clogged
[debug] (packet_simulator): Path path.source=2 path.target=0 clogged for ticks=70
[debug] (packet_simulator): reverse path clogged
[debug] (packet_simulator): Path path.source=2 path.target=5 clogged for ticks=148
[debug] (vsr): 1: repair_timeout fired
[debug] (vsr): 1: repair_timeout reset
[debug] (packet_simulator): reverse path clogged
[debug] (packet_simulator): Path path.source=2 path.target=3 clogged for ticks=110
[debug] (packet_simulator): reverse path clogged
[debug] (packet_simulator): Path path.source=1 path.target=4 clogged for ticks=221
[debug] (packet_simulator): reverse path clogged
[debug] (packet_simulator): Path path.source=5 path.target=1 clogged for ticks=349
[err] (packet_simulator): dropped packet from=5 to=0.
[debug] (packet_simulator): replayed packet from=5 to=0
[debug] (network): deliver_message: Process{ .client = 223766198791537235907751426329910979727 } &gt; Process{ .replica = 0 }: Command.ping
[debug] (replica): 0: on_message: view=33 status=Status.normal Header{ .checksum = 244141079138543730002306435492686385921, .checksum_body = 98081761841810822994326224503485043631, .parent = 0, .client = 223766198791537235907751426329910979727, .context = 0, .request = 0, .cluster = 0, .epoch = 0, .view = 0, .op = 0, .commit = 0, .timestamp = 0, .size = 128, .replica = 0, .command = Command.ping, .operation = Operation.reserved, .version = 0 }
[debug] (network): send_message: Process{ .replica = 0 } &gt; Process{ .client = 223766198791537235907751426329910979727 }: Command.pong
[err] (packet_simulator): dropped packet from=5 to=0.
[debug] (packet_simulator): delivering packet from=5 to=0
[debug] (network): deliver_message: Process{ .client = 223766198791537235907751426329910979727 } &gt; Process{ .replica = 0 }: Command.ping
[debug] (replica): 0: on_message: view=33 status=Status.normal Header{ .checksum = 244141079138543730002306435492686385921, .checksum_body = 98081761841810822994326224503485043631, .parent = 0, .client = 223766198791537235907751426329910979727, .context = 0, .request = 0, .cluster = 0, .epoch = 0, .view = 0, .op = 0, .commit = 0, .timestamp = 0, .size = 128, .replica = 0, .command = Command.ping, .operation = Operation.reserved, .version = 0 }
[debug] (network): send_message: Process{ .replica = 0 } &gt; Process{ .client = 223766198791537235907751426329910979727 }: Command.pong
[debug] (packet_simulator): reverse path clogged
[debug] (packet_simulator): Path path.source=4 path.target=4 clogged for ticks=8
[debug] (packet_simulator): replayed packet from=0 to=5
[debug] (network): deliver_message: Process{ .replica = 0 } &gt; Process{ .client = 223766198791537235907751426329910979727 }: Command.pong
[debug] (client): 223766198791537235907751426329910979727: on_message: Header{ .checksum = 46837701340878562154937920695254629092, .checksum_body = 98081761841810822994326224503485043631, .parent = 0, .client = 0, .context = 0, .request = 0, .cluster = 0, .epoch = 0, .view = 33, .op = 0, .commit = 0, .timestamp = 0, .size = 128, .replica = 0, .command = Command.pong, .operation = Operation.reserved, .version = 0 }
[debug] (client): 223766198791537235907751426329910979727: on_pong: newer view=31..33
[debug] (packet_simulator): delivering packet from=0 to=5
[debug] (network): deliver_message: Process{ .replica = 0 } &gt; Process{ .client = 223766198791537235907751426329910979727 }: Command.pong
[debug] (client): 223766198791537235907751426329910979727: on_message: Header{ .checksum = 46837701340878562154937920695254629092, .checksum_body = 98081761841810822994326224503485043631, .parent = 0, .client = 0, .context = 0, .request = 0, .cluster = 0, .epoch = 0, .view = 33, .op = 0, .commit = 0, .timestamp = 0, .size = 128, .replica = 0, .command = Command.pong, .operation = Operation.reserved, .version = 0 }
[err] (packet_simulator): dropped packet from=0 to=5.
[debug] (packet_simulator): reverse path clogged
[debug] (packet_simulator): Path path.source=4 path.target=5 clogged for ticks=177
[debug] (packet_simulator): reverse path clogged
[debug] (packet_simulator): Path path.source=4 path.target=3 clogged for ticks=82
[debug] (vsr): 223766198791537235907751426329910979727: request_timeout fired
[debug] (vsr): 223766198791537235907751426329910979727: request_timeout backing off
[debug] (vsr): 223766198791537235907751426329910979727: request_timeout after=110..101 (rtt=30 min=10 max=1000 attempts=4)
[debug] (client): 223766198791537235907751426329910979727: on_request_timeout: resending request=3 checksum=222300789647330553697086296996712842172
[debug] (client): 223766198791537235907751426329910979727: sending request to replica 1: Header{ .checksum = 222300789647330553697086296996712842172, .checksum_body = 333952290918115815430551620017559130487, .parent = 90529465241987729877863856904039902349, .client = 223766198791537235907751426329910979727, .context = 10, .request = 3, .cluster = 0, .epoch = 0, .view = 27, .op = 0, .commit = 0, .timestamp = 0, .size = 401179, .replica = 0, .command = Command.request, .operation = Operation(3), .version = 0 }
[debug] (network): send_message: Process{ .client = 223766198791537235907751426329910979727 } &gt; Process{ .replica = 1 }: Command.request
[debug] (packet_simulator): reverse path clogged
[debug] (packet_simulator): Path path.source=1 path.target=3 clogged for ticks=354
[debug] (vsr): 0: repair_timeout fired
[debug] (vsr): 0: repair_timeout reset
[debug] (packet_simulator): reverse path clogged
[debug] (packet_simulator): Path path.source=4 path.target=5 clogged for ticks=5
[debug] (packet_simulator): reverse path clogged
[debug] (packet_simulator): Path path.source=4 path.target=0 clogged for ticks=324
[debug] (packet_simulator): reverse path clogged
[debug] (packet_simulator): Path path.source=4 path.target=4 clogged for ticks=24
[debug] (vsr): 335511138666577538158140751966064872959: request_timeout fired
[debug] (vsr): 335511138666577538158140751966064872959: request_timeout backing off
[debug] (vsr): 335511138666577538158140751966064872959: request_timeout after=80..149 (rtt=30 min=10 max=1000 attempts=3)
[debug] (client): 335511138666577538158140751966064872959: on_request_timeout: resending request=7 checksum=103341896402299122564620713873323123980
[debug] (client): 335511138666577538158140751966064872959: sending request to replica 1: Header{ .checksum = 103341896402299122564620713873323123980, .checksum_body = 98081761841810822994326224503485043631, .parent = 295722455584224246722095867023767655631, .client = 335511138666577538158140751966064872959, .context = 1, .request = 7, .cluster = 0, .epoch = 0, .view = 31, .op = 0, .commit = 0, .timestamp = 0, .size = 128, .replica = 0, .command = Command.request, .operation = Operation(3), .version = 0 }
[debug] (network): send_message: Process{ .client = 335511138666577538158140751966064872959 } &gt; Process{ .replica = 1 }: Command.request
[debug] (packet_simulator): replayed packet from=3 to=1
[debug] (network): deliver_message: Process{ .client = 335511138666577538158140751966064872959 } &gt; Process{ .replica = 1 }: Command.request
[debug] (replica): 1: on_message: view=31 status=Status.normal Header{ .checksum = 103341896402299122564620713873323123980, .checksum_body = 98081761841810822994326224503485043631, .parent = 295722455584224246722095867023767655631, .client = 335511138666577538158140751966064872959, .context = 1, .request = 7, .cluster = 0, .epoch = 0, .view = 31, .op = 0, .commit = 0, .timestamp = 0, .size = 128, .replica = 0, .command = Command.request, .operation = Operation(3), .version = 0 }
[debug] (replica): 1: on_request: new request
[debug] (replica): 1: on_request: ignoring (already preparing)
[debug] (packet_simulator): reverse path clogged
[debug] (packet_simulator): Path path.source=0 path.target=0 clogged for ticks=600
[debug] (packet_simulator): delivering packet from=3 to=1
[debug] (network): deliver_message: Process{ .client = 335511138666577538158140751966064872959 } &gt; Process{ .replica = 1 }: Command.request
[debug] (replica): 1: on_message: view=31 status=Status.normal Header{ .checksum = 103341896402299122564620713873323123980, .checksum_body = 98081761841810822994326224503485043631, .parent = 295722455584224246722095867023767655631, .client = 335511138666577538158140751966064872959, .context = 1, .request = 7, .cluster = 0, .epoch = 0, .view = 31, .op = 0, .commit = 0, .timestamp = 0, .size = 128, .replica = 0, .command = Command.request, .operation = Operation(3), .version = 0 }
[debug] (replica): 1: on_request: new request
[debug] (replica): 1: on_request: ignoring (already preparing)
[debug] (packet_simulator): reverse path clogged
[debug] (packet_simulator): Path path.source=2 path.target=4 clogged for ticks=195
[debug] (vsr): 2: repair_timeout fired
[debug] (vsr): 2: repair_timeout reset
[debug] (replica): 2: repair_prepare: op=16 checksum=78014756875457191332436470636089908915 (committed, dirty)
[debug] (replica): 2: sending request_prepare to replica 1: Header{ .checksum = 99658369549599612680296458974308543284, .checksum_body = 98081761841810822994326224503485043631, .parent = 0, .client = 0, .context = 78014756875457191332436470636089908915, .request = 0, .cluster = 0, .epoch = 0, .view = 33, .op = 16, .commit = 0, .timestamp = 1, .size = 128, .replica = 2, .command = Command.request_prepare, .operation = Operation.reserved, .version = 0 }
[debug] (network): send_message: Process{ .replica = 2 } &gt; Process{ .replica = 1 }: Command.request_prepare
[debug] (packet_simulator): replayed packet from=2 to=1
[debug] (network): deliver_message: Process{ .replica = 2 } &gt; Process{ .replica = 1 }: Command.request_prepare
[debug] (replica): 1: on_message: view=31 status=Status.normal Header{ .checksum = 99658369549599612680296458974308543284, .checksum_body = 98081761841810822994326224503485043631, .parent = 0, .client = 0, .context = 78014756875457191332436470636089908915, .request = 0, .cluster = 0, .epoch = 0, .view = 33, .op = 16, .commit = 0, .timestamp = 1, .size = 128, .replica = 2, .command = Command.request_prepare, .operation = Operation.reserved, .version = 0 }
[debug] (replica): 1: on_request_prepare: ignoring (newer view)
[debug] (packet_simulator): reverse path clogged
[debug] (packet_simulator): Path path.source=1 path.target=2 clogged for ticks=115
[debug] (packet_simulator): reverse path clogged
[debug] (packet_simulator): Path path.source=2 path.target=3 clogged for ticks=17
[debug] (vsr): 1: ping_timeout fired
[debug] (vsr): 1: ping_timeout reset
[debug] (replica): 1: sending ping to replica 0: Header{ .checksum = 53590873638045886105482685214968408197, .checksum_body = 98081761841810822994326224503485043631, .parent = 0, .client = 0, .context = 0, .request = 0, .cluster = 0, .epoch = 0, .view = 31, .op = 214120000000, .commit = 0, .timestamp = 0, .size = 128, .replica = 1, .command = Command.ping, .operation = Operation.reserved, .version = 0 }
[debug] (network): send_message: Process{ .replica = 1 } &gt; Process{ .replica = 0 }: Command.ping
[debug] (replica): 1: sending ping to replica 2: Header{ .checksum = 53590873638045886105482685214968408197, .checksum_body = 98081761841810822994326224503485043631, .parent = 0, .client = 0, .context = 0, .request = 0, .cluster = 0, .epoch = 0, .view = 31, .op = 214120000000, .commit = 0, .timestamp = 0, .size = 128, .replica = 1, .command = Command.ping, .operation = Operation.reserved, .version = 0 }
[debug] (network): send_message: Process{ .replica = 1 } &gt; Process{ .replica = 2 }: Command.ping
[debug] (vsr): 1: commit_timeout fired
[debug] (vsr): 1: commit_timeout reset
[debug] (replica): 1: sending commit to replica 0: Header{ .checksum = 299416124590731346664567120869949794602, .checksum_body = 98081761841810822994326224503485043631, .parent = 0, .client = 0, .context = 280919655732552742998137919384557100881, .request = 0, .cluster = 0, .epoch = 0, .view = 31, .op = 0, .commit = 16, .timestamp = 0, .size = 128, .replica = 1, .command = Command.commit, .operation = Operation.reserved, .version = 0 }
[debug] (network): send_message: Process{ .replica = 1 } &gt; Process{ .replica = 0 }: Command.commit
[debug] (replica): 1: sending commit to replica 2: Header{ .checksum = 299416124590731346664567120869949794602, .checksum_body = 98081761841810822994326224503485043631, .parent = 0, .client = 0, .context = 280919655732552742998137919384557100881, .request = 0, .cluster = 0, .epoch = 0, .view = 31, .op = 0, .commit = 16, .timestamp = 0, .size = 128, .replica = 1, .command = Command.commit, .operation = Operation.reserved, .version = 0 }
[debug] (network): send_message: Process{ .replica = 1 } &gt; Process{ .replica = 2 }: Command.commit
[debug] (vsr): 1: repair_timeout fired
[debug] (vsr): 1: repair_timeout reset
[debug] (packet_simulator): delivering packet from=1 to=0
[debug] (network): deliver_message: Process{ .replica = 1 } &gt; Process{ .replica = 0 }: Command.commit
[debug] (replica): 0: on_message: view=33 status=Status.normal Header{ .checksum = 299416124590731346664567120869949794602, .checksum_body = 98081761841810822994326224503485043631, .parent = 0, .client = 0, .context = 280919655732552742998137919384557100881, .request = 0, .cluster = 0, .epoch = 0, .view = 31, .op = 0, .commit = 16, .timestamp = 0, .size = 128, .replica = 1, .command = Command.commit, .operation = Operation.reserved, .version = 0 }
[debug] (replica): 0: on_commit: ignoring (older view)
[err] (packet_simulator): partitioned network: partition={ false, true, false }
[err] (packet_simulator): dropped packet (different partitions): from=1 to=0
[err] (packet_simulator): dropped packet (different partitions): from=2 to=1
[debug] (packet_simulator): reverse path clogged
[debug] (packet_simulator): Path path.source=0 path.target=5 clogged for ticks=28
[debug] (packet_simulator): reverse path clogged
[debug] (packet_simulator): Path path.source=2 path.target=5 clogged for ticks=583
[debug] (packet_simulator): reverse path clogged
[debug] (packet_simulator): Path path.source=5 path.target=1 clogged for ticks=8
[debug] (packet_simulator): replayed packet from=5 to=1
[debug] (network): deliver_message: Process{ .client = 223766198791537235907751426329910979727 } &gt; Process{ .replica = 1 }: Command.request
[debug] (replica): 1: on_message: view=31 status=Status.normal Header{ .checksum = 222300789647330553697086296996712842172, .checksum_body = 333952290918115815430551620017559130487, .parent = 90529465241987729877863856904039902349, .client = 223766198791537235907751426329910979727, .context = 10, .request = 3, .cluster = 0, .epoch = 0, .view = 27, .op = 0, .commit = 0, .timestamp = 0, .size = 401179, .replica = 0, .command = Command.request, .operation = Operation(3), .version = 0 }
[debug] (replica): 1: on_request: new request
[debug] (replica): 1: on_request: ignoring (already preparing)
[debug] (vsr): 1: prepare_timeout fired
[debug] (vsr): 1: prepare_timeout backing off
[debug] (vsr): 1: prepare_timeout after=95..202 (rtt=30 min=10 max=1000 attempts=5)
[debug] (replica): 1: on_prepare_timeout: waiting for replica 0
[debug] (replica): 1: on_prepare_timeout: waiting for replica 2
[debug] (replica): 1: on_prepare_timeout: replicating to replica 2
[debug] (replica): 1: sending prepare to replica 2: Header{ .checksum = 274640755804917375998870706212380760139, .checksum_body = 197688710245638009225329894310189579105, .parent = 280919655732552742998137919384557100881, .client = 216211608991384047144981724848319393637, .context = 164199344481104444325627298724669288032, .request = 6, .cluster = 0, .epoch = 0, .view = 31, .op = 17, .commit = 15, .timestamp = 210690000000, .size = 1048576, .replica = 1, .command = Command.prepare, .operation = Operation(3), .version = 0 }
[debug] (network): send_message: Process{ .replica = 1 } &gt; Process{ .replica = 2 }: Command.prepare
[debug] (packet_simulator): replayed packet from=5 to=1
[debug] (network): deliver_message: Process{ .client = 223766198791537235907751426329910979727 } &gt; Process{ .replica = 1 }: Command.request
[debug] (replica): 1: on_message: view=31 status=Status.normal Header{ .checksum = 222300789647330553697086296996712842172, .checksum_body = 333952290918115815430551620017559130487, .parent = 90529465241987729877863856904039902349, .client = 223766198791537235907751426329910979727, .context = 10, .request = 3, .cluster = 0, .epoch = 0, .view = 27, .op = 0, .commit = 0, .timestamp = 0, .size = 401179, .replica = 0, .command = Command.request, .operation = Operation(3), .version = 0 }
[debug] (replica): 1: on_request: new request
[debug] (replica): 1: on_request: ignoring (already preparing)
[debug] (packet_simulator): delivering packet from=2 to=0
[debug] (network): deliver_message: Process{ .replica = 2 } &gt; Process{ .replica = 0 }: Command.request_prepare
[debug] (replica): 0: on_message: view=33 status=Status.normal Header{ .checksum = 99658369549599612680296458974308543284, .checksum_body = 98081761841810822994326224503485043631, .parent = 0, .client = 0, .context = 78014756875457191332436470636089908915, .request = 0, .cluster = 0, .epoch = 0, .view = 33, .op = 16, .commit = 0, .timestamp = 1, .size = 128, .replica = 2, .command = Command.request_prepare, .operation = Operation.reserved, .version = 0 }
[debug] (replica): 0: on_request_prepare: op=16 checksum=78014756875457191332436470636089908915 reading
[debug] (journal): 0: read_sectors: offset=16793600 len=1048576
[debug] (packet_simulator): replayed packet from=2 to=0
[debug] (network): deliver_message: Process{ .replica = 2 } &gt; Process{ .replica = 0 }: Command.ping
[debug] (replica): 0: on_message: view=33 status=Status.normal Header{ .checksum = 153987012347772732798740438845075575400, .checksum_body = 98081761841810822994326224503485043631, .parent = 0, .client = 0, .context = 0, .request = 0, .cluster = 0, .epoch = 0, .view = 33, .op = 213360000000, .commit = 0, .timestamp = 0, .size = 128, .replica = 2, .command = Command.ping, .operation = Operation.reserved, .version = 0 }
[debug] (replica): 0: sending pong to replica 2: Header{ .checksum = 219414782378182082957913852496080670361, .checksum_body = 98081761841810822994326224503485043631, .parent = 0, .client = 0, .context = 0, .request = 0, .cluster = 0, .epoch = 0, .view = 33, .op = 213360000000, .commit = 0, .timestamp = 214290000000, .size = 128, .replica = 0, .command = Command.pong, .operation = Operation.reserved, .version = 0 }
[debug] (network): send_message: Process{ .replica = 0 } &gt; Process{ .replica = 2 }: Command.pong
[err] (packet_simulator): dropped packet from=2 to=0.
[debug] (packet_simulator): delivering packet from=2 to=0
[debug] (network): deliver_message: Process{ .replica = 2 } &gt; Process{ .replica = 0 }: Command.pong
[debug] (replica): 0: on_message: view=33 status=Status.normal Header{ .checksum = 264015090071536491558522598688121977794, .checksum_body = 98081761841810822994326224503485043631, .parent = 0, .client = 0, .context = 0, .request = 0, .cluster = 0, .epoch = 0, .view = 33, .op = 213350000000, .commit = 0, .timestamp = 213390000000, .size = 128, .replica = 2, .command = Command.pong, .operation = Operation.reserved, .version = 0 }
[debug] (clock): 0: learn: replica=2 m0=213350000000 t1=213390000000 m2=214290000000 t2=214290000000 one_way_delay=470000000 asymmetric_delay=0 clock_offset=-430000000
[debug] (packet_simulator): replayed packet from=2 to=0
[debug] (network): deliver_message: Process{ .replica = 2 } &gt; Process{ .replica = 0 }: Command.request_prepare
[debug] (replica): 0: on_message: view=33 status=Status.normal Header{ .checksum = 99658369549599612680296458974308543284, .checksum_body = 98081761841810822994326224503485043631, .parent = 0, .client = 0, .context = 78014756875457191332436470636089908915, .request = 0, .cluster = 0, .epoch = 0, .view = 33, .op = 16, .commit = 0, .timestamp = 1, .size = 128, .replica = 2, .command = Command.request_prepare, .operation = Operation.reserved, .version = 0 }
[debug] (replica): 0: on_request_prepare: op=16 checksum=78014756875457191332436470636089908915 reading
[debug] (journal): 0: read_sectors: offset=16793600 len=1048576
[debug] (packet_simulator): delivering packet from=2 to=0
[debug] (network): deliver_message: Process{ .replica = 2 } &gt; Process{ .replica = 0 }: Command.prepare_ok
[debug] (replica): 0: on_message: view=33 status=Status.normal Header{ .checksum = 217678308463251147144023215365490091882, .checksum_body = 98081761841810822994326224503485043631, .parent = 78014756875457191332436470636089908915, .client = 216211608991384047144981724848319393637, .context = 149727808271441180061851336637491398996, .request = 6, .cluster = 0, .epoch = 0, .view = 33, .op = 17, .commit = 14, .timestamp = 199580000000, .size = 128, .replica = 2, .command = Command.prepare_ok, .operation = Operation(3), .version = 0 }
[debug] (replica): 0: on_prepare_ok: 2 message(s)
[debug] (replica): 0: on_prepare_ok: quorum received, context=149727808271441180061851336637491398996
[debug] (replica): 0: commit_op: executing view=33 true op=17 checksum=149727808271441180061851336637491398996 (hash)
[debug] (state_machine): state=8e78424ef36512ccf6b12e2058d3b303 input=e6221169bd89d2ff6a65f67d7608c22 input.len=1048448 new state=6cc761c2ee8cc45e1490323082c58bc4
[info] (state_checker):      0014 8e78424ef36512ccf6b12e2058d3b303 &gt; 6cc761c2ee8cc45e1490323082c58bc4 0
[debug] (replica): 0: update_client_table_entry: client=216211608991384047144981724848319393637 session=3 request=6
[debug] (replica): 0: commit_op: replying to client: Header{ .checksum = 28290738994989111311488308948561595042, .checksum_body = 100004905418256206540951082609245590701, .parent = 164199344481104444325627298724669288032, .client = 216211608991384047144981724848319393637, .context = 0, .request = 6, .cluster = 0, .epoch = 0, .view = 30, .op = 17, .commit = 17, .timestamp = 0, .size = 144, .replica = 0, .command = Command.reply, .operation = Operation(3), .version = 0 }
[debug] (network): send_message: Process{ .replica = 0 } &gt; Process{ .client = 216211608991384047144981724848319393637 }: Command.reply
[debug] (vsr): 0: prepare_timeout stopped
[debug] (clock): 0: synchronized: truechimers=2/3 clock_offset=0ns..0ns accuracy=0ns
[debug] (packet_simulator): delivering packet from=2 to=0
[debug] (network): deliver_message: Process{ .replica = 2 } &gt; Process{ .replica = 0 }: Command.ping
[debug] (replica): 0: on_message: view=33 status=Status.normal Header{ .checksum = 153987012347772732798740438845075575400, .checksum_body = 98081761841810822994326224503485043631, .parent = 0, .client = 0, .context = 0, .request = 0, .cluster = 0, .epoch = 0, .view = 33, .op = 213360000000, .commit = 0, .timestamp = 0, .size = 128, .replica = 2, .command = Command.ping, .operation = Operation.reserved, .version = 0 }
[debug] (replica): 0: sending pong to replica 2: Header{ .checksum = 43621431138609778079986496330068652148, .checksum_body = 98081761841810822994326224503485043631, .parent = 0, .client = 0, .context = 0, .request = 0, .cluster = 0, .epoch = 0, .view = 33, .op = 213360000000, .commit = 0, .timestamp = 214300000000, .size = 128, .replica = 0, .command = Command.pong, .operation = Operation.reserved, .version = 0 }
[debug] (network): send_message: Process{ .replica = 0 } &gt; Process{ .replica = 2 }: Command.pong
[debug] (packet_simulator): delivering packet from=5 to=1
[debug] (network): deliver_message: Process{ .client = 223766198791537235907751426329910979727 } &gt; Process{ .replica = 1 }: Command.request
[debug] (replica): 1: on_message: view=31 status=Status.normal Header{ .checksum = 222300789647330553697086296996712842172, .checksum_body = 333952290918115815430551620017559130487, .parent = 90529465241987729877863856904039902349, .client = 223766198791537235907751426329910979727, .context = 10, .request = 3, .cluster = 0, .epoch = 0, .view = 27, .op = 0, .commit = 0, .timestamp = 0, .size = 401179, .replica = 0, .command = Command.request, .operation = Operation(3), .version = 0 }
[debug] (replica): 1: on_request: new request
[debug] (replica): 1: on_request: ignoring (already preparing)
[debug] (packet_simulator): reverse path clogged
[debug] (packet_simulator): Path path.source=4 path.target=5 clogged for ticks=207
[debug] (packet_simulator): replayed packet from=0 to=2
[debug] (network): deliver_message: Process{ .replica = 0 } &gt; Process{ .replica = 2 }: Command.pong
[debug] (replica): 2: on_message: view=33 status=Status.normal Header{ .checksum = 219414782378182082957913852496080670361, .checksum_body = 98081761841810822994326224503485043631, .parent = 0, .client = 0, .context = 0, .request = 0, .cluster = 0, .epoch = 0, .view = 33, .op = 213360000000, .commit = 0, .timestamp = 214290000000, .size = 128, .replica = 0, .command = Command.pong, .operation = Operation.reserved, .version = 0 }
[debug] (clock): 2: learn: replica=0 m0=213360000000 t1=214290000000 m2=214310000000 t2=214310000000 one_way_delay=475000000 asymmetric_delay=0 clock_offset=455000000
[debug] (packet_simulator): replayed packet from=0 to=2
[debug] (network): deliver_message: Process{ .replica = 0 } &gt; Process{ .replica = 2 }: Command.pong
[debug] (replica): 2: on_message: view=33 status=Status.normal Header{ .checksum = 43621431138609778079986496330068652148, .checksum_body = 98081761841810822994326224503485043631, .parent = 0, .client = 0, .context = 0, .request = 0, .cluster = 0, .epoch = 0, .view = 33, .op = 213360000000, .commit = 0, .timestamp = 214300000000, .size = 128, .replica = 0, .command = Command.pong, .operation = Operation.reserved, .version = 0 }
[debug] (clock): 2: learn: replica=0 m0=213360000000 t1=214300000000 m2=214310000000 t2=214310000000 one_way_delay=475000000 asymmetric_delay=0 clock_offset=465000000
[debug] (packet_simulator): replayed packet from=0 to=4
[debug] (network): deliver_message: Process{ .replica = 0 } &gt; Process{ .client = 216211608991384047144981724848319393637 }: Command.reply
[debug] (client): 216211608991384047144981724848319393637: on_message: Header{ .checksum = 28290738994989111311488308948561595042, .checksum_body = 100004905418256206540951082609245590701, .parent = 164199344481104444325627298724669288032, .client = 216211608991384047144981724848319393637, .context = 0, .request = 6, .cluster = 0, .epoch = 0, .view = 30, .op = 17, .commit = 17, .timestamp = 0, .size = 144, .replica = 0, .command = Command.reply, .operation = Operation(3), .version = 0 }
[debug] (client): 216211608991384047144981724848319393637: on_reply: user_data=0 request=6 size=144 hash
[debug] (client): 216211608991384047144981724848319393637: on_reply: newer view=27..30
[debug] (vsr): 216211608991384047144981724848319393637: request_timeout stopped
[debug] (client): 216211608991384047144981724848319393637: send_request_for_the_first_time: request=7 checksum=198127038382632819754321997938204325614
[debug] (vsr): 216211608991384047144981724848319393637: request_timeout started
[debug] (client): 216211608991384047144981724848319393637: sending request to replica 0: Header{ .checksum = 198127038382632819754321997938204325614, .checksum_body = 98081761841810822994326224503485043631, .parent = 28290738994989111311488308948561595042, .client = 216211608991384047144981724848319393637, .context = 3, .request = 7, .cluster = 0, .epoch = 0, .view = 30, .op = 0, .commit = 0, .timestamp = 0, .size = 128, .replica = 0, .command = Command.request, .operation = Operation(3), .version = 0 }
[debug] (network): send_message: Process{ .client = 216211608991384047144981724848319393637 } &gt; Process{ .replica = 0 }: Command.request
[debug] (clock): 2: synchronized: truechimers=2/3 clock_offset=0ns..0ns accuracy=0ns
[debug] (packet_simulator): replayed packet from=0 to=2
[debug] (network): deliver_message: Process{ .replica = 0 } &gt; Process{ .replica = 2 }: Command.pong
[debug] (replica): 2: on_message: view=33 status=Status.normal Header{ .checksum = 219414782378182082957913852496080670361, .checksum_body = 98081761841810822994326224503485043631, .parent = 0, .client = 0, .context = 0, .request = 0, .cluster = 0, .epoch = 0, .view = 33, .op = 213360000000, .commit = 0, .timestamp = 214290000000, .size = 128, .replica = 0, .command = Command.pong, .operation = Operation.reserved, .version = 0 }
[warn] (clock): 2: learn: m0=213360000000 &lt; window.monotonic=214320000000
[debug] (packet_simulator): delivering packet from=0 to=2
[debug] (network): deliver_message: Process{ .replica = 0 } &gt; Process{ .replica = 2 }: Command.pong
[debug] (replica): 2: on_message: view=33 status=Status.normal Header{ .checksum = 43621431138609778079986496330068652148, .checksum_body = 98081761841810822994326224503485043631, .parent = 0, .client = 0, .context = 0, .request = 0, .cluster = 0, .epoch = 0, .view = 33, .op = 213360000000, .commit = 0, .timestamp = 214300000000, .size = 128, .replica = 0, .command = Command.pong, .operation = Operation.reserved, .version = 0 }
[warn] (clock): 2: learn: m0=213360000000 &lt; window.monotonic=214320000000
[debug] (replica): 0: on_request_prepare_read: op=16 checksum=78014756875457191332436470636089908915 sending to replica=2
[debug] (replica): 0: sending prepare to replica 2: Header{ .checksum = 78014756875457191332436470636089908915, .checksum_body = 86347058295434097461203223295693055515, .parent = 28144421776703432668745419611282612780, .client = 335511138666577538158140751966064872959, .context = 75417735266591548424521437204787244953, .request = 6, .cluster = 0, .epoch = 0, .view = 30, .op = 16, .commit = 14, .timestamp = 199030000000, .size = 970676, .replica = 0, .command = Command.prepare, .operation = Operation(3), .version = 0 }
[debug] (network): send_message: Process{ .replica = 0 } &gt; Process{ .replica = 2 }: Command.prepare
[debug] (replica): 0: on_request_prepare_read: op=16 checksum=78014756875457191332436470636089908915 sending to replica=2
[debug] (replica): 0: sending prepare to replica 2: Header{ .checksum = 78014756875457191332436470636089908915, .checksum_body = 86347058295434097461203223295693055515, .parent = 28144421776703432668745419611282612780, .client = 335511138666577538158140751966064872959, .context = 75417735266591548424521437204787244953, .request = 6, .cluster = 0, .epoch = 0, .view = 30, .op = 16, .commit = 14, .timestamp = 199030000000, .size = 970676, .replica = 0, .command = Command.prepare, .operation = Operation(3), .version = 0 }
[debug] (network): send_message: Process{ .replica = 0 } &gt; Process{ .replica = 2 }: Command.prepare
[err] (packet_simulator): dropped packet from=0 to=2.
[debug] (packet_simulator): delivering packet from=0 to=4
[debug] (network): deliver_message: Process{ .replica = 0 } &gt; Process{ .client = 216211608991384047144981724848319393637 }: Command.reply
[debug] (client): 216211608991384047144981724848319393637: on_message: Header{ .checksum = 28290738994989111311488308948561595042, .checksum_body = 100004905418256206540951082609245590701, .parent = 164199344481104444325627298724669288032, .client = 216211608991384047144981724848319393637, .context = 0, .request = 6, .cluster = 0, .epoch = 0, .view = 30, .op = 17, .commit = 17, .timestamp = 0, .size = 144, .replica = 0, .command = Command.reply, .operation = Operation(3), .version = 0 }
[debug] (client): 216211608991384047144981724848319393637: on_reply: ignoring (request 6 &lt; 7)
[debug] (vsr): 0: ping_timeout fired
[debug] (vsr): 0: ping_timeout reset
[debug] (replica): 0: sending ping to replica 1: Header{ .checksum = 168999898550818333300051828657014230421, .checksum_body = 98081761841810822994326224503485043631, .parent = 0, .client = 0, .context = 0, .request = 0, .cluster = 0, .epoch = 0, .view = 33, .op = 214350000000, .commit = 0, .timestamp = 0, .size = 128, .replica = 0, .command = Command.ping, .operation = Operation.reserved, .version = 0 }
[debug] (network): send_message: Process{ .replica = 0 } &gt; Process{ .replica = 1 }: Command.ping
[debug] (replica): 0: sending ping to replica 2: Header{ .checksum = 168999898550818333300051828657014230421, .checksum_body = 98081761841810822994326224503485043631, .parent = 0, .client = 0, .context = 0, .request = 0, .cluster = 0, .epoch = 0, .view = 33, .op = 214350000000, .commit = 0, .timestamp = 0, .size = 128, .replica = 0, .command = Command.ping, .operation = Operation.reserved, .version = 0 }
[debug] (network): send_message: Process{ .replica = 0 } &gt; Process{ .replica = 2 }: Command.ping
[debug] (vsr): 0: commit_timeout fired
[debug] (vsr): 0: commit_timeout reset
[debug] (replica): 0: sending commit to replica 1: Header{ .checksum = 197267605159598609004125922991787151750, .checksum_body = 98081761841810822994326224503485043631, .parent = 0, .client = 0, .context = 149727808271441180061851336637491398996, .request = 0, .cluster = 0, .epoch = 0, .view = 33, .op = 0, .commit = 17, .timestamp = 0, .size = 128, .replica = 0, .command = Command.commit, .operation = Operation.reserved, .version = 0 }
[debug] (network): send_message: Process{ .replica = 0 } &gt; Process{ .replica = 1 }: Command.commit
[debug] (replica): 0: sending commit to replica 2: Header{ .checksum = 197267605159598609004125922991787151750, .checksum_body = 98081761841810822994326224503485043631, .parent = 0, .client = 0, .context = 149727808271441180061851336637491398996, .request = 0, .cluster = 0, .epoch = 0, .view = 33, .op = 0, .commit = 17, .timestamp = 0, .size = 128, .replica = 0, .command = Command.commit, .operation = Operation.reserved, .version = 0 }
[debug] (network): send_message: Process{ .replica = 0 } &gt; Process{ .replica = 2 }: Command.commit
[debug] (vsr): 0: repair_timeout fired
[debug] (vsr): 0: repair_timeout reset
[debug] (packet_simulator): delivering packet from=0 to=2
[debug] (network): deliver_message: Process{ .replica = 0 } &gt; Process{ .replica = 2 }: Command.prepare
[debug] (replica): 2: on_message: view=33 status=Status.normal Header{ .checksum = 78014756875457191332436470636089908915, .checksum_body = 86347058295434097461203223295693055515, .parent = 28144421776703432668745419611282612780, .client = 335511138666577538158140751966064872959, .context = 75417735266591548424521437204787244953, .request = 6, .cluster = 0, .epoch = 0, .view = 30, .op = 16, .commit = 14, .timestamp = 199030000000, .size = 970676, .replica = 0, .command = Command.prepare, .operation = Operation(3), .version = 0 }
[debug] (replica): 2: on_prepare: ignoring (repair)
[debug] (replica): 2: repair_header: op=16 exists, checksum dirty
[debug] (journal): 2: set_header_as_dirty: op=16 checksum=78014756875457191332436470636089908915
[debug] (replica): 2: on_repair: repairing journal
[debug] (journal): 2: write: view=30 op=16 len=970676: 78014756875457191332436470636089908915 starting
[debug] (journal): 2: write_sectors: offset=16793600 len=970752 locked
[debug] (packet_simulator): replayed packet from=0 to=2
[debug] (network): deliver_message: Process{ .replica = 0 } &gt; Process{ .replica = 2 }: Command.ping
[debug] (replica): 2: on_message: view=33 status=Status.normal Header{ .checksum = 168999898550818333300051828657014230421, .checksum_body = 98081761841810822994326224503485043631, .parent = 0, .client = 0, .context = 0, .request = 0, .cluster = 0, .epoch = 0, .view = 33, .op = 214350000000, .commit = 0, .timestamp = 0, .size = 128, .replica = 0, .command = Command.ping, .operation = Operation.reserved, .version = 0 }
[debug] (replica): 2: sending pong to replica 0: Header{ .checksum = 306820467990549653019747882516583816764, .checksum_body = 98081761841810822994326224503485043631, .parent = 0, .client = 0, .context = 0, .request = 0, .cluster = 0, .epoch = 0, .view = 33, .op = 214350000000, .commit = 0, .timestamp = 214350000000, .size = 128, .replica = 2, .command = Command.pong, .operation = Operation.reserved, .version = 0 }
[debug] (network): send_message: Process{ .replica = 2 } &gt; Process{ .replica = 0 }: Command.pong
[debug] (packet_simulator): reverse path clogged
[debug] (packet_simulator): Path path.source=5 path.target=1 clogged for ticks=132
[debug] (packet_simulator): replayed packet from=2 to=0
[debug] (network): deliver_message: Process{ .replica = 2 } &gt; Process{ .replica = 0 }: Command.request_prepare
[debug] (replica): 0: on_message: view=33 status=Status.normal Header{ .checksum = 99658369549599612680296458974308543284, .checksum_body = 98081761841810822994326224503485043631, .parent = 0, .client = 0, .context = 78014756875457191332436470636089908915, .request = 0, .cluster = 0, .epoch = 0, .view = 33, .op = 16, .commit = 0, .timestamp = 1, .size = 128, .replica = 2, .command = Command.request_prepare, .operation = Operation.reserved, .version = 0 }
[debug] (replica): 0: on_request_prepare: op=16 checksum=78014756875457191332436470636089908915 reading
[debug] (journal): 0: read_sectors: offset=16793600 len=1048576
[debug] (vsr): 2: ping_timeout fired
[debug] (vsr): 2: ping_timeout reset
[debug] (replica): 2: sending ping to replica 0: Header{ .checksum = 92948431762315479974112755386055213004, .checksum_body = 98081761841810822994326224503485043631, .parent = 0, .client = 0, .context = 0, .request = 0, .cluster = 0, .epoch = 0, .view = 33, .op = 214360000000, .commit = 0, .timestamp = 0, .size = 128, .replica = 2, .command = Command.ping, .operation = Operation.reserved, .version = 0 }
[debug] (network): send_message: Process{ .replica = 2 } &gt; Process{ .replica = 0 }: Command.ping
[debug] (replica): 2: sending ping to replica 1: Header{ .checksum = 92948431762315479974112755386055213004, .checksum_body = 98081761841810822994326224503485043631, .parent = 0, .client = 0, .context = 0, .request = 0, .cluster = 0, .epoch = 0, .view = 33, .op = 214360000000, .commit = 0, .timestamp = 0, .size = 128, .replica = 2, .command = Command.ping, .operation = Operation.reserved, .version = 0 }
[debug] (network): send_message: Process{ .replica = 2 } &gt; Process{ .replica = 1 }: Command.ping
[err] (packet_simulator): dropped packet (different partitions): from=0 to=1
[debug] (packet_simulator): delivering packet from=0 to=2
[debug] (network): deliver_message: Process{ .replica = 0 } &gt; Process{ .replica = 2 }: Command.commit
[debug] (replica): 2: on_message: view=33 status=Status.normal Header{ .checksum = 197267605159598609004125922991787151750, .checksum_body = 98081761841810822994326224503485043631, .parent = 0, .client = 0, .context = 149727808271441180061851336637491398996, .request = 0, .cluster = 0, .epoch = 0, .view = 33, .op = 0, .commit = 17, .timestamp = 0, .size = 128, .replica = 0, .command = Command.commit, .operation = Operation.reserved, .version = 0 }
[debug] (replica): 2: on_commit: checksum verified
[debug] (vsr): 2: normal_status_timeout reset
[debug] (replica): 2: commit_ops: advancing commit_max=16..17
[debug] (journal): 2: read_sectors: offset=17842176 len=1048576
[debug] (packet_simulator): replayed packet from=0 to=2
[debug] (network): deliver_message: Process{ .replica = 0 } &gt; Process{ .replica = 2 }: Command.pong
[debug] (replica): 2: on_message: view=33 status=Status.normal Header{ .checksum = 219414782378182082957913852496080670361, .checksum_body = 98081761841810822994326224503485043631, .parent = 0, .client = 0, .context = 0, .request = 0, .cluster = 0, .epoch = 0, .view = 33, .op = 213360000000, .commit = 0, .timestamp = 214290000000, .size = 128, .replica = 0, .command = Command.pong, .operation = Operation.reserved, .version = 0 }
[warn] (clock): 2: learn: m0=213360000000 &lt; window.monotonic=214320000000
[debug] (packet_simulator): delivering packet from=2 to=0
[debug] (network): deliver_message: Process{ .replica = 2 } &gt; Process{ .replica = 0 }: Command.request_prepare
[debug] (replica): 0: on_message: view=33 status=Status.normal Header{ .checksum = 99658369549599612680296458974308543284, .checksum_body = 98081761841810822994326224503485043631, .parent = 0, .client = 0, .context = 78014756875457191332436470636089908915, .request = 0, .cluster = 0, .epoch = 0, .view = 33, .op = 16, .commit = 0, .timestamp = 1, .size = 128, .replica = 2, .command = Command.request_prepare, .operation = Operation.reserved, .version = 0 }
[debug] (replica): 0: on_request_prepare: op=16 checksum=78014756875457191332436470636089908915 reading
[debug] (journal): 0: read_sectors: offset=16793600 len=1048576
[debug] (replica): 0: on_request_prepare_read: op=16 checksum=78014756875457191332436470636089908915 sending to replica=2
[debug] (replica): 0: sending prepare to replica 2: Header{ .checksum = 78014756875457191332436470636089908915, .checksum_body = 86347058295434097461203223295693055515, .parent = 28144421776703432668745419611282612780, .client = 335511138666577538158140751966064872959, .context = 75417735266591548424521437204787244953, .request = 6, .cluster = 0, .epoch = 0, .view = 30, .op = 16, .commit = 14, .timestamp = 199030000000, .size = 970676, .replica = 0, .command = Command.prepare, .operation = Operation(3), .version = 0 }
[debug] (network): send_message: Process{ .replica = 0 } &gt; Process{ .replica = 2 }: Command.prepare
[debug] (replica): 0: on_request_prepare_read: op=16 checksum=78014756875457191332436470636089908915 sending to replica=2
[debug] (replica): 0: sending prepare to replica 2: Header{ .checksum = 78014756875457191332436470636089908915, .checksum_body = 86347058295434097461203223295693055515, .parent = 28144421776703432668745419611282612780, .client = 335511138666577538158140751966064872959, .context = 75417735266591548424521437204787244953, .request = 6, .cluster = 0, .epoch = 0, .view = 30, .op = 16, .commit = 14, .timestamp = 199030000000, .size = 970676, .replica = 0, .command = Command.prepare, .operation = Operation(3), .version = 0 }
[debug] (network): send_message: Process{ .replica = 0 } &gt; Process{ .replica = 2 }: Command.prepare
[debug] (packet_simulator): delivering packet from=0 to=2
[debug] (network): deliver_message: Process{ .replica = 0 } &gt; Process{ .replica = 2 }: Command.pong
[debug] (replica): 2: on_message: view=33 status=Status.normal Header{ .checksum = 219414782378182082957913852496080670361, .checksum_body = 98081761841810822994326224503485043631, .parent = 0, .client = 0, .context = 0, .request = 0, .cluster = 0, .epoch = 0, .view = 33, .op = 213360000000, .commit = 0, .timestamp = 214290000000, .size = 128, .replica = 0, .command = Command.pong, .operation = Operation.reserved, .version = 0 }
[warn] (clock): 2: learn: m0=213360000000 &lt; window.monotonic=214320000000
[debug] (packet_simulator): delivering packet from=2 to=0
[debug] (network): deliver_message: Process{ .replica = 2 } &gt; Process{ .replica = 0 }: Command.ping
[debug] (replica): 0: on_message: view=33 status=Status.normal Header{ .checksum = 92948431762315479974112755386055213004, .checksum_body = 98081761841810822994326224503485043631, .parent = 0, .client = 0, .context = 0, .request = 0, .cluster = 0, .epoch = 0, .view = 33, .op = 214360000000, .commit = 0, .timestamp = 0, .size = 128, .replica = 2, .command = Command.ping, .operation = Operation.reserved, .version = 0 }
[debug] (replica): 0: sending pong to replica 2: Header{ .checksum = 119909219287189517540346178431674511770, .checksum_body = 98081761841810822994326224503485043631, .parent = 0, .client = 0, .context = 0, .request = 0, .cluster = 0, .epoch = 0, .view = 33, .op = 214360000000, .commit = 0, .timestamp = 214380000000, .size = 128, .replica = 0, .command = Command.pong, .operation = Operation.reserved, .version = 0 }
[debug] (network): send_message: Process{ .replica = 0 } &gt; Process{ .replica = 2 }: Command.pong
[debug] (replica): 2: commit_op: executing view=33 false op=17 checksum=149727808271441180061851336637491398996 (hash)
```
</details>

### PR DESCRIPTION
**Pull request by jorangreef**
Fixes: #100

### CODE REVIEW

File: src/vsr/replica.zig [hunk 1]
```diff
@@ -2545,7 +2573,8 @@ pub fn Replica(
                 // We use the `timestamp` field to send this in addition to the current view number:
                 .timestamp = if (command == .do_view_change) self.view_normal else 0,
                 .op = self.op,
-                .commit = self.commit_max,
+                // See the comment in `on_do_view_change()` for why `commit_min` is crucial:
+                .commit = if (command == .do_view_change) self.commit_min else self.commit_max,
```
Comment (sentientwaffle) [inline src/vsr/replica.zig:2912]: `Header.commit`'s doc comment in `vsr.zig` should document this variation, e.g.:

```zig
    /// The commit number of the latest committed prepare. Committed ops are immutable.
    ///
    /// * A `do_view_change` sets this to `commit_min`.
    /// * A `start_view` sets this to `commit_max`.
    commit: u64 = 0,
```

File: src/vsr/replica.zig [hunk 2]
```diff
@@ -4297,7 +4326,14 @@ pub fn Replica(
...
             assert(message.header.op == self.op);
             assert(message.header.op == self.message_body_as_headers(message)[0].op);
-            assert(message.header.commit == self.commit_max);
+            // Each replica must advertise its own commit number, so that the primary can know which
+            // headers must be repaired in its own log. Otherwise, a gap in the log may prevent the
+            // primary from repairing its own log adequately, resulting in the log being forked if
+            // the primary also discards uncommitted operations.
+            // It is also safe not to use `commit_max` here because the new primary will assume that
+            // operations after the highest `commit_min` may yet have been committed before the old
+            // primary crashed. The new primary will use the NACK protocol to be sure of a discard.
```
Comment (sentientwaffle) [inline src/vsr/replica.zig]: Maybe `s/repaired in its own log/replaced in its own log`?
The headers we are talking about here aren't installed by `repair_header`, so "repair" might be a little misleading.

File: src/vsr/replica.zig [hunk 3]
```diff
@@ -1070,10 +1070,24 @@ pub fn Replica(
...
             // Now that we have the latest op in place, repair any other headers:
+            // We must trust headers that other replicas have committed, because repair_header() may
+            // not always be able to affect a repair if there is a gap in the hash chain.
             for (self.do_view_change_from_all_replicas) |received| {
                 if (received) |m| {
                     for (self.message_body_as_headers(m)) |*h| {
-                        _ = self.repair_header(h);
+                        if (h.op <= m.header.commit) {
+                            if (self.journal.header_with_op_and_checksum(h.op, h.checksum)) |_| {
+                                log.debug("{}: on_do_view_change: op={} committed on replica={}", .{
```
Comment (sentientwaffle) [inline src/vsr/replica.zig]: `op={} committed on replica={}` could describe the `else` branch also.

File: src/vsr/replica.zig [hunk 4]
```diff
@@ -1085,14 +1099,23 @@ pub fn Replica(
...
+            // 2. may not always reflect the timestamp of the latest prepared op, and
+            // 3. should be advanced before discarding the timestamps of any uncommitted headers.
+            if (self.state_machine.prepare_timestamp < latest.timestamp) {
+                self.state_machine.prepare_timestamp = latest.timestamp;
+            }
+
+            // TODO At present, discard_uncommitted_headers() does not consider interactions with
+            // the hash chain, i.e. that could lead to a hash chain swing, when it removes
+            // uncommitted ops. This is a correctness bug, where old ops may not be replaced in the
+            // view change. Rather, discard_uncommitted_headers() must fix up self.op after discard.
```
Comment (sentientwaffle) [inline src/vsr/replica.zig]: > that could lead to a hash chain swing

I'm not sure I understand what a "hash chain swing" is.

I understand that the new `self.journal.set_header_as_dirty` call above can replace an op, potentially breaking the hash chain between `commit_min` and `commit_min + 1` (for every `do_view_change`'s `commit_min`). So we may need to discard some ops that follow a `commit_min`.

But the comment implies the "swing" hasn't happened yet?

File: src/vsr/replica.zig [hunk 5]
```diff
@@ -1024,7 +1024,7 @@ pub fn Replica(
             });
 
             var v: ?u32 = null;
-            var k: ?u64 = null;
+            var k: ?u64 = null; // This represents `commit_min` according to each replica.
```
Comment (sentientwaffle) [inline src/vsr/replica.zig]: Should it be

```
// The highest `commit_min` from any replica.
```

Comment (jorangreef) [reply src/vsr/replica.zig]: Much better!

File: src/vsr/replica.zig (hunk 4 above)
Comment (jorangreef) [reply src/vsr/replica.zig]: A “hash chain swing” or “quorum swing” would be where a prepare is replaced with another, undermining the guarantee to the previous primary, meaning that the commit quorum “swings” to a new decision by another primary, forking the log if the prepare was in fact committed.

File: src/vsr/replica.zig (hunk 2 above)
Comment (jorangreef) [reply src/vsr/replica.zig]: I was thinking the same, wasn't quite happy with overloading the repair wording.

**Comment by jorangreef** [comment]
Fixes: #103

File: src/vsr/replica.zig [hunk 6]
```diff
@@ -2585,105 +2520,52 @@ pub fn Replica(
...
-            // ensures that the old primary could not possibly have committed the header.
             var op = self.op;
-            while (op > self.commit_max) : (op -= 1) {
+            while (op > op_committed) : (op -= 1) {
                 if (self.journal.header_with_op(op) != null) continue;
 
                 log.debug("{}: discard_uncommitted_headers: op={} gap", .{ self.replica, op });
 
-                var nacks: usize = 0;
-                for (self.do_view_change_from_all_replicas) |received, replica| {
```
Comment (sentientwaffle) [inline src/vsr/replica.zig:3000]: It's great that we can remove the nack protocol; this really simplifies the view change!

File: src/vsr/replica.zig [hunk 7]
```diff
@@ -4296,8 +4170,15 @@ pub fn Replica(
...
-            assert(message.header.op == self.message_body_as_headers(message)[0].op);
-            assert(message.header.commit == self.commit_max);
+            assert(message.header.op == message_body_as_headers(message)[0].op);
+            // Each replica must advertise its own commit number, so that the primary can know which
+            // headers must be replaced in its own log. Otherwise, a gap in the log may prevent the
+            // primary from repairing its own log adequately, resulting in the log being forked if
+            // the primary also discards uncommitted operations.
+            // It is also safe not to use `commit_max` here because the new primary will assume that
+            // operations after the highest `commit_min` may yet have been committed before the old
+            // primary crashed. The new primary will use the NACK protocol to be sure of a discard.
```
Comment (sentientwaffle) [inline src/vsr/replica.zig:4728]: > The new primary will use the NACK protocol to be sure of a discard.

Not anymore, right?

File: src/vsr/replica.zig [hunk 8]
```diff
@@ -4086,6 +3951,15 @@ pub fn Replica(
             }
         }
 
+        fn replace_header(self: *Self, header: *Header) void {
+            assert(header.command == .prepare);
```
Comment (sentientwaffle) [inline src/vsr/replica.zig:4471]: Could we assert that `header.op <= self.op` to verify that the caller has already updated the replica's `op`?

File: src/vsr/replica.zig [hunk 9]
```diff
@@ -4086,6 +3951,15 @@ pub fn Replica(
...
+
+            // Do not set an op as dirty if we already have it exactly because:
+            // 1. this would trigger a repair and delay the view change, or worse,
+            // 2. prevent repairs to another replica when we have the op.
+            if (!self.journal.has(header)) self.journal.set_header_as_dirty(header);
```
Comment (sentientwaffle) [inline src/vsr/replica.zig:4494]: Inside this condition, could we assert that if we are replacing another version of the same op, then `op > self.commit_min`?
Or maybe we could assert that `replace_header` is never called when `op ≤ commit_min`.

File: src/vsr/replica.zig [hunk 10]
```diff
@@ -4479,112 +4360,195 @@ pub fn Replica(
...
+            assert(self.commit_max <= self.op);
 
-            // Do not set the latest op as dirty if we already have it exactly:
-            // Otherwise, this would trigger a repair and delay the view change, or worse, it would
-            // prevent us from assisting another replica to recover when we do in fact have the op.
-            if (self.journal.has(latest)) {
-                log.debug("{}: {s}: latest op exists exactly", .{ self.replica, method });
-            } else {
-                self.journal.set_header_as_dirty(latest);
+            self.journal.remove_entries_from(self.op + 1);
```
Comment (sentientwaffle) [inline src/vsr/replica.zig]: Could this move up to immediately follow `self.op = op`? It's helpful when those are paired close together.

File: src/vsr/replica.zig [hunk 11]
```diff
@@ -4479,112 +4360,195 @@ pub fn Replica(
...
+            });
+        }
+
+        fn set_log_from_do_view_change_messages(self: *Self) void {
+            const view_normal_canonical = self.set_op_and_commit_max_from_do_view_change_messages();
+
+            // First, set all the canonical headers from the replica(s) with highest `view_normal`:
+            for (self.do_view_change_from_all_replicas) |received| {
+                if (received) |message| {
+                    var view_normal = @intCast(u32, message.header.timestamp);
```
Comment (sentientwaffle) [inline src/vsr/replica.zig]:
```suggestion
                    const view_normal = @intCast(u32, message.header.timestamp);
```

File: src/vsr/replica.zig [hunk 12]
```diff
@@ -4479,112 +4360,195 @@ pub fn Replica(
...
+                }
             }
 
-            assert(self.op == latest.op);
-            self.journal.remove_entries_from(self.op + 1);
-            assert(self.journal.header_with_op(self.op).?.checksum == latest.checksum);
+            // Now that the canonical headers are all in place, repair any other headers:
+            for (self.do_view_change_from_all_replicas) |received| {
+                if (received) |message| {
+                    var view_normal = @intCast(u32, message.header.timestamp);
```
Comment (sentientwaffle) [inline src/vsr/replica.zig]:
```suggestion
                    const view_normal = @intCast(u32, message.header.timestamp);
```

File: src/vsr/replica.zig [hunk 13]
```diff
@@ -4479,112 +4360,195 @@ pub fn Replica(
...
+        }
+
+        fn set_log_from_do_view_change_messages(self: *Self) void {
+            const view_normal_canonical = self.set_op_and_commit_max_from_do_view_change_messages();
+
+            // First, set all the canonical headers from the replica(s) with highest `view_normal`:
+            for (self.do_view_change_from_all_replicas) |received| {
+                if (received) |message| {
+                    var view_normal = @intCast(u32, message.header.timestamp);
+                    assert(view_normal < message.header.view);
```
Comment (sentientwaffle) [inline src/vsr/replica.zig:5053]: Can you explain this assertion to me? (Why can't they be equal?)

File: src/vsr/replica.zig [hunk 14]
```diff
@@ -4296,8 +4170,15 @@ pub fn Replica(
...
-            assert(message.header.commit == self.commit_max);
+            assert(message.header.op == message_body_as_headers(message)[0].op);
+            // Each replica must advertise its own commit number, so that the primary can know which
+            // headers must be replaced in its own log. Otherwise, a gap in the log may prevent the
+            // primary from repairing its own log adequately, resulting in the log being forked if
+            // the primary also discards uncommitted operations.
+            // It is also safe not to use `commit_max` here because the new primary will assume that
+            // operations after the highest `commit_min` may yet have been committed before the old
+            // primary crashed. The new primary will use the NACK protocol to be sure of a discard.
+            assert(message.header.commit == self.commit_min);
```
Comment (sentientwaffle) [inline src/vsr/replica.zig:4729]: Copy this assertion to `send_message_to_replica`'s `.do_view_change` section.

File: src/vsr/replica.zig [hunk 15]
```diff
@@ -4296,8 +4170,15 @@ pub fn Replica(
             assert(message.header.command == .do_view_change);
             assert(message.header.view == self.view);
             assert(message.header.op == self.op);
-            assert(message.header.op == self.message_body_as_headers(message)[0].op);
-            assert(message.header.commit == self.commit_max);
+            assert(message.header.op == message_body_as_headers(message)[0].op);
+            // Each replica must advertise its own commit number, so that the primary can know which
```
Comment (sentientwaffle) [inline src/vsr/replica.zig]:
```suggestion
            // Each replica must advertise its own commit number, so that the new primary can know which
```

File: src/vsr/replica.zig (hunk 6 above)
Comment (jorangreef) [reply src/vsr/replica.zig:3000]: Yes, much better! Just to clarify that we only remove it here. We still need it later, for discarding ops where there are no gaps.

However, using it here was never necessary for correctness, since the view change already guarantees the quorum intersection property, i.e. if any header might have committed, then it is guaranteed to survive into the view change. Therefore, if a header does not survive into a view change, if there is a gap across all replicas, then that op (and subsequent ops) could not possibly have committed. So the mere existence of a gap is enough to discard here.

`discard_uncommitted_headers()` is trying to discard headers for which there are gaps, where we are certain the op could not have been committed.

The NACK protocol has a slightly different purpose: discern for sure whether an op (for which there is no gap, where the header exists) is definitely uncommitted, and can therefore be discarded safely if it cannot be repaired.

File: src/vsr/replica.zig (hunk 7 above)
Comment (jorangreef) [reply src/vsr/replica.zig:4728]: This is still true, since we have two ways of discarding: for a clear gap, or otherwise via the NACK protocol. We just no longer use the NACK protocol where there is already a clear gap.

File: src/vsr/replica.zig (hunk 9 above)
Comment (jorangreef) [reply src/vsr/replica.zig:3960]: I've done the first version of the assertion, to assert that a committed op is not replaced, since most call sites trust the canonical headers for which we call `replace_header()`.

Comment (jorangreef) [reply src/vsr/replica.zig:4494]: I tried the first assert, and then realized that it might also be possible that our journal may simply be ahead and may not have the op any more? So an early return, following `repair_header()`, is what we have now in `replace_header()` if the header being replaced is already locally committed.

File: src/vsr/replica.zig (hunk 13 above)
Comment (jorangreef) [reply src/vsr/replica.zig:5053]: The view during which the replica's status was last normal, has to be before the view of the current view change, since we are advancing to a newer view. Is that a clear explanation?

I've added a comment to this effect.

Comment (sentientwaffle) [reply src/vsr/replica.zig:5053]: Gotcha, this message is always generated during a view change, which means it's view_normal is in the past. I was mixed up about the context.

File: src/vsr/replica.zig [hunk 16]
```diff
@@ -2520,6 +2520,49 @@ pub fn Replica(
...
+                self.replica,
+                remove_op_min,
+                self.op,
+            });
+
+            assert(remove_op_min <= self.op);
+            assert(remove_op_min > self.commit_min);
+            assert(remove_op_min + config.pipeline_max - 1 >= self.op);
+
+            // If any ops are canonical, then the replica's do_view_change message will repair them.
```
Comment (sentientwaffle) [inline src/vsr/replica.zig]: Could the replica update `self.op` here, just for consistency? (I know that it is going to be immediately rewritten by `set_op_and_commit_max`).

File: src/vsr/replica.zig [hunk 17]
```diff
@@ -2520,6 +2520,49 @@ pub fn Replica(
...
+                self.op - self.commit_min,
+                // The number of uncommitted ops cannot be more than the length of the pipeline.
+                // Do not reset any ops that we did not include in our do_view_change message.
+                config.pipeline_max,
+            );
+
+            assert(remove_op_count <= config.pipeline_max);
+            if (remove_op_count == 0) return;
+
+            const remove_op_min = self.op -| (remove_op_count - 1); // Inclusive.
```
Comment (sentientwaffle) [inline src/vsr/replica.zig]: Is the saturating subtraction necessary?

- When `remove_op_count = self.op - self.commit_min`, `self.op - (remove_op_count - 1) = (self.op - remove_op_count) + 1 = commit_min + 1`.
- When `remove_op_count = config.pipeline_max`, `config.pipeline_max < self.op - self.commit_min < self.op`.

File: src/vsr/replica.zig (hunk 16 above)
Comment (jorangreef) [reply src/vsr/replica.zig:2562]: Thanks, I realize also that we need another clamp to ensure we don't remove the `root` prepare. Otherwise `self.op = remove_op_min - 1` would underflow.

File: src/vsr/replica.zig (hunk 17 above)
Comment (jorangreef) [reply src/vsr/replica.zig]: Thanks, the saturating arithmetic is not necessary. This would also make a great comment to show the workings.

There's a small tweak I think.

- When `remove_op_count = config.pipeline_max`, `config.pipeline_max < self.op - self.commit_min` holds.
- However, from there `self.op - self.commit_min < self.op` does not always follow. For example, when `self.op=1` and `commit_min=0` then `self.op - self.commit_min == self.op`.

Comment (jorangreef) [reply src/vsr/replica.zig]: This is what I have:

```zig
const remove_op_count = std.math.min(
    // Do not reset any ops that we have already committed.
    self.op - self.commit_min,
    // The number of uncommitted ops cannot be more than the length of the pipeline.
    // Do not reset any ops that we did not include in our do_view_change message.
    config.pipeline_max,
);

assert(remove_op_count <= config.pipeline_max);
if (remove_op_count == 0) return;

// Saturating subtraction is not necessary below, because we take the min() above:
// * When `remove_op_count` = `self.op - self.commit_min`,
//      `self.op - self.commit_min <= self.op`.
// * When `remove_op_count = config.pipeline_max`,
//      `config.pipeline_max < self.op - self.commit_min <= self.op`.
const remove_op_min = self.op - remove_op_count + 1; // Add 1 as `op_min` is inclusive.
```

However, I think this is harder to get wrong, as it also binds intention with respect to the replica's DVC:

```zig
const message = self.do_view_change_from_all_replicas[self.replica].?;
assert(message.header.view == self.view);
assert(message.header.op == self.op);

var op_min: ?u64 = null;
var op_count: usize = config.pipeline_max;

for (message_body_as_headers(message)) |header| {
    assert(op_min == null or op_min.? > header.op);

    if (header.op <= self.commit_min) continue;
    if (op_count == 0) continue; // Assert all subsequent header.op's against op_min.

    op_min = header.op;
    op_count -= 1;
}
```

Now we have a stronger guarantee that any header we discard here as potentially uncanonical, will be able to be repaired later from the replica's DVC, if it turns out to be canonical.

Comment (sentientwaffle) [reply src/vsr/replica.zig]: Can we add
```
assert(message.header.commit == self.commit_min);
```
to the `message`'s assertions?

---

`op_min` is a tricky name, since it is about to become the new `replica.op` (which is the replica's _maximum_ op). What about `op_uncanonical_min` or `op_truncate`?

---

Does the `op_count` decrement track correctly when there are gaps in the DVC headers?

Comment (sentientwaffle) [reply src/vsr/replica.zig]: Also, when the `if (op_count == 0)` branch is taken, doesn't that mean that more than `config.pipeline_max` ops will be removed? i.e. shouldn't it be

```zig
if (op_count == 0) {
    op_min = op_min.? + 1;
    continue
}
```

File: src/vsr/replica.zig [hunk 18]
```diff
@@ -1023,76 +1025,13 @@ pub fn Replica(
...
-            // Verify that the repairs above have not replaced or advanced the latest op:
-            assert(self.journal.header_with_op(self.op).?.checksum == latest.checksum);
-
             assert(self.start_view_change_quorum);
             assert(!self.do_view_change_quorum);
             self.do_view_change_quorum = true;
 
-            self.discard_uncommitted_headers();
+            self.set_log_from_do_view_change_messages();
             assert(self.op >= self.commit_max);
```
Comment (sentientwaffle) [inline src/vsr/replica.zig:1198]:
```suggestion
            assert(self.op >= self.commit_max);
            assert(self.state_machine.prepare_timestamp >= self.journal.header_with_op(self.op).?.timestamp);
```

File: src/vsr/replica.zig [hunk 19]
```diff
@@ -4479,112 +4413,205 @@ pub fn Replica(
...
+                method,
+                self.view,
+                previous_op,
+                self.op,
+                previous_commit_max,
+                self.commit_max,
+            });
+        }
+
+        fn set_log_from_do_view_change_messages(self: *Self) void {
```
Comment (sentientwaffle) [inline src/vsr/replica.zig:5001]:
```suggestion
        fn set_log_from_do_view_change_messages(self: *Self) void {
            assert(self.status == .view_change);
            assert(self.leader_index(self.view) == self.replica);
            assert(self.replica_count > 1);
            assert(self.start_view_change_quorum);
            assert(self.do_view_change_quorum);

```

File: src/vsr/replica.zig [hunk 20]
```diff
@@ -4479,112 +4413,205 @@ pub fn Replica(
...
+                self.state_machine.prepare_timestamp = head.timestamp;
+            }
+
+            self.discard_uncommitted_headers();
+        }
+
+        /// Returns the highest `view_normal` from any replica, whose headers will be canonical,
+        /// since the replica has knowledge of previous view changes in which headers were replaced.
+        fn set_op_and_commit_max_from_do_view_change_messages(self: *Self) u64 {
+            assert(self.status == .view_change);
```
Comment (sentientwaffle) [inline src/vsr/replica.zig:5136]:
```suggestion
            assert(self.status == .view_change);
            assert(self.leader_index(self.view) == self.replica);
```

File: src/vsr/replica.zig [hunk 21]
```diff
@@ -4479,112 +4413,205 @@ pub fn Replica(
...
+                    if (k == null or message.header.commit > k.?) k = message.header.commit;
+                }
+            }
+
+            assert(v.? >= self.view_normal);
+
+            // Any headers removed must be a subset of the replica's do_view_change message, and
+            // must be removed before set_op_and_commit_max() below, since that may change self.op.
+            self.discard_uncanonical_headers(v.?);
+            self.set_op_and_commit_max(n.?, k.?, "on_do_view_change");
```
Comment (sentientwaffle) [inline src/vsr/replica.zig]: Since `self.set_op_and_commit_max` here is advancing `self.op`, after this runs `self.journal.header_for_op(self.op)` would be `null` — which temporarily violates a replica invariant.

It might be cleaner if:
- `set_op_and_commit_max` moved into `set_log_from_do_view_change_messages` immediately before or after the first `replace_header` loop
- move `discard_uncanonical_headers`  into `set_log_from_do_view_change_messages` as well, so that all mutation would happen in one place
- Then what's left of `set_op_and_commit_max_from_do_view_change_messages` function simply returns `struct { view_normal, op, commit }` (it would be renamed).

File: src/config.zig [hunk 22]
```diff
@@ -95,7 +95,8 @@ pub const connections_max = replicas_max + clients_max;
 /// This impacts the amount of memory allocated at initialization by the server.
 pub const message_size_max = switch (deployment_environment) {
     // Use a small message size during the simulator for improved performance.
-    .simulation => sector_size,
+    // (*2 so that there is room for pipeline_max headers in the DVC).
+    .simulation => sector_size * 2,
```
Comment (jorangreef) [inline src/config.zig]: Could we derive this exactly, taking the max?

File: src/vsr.zig [hunk 23]
```diff
@@ -199,6 +199,9 @@ pub const Header = extern struct {
     op: u64 = 0,
 
     /// The commit number of the latest committed prepare. Committed ops are immutable.
+    ///
+    /// * A `do_view_change` sets this to `commit_min`.
```
Comment (jorangreef) [inline src/vsr.zig]:
```suggestion
    /// * A `do_view_change` sets this to `commit_min`, to reflect the sending replica's progress.
```

File: src/vsr/journal.zig [hunk 24]
```diff
@@ -725,6 +727,7 @@ pub fn Journal(comptime Replica: type, comptime Storage: type) type {
             if (self.header_with_op_and_checksum(op, checksum)) |exact| {
                 if (exact.size == @sizeOf(Header)) {
                     message.header.* = exact.*;
+                    std.mem.set(u8, message.buffer[@sizeOf(Header)..config.sector_size], 0);
```
Comment (jorangreef) [inline src/vsr/journal.zig:732]: Can you help me understand why we need to do this?

Comment (jorangreef) [reply src/vsr/journal.zig:732]: It looks interesting! 😁

File: src/vsr/replica.zig [hunk 25]
```diff
@@ -63,6 +63,21 @@ const quorum_messages_null = [_]?*Message{null} ** config.replicas_max;
 const QuorumCounter = std.StaticBitSet(config.replicas_max);
 const quorum_counter_null = QuorumCounter.initEmpty();
 
+// CRITICAL: The number of prepare headers to include in the body:
+// We must provide enough headers to cover all uncommitted headers so that the new
+// leader (if we are in a view change) can decide whether to discard uncommitted headers
+// that cannot be repaired because they are gaps, and this must be relative to the
+// cluster as a whole (not relative to the difference between our op and commit number)
+// as otherwise we would break correctness.
+const view_change_headers_count = config.pipeline_max;
```
Comment (jorangreef) [inline src/vsr/replica.zig:72]: Great to capture it like this.

File: src/vsr/replica.zig [hunk 26]
```diff
@@ -877,6 +892,8 @@ pub fn ReplicaType(
             if (message.header.op > self.op + 1) {
                 log.debug("{}: on_prepare: newer op", .{self.replica});
                 self.jump_to_newer_op_in_normal_status(message.header);
+                // "`replica.op` exists" invariant is temporarily broken.
+                assert(self.journal.header_with_op(message.header.op - 1) == null);
```
Comment (jorangreef) [inline src/vsr/replica.zig:900]: What if we have a header shining through here from a previous log cycle?

File: src/vsr/replica.zig [hunk 27]
```diff
@@ -1106,6 +1125,21 @@ pub fn ReplicaType(
...
+        ///   (Reason: the headers bundled with the DVC(s) with the highest view_normal will be
+        ///   loaded into the new leader with `replace_header()`, not `repair_header()`).
+        ///
+        /// Across all DVCs in the quorum:
+        ///
+        /// * The headers of every DVC with the same view_normal must agree. In other words:
+        ///   dvc₁.headers[i].op == dvc₂.headers[j].op implies
+        ///   dvc₁.headers[i].checksum == dvc₂.headers[j].checksum.
+        ///   (Reason: the headers bundled with the DVC(s) with the highest view_normal will be
+        ///   loaded into the new leader with `replace_header()`, not `repair_header()`).
```
Comment (jorangreef) [inline src/vsr/replica.zig:1145]: These are important invariants to list. I had to do a double-take for the 2nd invariant but it checks out.

File: src/config.zig (hunk 22 above)
Comment (jorangreef) [reply src/config.zig]: So that we require a min of `pipeline_max` headers, and then round up to the nearest sector? This will leave `pipeline_max` more future proof, especially when we increase `clients_max`.

File: src/vsr/journal.zig (hunk 24 above)
Comment (jorangreef) [reply src/vsr/journal.zig:732]: My guess is that it's in case this message is received locally and persisted to disk, so that we don't leak random data into the sector padding? I think usually the MessageBus would otherwise take care of zeroing the padding here?

Comment (jorangreef) [reply src/vsr/journal.zig:732]: We could also assert this in debug builds or for `config.verify`, at call sites where we write this message to disk.

File: src/vsr/replica.zig [hunk 28]
```diff
@@ -1345,7 +1299,40 @@ pub fn ReplicaType(
...
+            //    gap at op 6). But there is a conflict at op=5. For correctness, replica 1 must
+            //    pick 5a — 5a may be committed by replica 0.
+            //    Without replica 0's assistance, replica 1 has no way to pick between 5a/5b.
+            //
+            // Including at least as many headers in the recovery response as the DVC maintains the
+            // invariant: DVCs with the same view_normal must never disagree on the identity of a
+            // message.
+            //
+            // (DVCs can still safely include gaps — but they must be of the form [4a,__,6a],
+            // not [4a,__,6b]).
```
Comment (jorangreef) [inline src/vsr/replica.zig:1334]: 🥳

Comment (jorangreef) [reply src/vsr/replica.zig:1334]: Awesome worked example.

File: src/vsr/replica.zig [hunk 29]
```diff
@@ -1345,7 +1299,40 @@ pub fn ReplicaType(
...
+            const count_max = view_change_headers_count;
```
Comment (jorangreef) [inline src/vsr/replica.zig]: To avoid introducing another local variable, i.e. to rather "shrink the scope", let's just use `view_change_headers_count` inline below when passing to `copy_latest...`, especially since we only use it once.

Then we just add a comma after the last arg to `copy_latest...` to deal with line length.

File: src/vsr/replica.zig [hunk 30]
```diff
@@ -2911,16 +2901,11 @@ pub fn ReplicaType(
...
             };
 
-            // CRITICAL: The number of prepare headers to include in the body:
-            // We must provide enough headers to cover all uncommitted headers so that the new
-            // leader (if we are in a view change) can decide whether to discard uncommitted headers
-            // that cannot be repaired because they are gaps, and this must be relative to the
-            // cluster as a whole (not relative to the difference between our op and commit number)
-            // as otherwise we would break correctness.
-            const count_max = config.pipeline_max;
+            const count_max = view_change_headers_count;
```
Comment (jorangreef) [inline src/vsr/replica.zig]: Here too let's use `view_change_headers_count` inline since we only use it essentially once (`copy_latest...` will also do the `> 0` assert).

File: src/vsr/replica.zig [hunk 31]
```diff
@@ -4491,6 +4482,56 @@ pub fn ReplicaType(
...
+        }
+
+        /// Replaces the header if the header is different and not already committed.
+        /// The caller must ensure that the header is trustworthy.
+        fn replace_header(self: *Self, header: *const Header) void {
+            assert(self.op_checkpoint <= self.commit_min);
+            assert(header.command == .prepare);
+            assert(header.op <= self.op); // Never advance the op.
+            // TODO(Rebase) assert that it is ≤ the checkpoint trigger
+            //assert(header.op <= self.op_checkpoint_trigger());
```
Comment (jorangreef) [inline src/vsr/replica.zig]: Should this assert be re-enabled now?

File: src/vsr/replica.zig [hunk 32]
```diff
@@ -4491,6 +4482,56 @@ pub fn ReplicaType(
...
+                    assert(existing_header.checksum == header.checksum);
+                    return;
+                } else {
+                    if (header.op <= self.op_checkpoint) {
+                        // Never replace a checkpointed op — those slots are needed by the following
+                        // WAL wrap.
+                        return;
+                    } else {
+                        // If an op is committed but not checkpointed, we must still have the header.
+                        @panic("missing committed, uncheckpointed header");
```
Comment (jorangreef) [inline src/vsr/replica.zig:4486]: Nice!

File: src/vsr/replica.zig [hunk 33]
```diff
@@ -4899,112 +4948,322 @@ pub fn ReplicaType(
...
+            assert(do_view_change_head.op >= do_view_change_head.commit_min_max);
+            assert(do_view_change_head.commit_min_max >= self.commit_min);
+
+            const view_normal_canonical = do_view_change_head.view_normal;
+            // `op_uncanonical` must be computed before calling `set_op_and_commit_max()`, since
+            // that may change `replica.op`.
+            //
+            // Don't remove the uncanonical headers yet, though — even though the removed headers are
+            // a subset of the DVC headers, removing and then adding them back would cause clean
+            // headers to become dirty.
```
Comment (jorangreef) [inline src/vsr/replica.zig]: Good catch!

Comment (jorangreef) [reply src/vsr/replica.zig]: "yet, though" -> "yet"

File: src/vsr/replica.zig [hunk 34]
```diff
@@ -4899,112 +4948,322 @@ pub fn ReplicaType(
...
+            const op_uncanonical = self.op_uncanonical_min(view_normal_canonical);
+            assert(op_uncanonical <= self.op + 1);
+            assert(op_uncanonical >= self.op + 1 -| config.pipeline_max);
+            assert(op_uncanonical >= self.commit_min);
```
Comment (jorangreef) [inline src/vsr/replica.zig]: Should it not always be > `self.commit_min`?

Comment (jorangreef) [reply src/vsr/replica.zig]: i.e. Can `commit_min` itself be uncanonical?

File: src/vsr/replica.zig [hunk 35]
```diff
@@ -4899,112 +4948,322 @@ pub fn ReplicaType(
...
+            // where the new leader's headers depends on which of replica 1 and 2's DVCs is used
+            // for repair before the other (i.e. whether they repair op 6 or 7 first).
+            //
+            // For the above case to occur, replicas 0, 1, and 2 must all share the highest `view_normal`.
+            // And since they share the latest `view_normal`, ops 5,6,7 were just installed by
+            // `replace_header`, which is order-independent (it doesn't use the hash chain).
+            //
+            // (If replica 0's view_normal was greater than 1/2's, then replica 0 must have all
+            // headers from previous views. Which means 6,7 are from the current view. But since
+            // replica 0 doesn't have 6/7, then replica 1/2 must share the latest view_normal. ∎)
```
Comment (jorangreef) [inline src/vsr/replica.zig]:
```suggestion
            // replica 0 doesn't have 6/7, then replica 1/2 must share the latest view_normal.)
```

A microdot? 😉

File: src/vsr/replica.zig [hunk 36]
```diff
@@ -4899,112 +4948,322 @@ pub fn ReplicaType(
...
 
-            assert(self.op == latest.op);
-            self.journal.remove_entries_from(self.op + 1);
-            assert(self.journal.header_with_op(self.op).?.checksum == latest.checksum);
+            // Since we used do_view_change_head to set the replica.op, it must have been loaded
+            // into the headers (if it wasn't present already).
+            assert(self.journal.header_with_op(self.op) != null);
+
+            // The iteration order of DVCs for repair does not impact the final result.
+            // In other words, you can't end up in a situation with a DVC quorums like:
```
Comment (jorangreef) [inline src/vsr/replica.zig]:
```suggestion
            // In other words, you can't end up in a situation with a DVC quorum like:
```

File: src/vsr/replica.zig [hunk 37]
```diff
@@ -4899,112 +4948,322 @@ pub fn ReplicaType(
...
+            //
+            //   replica     headers  commit_min
+            //         0   4 5 _ _ 8           4 (new leader; handling DVC quorum)
+            //         1   4 _ 6 _ 8           4
+            //         2   4 _ _ 7 8           4
+            //         3  (4 5 6 7 8)          8 (didn't participate in view change)
+            //         4  (4 5 6 7 8)          8 (didn't participate in view change)
+            //
+            // where the new leader's headers depends on which of replica 1 and 2's DVCs is used
```
Comment (jorangreef) [inline src/vsr/replica.zig]:
```suggestion
            // where the new leader's headers depends on which of replica 1 and 2's DVC is used
```

File: src/vsr/replica.zig (hunk 35 above)
Comment (jorangreef) [reply src/vsr/replica.zig]: Thanks for the awesome worked example!

File: src/vsr/replica.zig [hunk 38]
```diff
@@ -4899,112 +4948,322 @@ pub fn ReplicaType(
...
+                    }
+                }
+            }
+
+            // The `prepare_timestamp` prevents a primary's own clock from running backwards.
+            // Therefore, `prepare_timestamp`:
+            // 1. is advanced if behind the cluster, but never reset if ahead of the cluster, i.e.
+            // 2. may not always reflect the timestamp of the latest prepared op, and
+            // 3. should be advanced before discarding the timestamps of any uncommitted headers.
+            const head = self.journal.header_with_op(self.op).?;
```
Comment (jorangreef) [inline src/vsr/replica.zig]:
```suggestion
            const head_timestamp = self.journal.header_with_op(self.op).?.timestamp;
```

To shrink the scope further for purpose.

File: src/vsr/replica.zig [hunk 39]
```diff
@@ -4899,112 +4948,322 @@ pub fn ReplicaType(
...
+        }
+
+        fn do_view_change_quorum_head(self: *const Self) struct {
+            /// The highest `view_normal` of any DVC.
+            ///
+            /// The headers bundled with DVCs with the highest `view_normal` are canonical, since
+            /// the replica has knowledge of previous view changes in which headers were replaced.
+            view_normal: u32,
+            /// The highest `commit_min` from any DVC.
+            /// (This is not a `commit_max`.)
```
Comment (jorangreef) [inline src/vsr/replica.zig]:
```suggestion
            /// The highest `commit_min` from any DVC (this is not a `commit_max`).
```

File: src/vsr/replica.zig [hunk 40]
```diff
@@ -4899,112 +4948,322 @@ pub fn ReplicaType(
...
+                    // * may be higher than the view in any of the prepare headers.
+                    // * must be lower than the view of this view change.
+                    const view_normal = @intCast(u32, message.header.timestamp);
+                    assert(view_normal < message.header.view);
+
+                    if (replica == self.replica) {
+                        assert(view_normal == self.view_normal);
+                        assert(message.header.op == self.op);
+                        // We may have a newer commit than our own DVC due to async commits
+                        // (see below).
```
Comment (jorangreef) [inline src/vsr/replica.zig]:
```suggestion
                        // We may have a newer commit than our DVC due to async commits (see below).
```

File: src/vsr/replica.zig [hunk 41]
```diff
@@ -4899,112 +4948,322 @@ pub fn ReplicaType(
...
+                    if (k == null or message.header.commit > k.?) k = message.header.commit;
+                }
+            }
+
+            // Consider the case:
+            // 1. Start committing op=N.
+            // 2. Send `do_view_change` to self.
+            // 3. Finish committing op=N.
+            // 4. Remaining `do_view_change` messages arrive, completing the quorum.
+            // In this scenario, the our own `do_view_change`'s commit is `N-1`, but `commit_min=N`.
```
Comment (jorangreef) [inline src/vsr/replica.zig]:
```suggestion
            // In this scenario, our own DVC's commit is `N-1`, but `commit_min=N`.
```

File: src/vsr/replica.zig [hunk 42]
```diff
@@ -4899,112 +4948,322 @@ pub fn ReplicaType(
...
+            // Don't let the commit backtrack.
+            if (k.? < self.commit_min) {
+                assert(k.? == self.do_view_change_from_all_replicas[self.replica].?.header.commit);
```
Comment (jorangreef) [inline src/vsr/replica.zig]: Great!

File: src/vsr/replica.zig (hunk 38 above)
Comment (jorangreef) [reply src/vsr/replica.zig]: We could also consider adding `timestamp` to `do_view_change_quorum_head` since that is what we are thinking about here... does any quorum have a newer prepare timestamp?

File: src/vsr/replica.zig [hunk 43]
```diff
@@ -2951,108 +2936,111 @@ pub fn ReplicaType(
...
+        fn op_uncanonical_min(self: *const Self, view_normal_canonical: u64) usize {
+            assert(self.replica_count > 1);
+            assert(self.status == .view_change);
+            assert(self.leader_index(self.view) == self.replica);
+            assert(self.do_view_change_quorum);
+            assert(!self.repair_timeout.ticking);
+            assert(self.journal.header_with_op(self.op) != null);
+            assert(self.view_normal <= view_normal_canonical);
+
+            if (self.view_normal == view_normal_canonical) return self.op + 1;
```
Comment (jorangreef) [inline src/vsr/replica.zig]: Since when using this at the call site, we always subtract 1 (or add 1 to compare, i.e. in an assert), can we not rather return the op without the plus one? Or otherwise use an optional return type to indicate?

File: src/vsr/replica.zig [hunk 44]
```diff
@@ -2951,108 +2936,111 @@ pub fn ReplicaType(
...
+        ///   replica 0: 4, 5, 6b, 7b, 8b  (commit_min=6b, leader, status=normal, view=X)
+        ///   replica 1: 4, 5, 6b, --, --  (commit_min=5, follower, status=normal, view=X)
+        ///   replica 2: 4, 5, 6a, --, 8b  (view<X)
+        ///
+        /// 1. Replica 0 crashes immediately after committing 6b.
+        /// 2. Replicas 1 and 2 must determine the new chain HEAD.
+        /// 3. 8b is discarded due to the gap in 7.
+        /// 4. To distinguish between 6a and 6b (and safely discard 6a), the new leader trusts ops
+        ///    from the DVC(s) with the greatest `view_normal`.
+        fn op_uncanonical_min(self: *const Self, view_normal_canonical: u64) usize {
```
Comment (jorangreef) [inline src/vsr/replica.zig]: I was wondering whether we can't find a better name for this method?

Since the version of the op we have could in fact equally turn out to be canonical, we're just not sure.

File: src/vsr/replica.zig [hunk 45]
```diff
@@ -4899,112 +4948,322 @@ pub fn ReplicaType(
...
+            // Any uncanonical ops remaining either:
+            // * Connect to the hash chain on the right.
+            // * Do not connect on the right (hash chain break).
+            //
+            // If there is a hash chain break, none of the headers from the canonical DVCs replaced
+            // the broken op. It is truncated like a gap.
+            //
+            // Removing these is necessary for correctness and liveness, to ensure that
+            // disconnected headers do not remain in place in lieu of gaps.
+            var op: u64 = op_uncanonical - 1;
```
Comment (jorangreef) [inline src/vsr/replica.zig]: Is it possible where a replica is so far behind that its uncanonical op is actually a few tens of ops behind, also completely disconnected, then we remove everything to the right, and then participate in a subsequent view change, but having lost what were committed headers (what we removed)?

On second thought, I guess not, since it's bounded by `pipeline_max` and we've noted this also in comments. But I thought I'd ask just to double check.

File: src/vsr/replica.zig [hunk 46]
```diff
@@ -4899,112 +4948,322 @@ pub fn ReplicaType(
...
+            while (op <= self.op) : (op += 1) {
```
Comment (jorangreef) [inline src/vsr/replica.zig]: Can we refactor out some blocks within this function to keep the overall function body under 70 lines?

File: src/vsr/journal.zig (hunk 24 above)
Comment (sentientwaffle) [reply src/vsr/journal.zig:732]: Yeah, this isn't directly related to trust-committed-ops, it is a just a bug I ran into during testing!

It is documented in the commit https://github.com/tigerbeetledb/tigerbeetle/pull/102/commits/53e7d106e1f60751e54ae8c2685a689931807a53. But I'll add an explanation in the code, too.

> We could also assert this in debug builds or for `config.verify`, at call sites where we write this message to disk.

We do — that's what caught this error :grin:.

File: src/vsr/replica.zig (hunk 26 above)
Comment (sentientwaffle) [reply src/vsr/replica.zig:900]: We might, but it wouldn't be returned by `header_with_op()` (which only returns an exact `op` match).

File: src/vsr/replica.zig (hunk 27 above)
Comment (sentientwaffle) [reply src/vsr/replica.zig:1145]: It was surprising to me too! I "discovered" it because it wasn't being completely enforced — it could be broken by recovery protocol, which didn't include enough headers in the `recovery_response` message.

File: src/vsr/replica.zig (hunk 31 above)
Comment (sentientwaffle) [reply src/vsr/replica.zig]: Yes, thank you!

File: src/vsr/replica.zig (hunk 34 above)
Comment (sentientwaffle) [reply src/vsr/replica.zig]: Good point; `commit_min` is always canonical. `op_uncanonical_min` already had the correct check, too.

File: src/vsr/replica.zig (hunk 35 above)
Comment (sentientwaffle) [reply src/vsr/replica.zig]: That is a deliberate ["end-of-proof"](https://en.wikipedia.org/wiki/Tombstone_(typography)) symbol, though I can remove it if you prefer.

File: src/vsr/replica.zig (hunk 44 above)
Comment (sentientwaffle) [reply src/vsr/replica.zig]: :thinking: My working definition for uncanonical headers is:

> An uncanonical message _may have_ been removed/changed by a prior view.

i.e. the new leader may decide to keep some "uncanonical" headers. By that definition I think the naming is correct. Are you using "canonical" to mean "all headers part of the new view, according to the leader at view start"?

File: src/vsr/replica.zig (hunk 43 above)
Comment (sentientwaffle) [reply src/vsr/replica.zig]: Nice! Yes, it simplifies the caller to flip `op_uncanonical_min()` and return `op_canonical_max()` instead.

File: src/vsr/replica.zig (hunk 45 above)
Comment (sentientwaffle) [reply src/vsr/replica.zig]: Right, it is bounded by `pipeline_max`. Also if the header is possibly committed, it can't be disconnected at this point. The other DVCs would have provided the headers to repair the committed header's hash chain, due to the quorum intersection property.

File: src/vsr/replica.zig (hunk 46 above)
Comment (sentientwaffle) [reply src/vsr/replica.zig]: I will refactor this some, but I don't think it will be under 70 lines yet. I have some other changes in mind for a future PR (to more aggressively verify the "all same-view_normal-DVC headers must match" invariant) that will take it the rest of the way. FWIW, I don't think this function actually does "too much" — rather, it has lots of documentation, checks, and logging, which inflates the line count. (Plus we have iterate the DVCs twice, both times filtering+checking `view_normal`).

One (possibly controversial :wink:) refactor — I restructured `discard_uncommitted_ops`:
- Renamed to `do_view_change_op_max`
- It now just returns the new `replica.op`; it does not set `replica.op` or truncate entries from the log.
- I moved the "search for hash break in uncanonical headers" into there as well.

My goal is to move as much of the state mutation as possible directly into `set_log_from_do_view_change_messages`, rather than the replica functions it invokes. (I find having the mutation as close together as possible makes it easier to mentally/manually check invariants).

File: src/vsr/replica.zig (hunk 42 above)
Comment (sentientwaffle) [reply src/vsr/replica.zig]: Ah, actually there was a bug in this assertion! It needs to handle committing multiple ops between while waiting for the DVC quorum.

Comment (sentientwaffle) [reply src/vsr/replica.zig]: i.e. if we are replica 0, then replica 1's DVC commit_min might have been the highest in the quorum (`k`). But in the mean time we committed ahead of it (`self.commit_min > k`). I updated the comment, and the assert now reads:
```zig
                assert(self.commit_min >
                    self.do_view_change_from_all_replicas[self.replica].?.header.commit);
```

File: src/vsr/journal.zig (hunk 24 above)
Comment (jorangreef) [reply src/vsr/journal.zig:732]: Nice! I had a feeling we had those asserts in there somewhere but thought I'd pretend we didn't just in case!

Comment (jorangreef) [reply src/vsr/journal.zig:732]: 😁

File: src/vsr/replica.zig (hunk 31 above)
Comment (jorangreef) [reply src/vsr/replica.zig]: We should improve our git precommit hook to lint the code for any `// assert` patterns.

File: src/vsr/replica.zig (hunk 35 above)
Comment (jorangreef) [reply src/vsr/replica.zig]: Let's keep it. And then let it be an Easter egg. i.e. We have so many proofs that we won't always use it.

File: src/vsr/replica.zig (hunk 42 above)
Comment (jorangreef) [reply src/vsr/replica.zig]: Good catch. Expresses the concurrent `commit_min` increment more clearly now too.

File: src/vsr/replica.zig (hunk 43 above)
Comment (jorangreef) [reply src/vsr/replica.zig]: Yes, `op_canonical_max()` would be perfect, then it's stated in the positive and we can drop the `uncanonical` naming.

File: src/vsr/replica.zig (hunk 44 above)
Comment (jorangreef) [reply src/vsr/replica.zig]: > Are you using "canonical" to mean "all headers part of the new view, according to the leader at view start"?

Yes. And these we know for sure to be canonical.

> My working definition for uncanonical headers is:

>> An uncanonical message may have been removed/changed by a prior view.

Yes. I'm thinking that it could also later be found to be canonical  say on another replica. So it's more a question of uncertainty. Not knowing for sure if it is canonical. But we can't say for sure that it is uncanonical.

Comment (jorangreef) [reply src/vsr/replica.zig]: i.e. Like the opposite of a bloom filter, it will tell you for sure if something is not in a set, but it can't tell you for sure if something is in a set. The opposite of that. 😁

File: src/vsr/replica.zig (hunk 46 above)
Comment (jorangreef) [reply src/vsr/replica.zig]: > My goal is to move as much of the state mutation as possible directly into set_log_from_do_view_change_messages, rather than the replica functions it invokes.

Excellent idea. Let's do it.

File: src/vsr/replica.zig (hunk 44 above)
Comment (sentientwaffle) [reply src/vsr/replica.zig]: Gotcha, we were using different definitions for "canonical headers" then. I was thinking of it in terms of the new leader's viewpoint, with the uncertainty built in. Phrased in the positive, my definition could have been "A canonical header was part of the latest view_normal".

(Even the "canonical" headers (according to this definition) may still be discarded if there is a gap across all DVCs.)

Comment (sentientwaffle) [reply src/vsr/replica.zig]: What if we define "the highest view_normal before now" to be the "base view" (or similar — "base" is probably too general a term). Then `op_canonical_max()` can be named (e.g.) `op_base_max()`.

Comment (jorangreef) [reply src/vsr/replica.zig]: > Phrased in the positive, my definition could have been "A canonical header was part of the latest view_normal".

I was actually thinking this too, and also that these are the same, since the headers from the latest `view_normal` will be installed by the new primary and be part of the `start_view`.

> Even the "canonical" headers (according to this definition) may still be discarded if there is a gap across all DVCs.

Yes, agreed.

Comment (sentientwaffle) [reply src/vsr/replica.zig]: > I was actually thinking this too, and also that these are the same, since the headers from the latest view_normal will be installed by the new primary and be part of the start_view.

They will be installed, but will not necessarily be part of the `start_view`. A subset of the canonical headers (meaning here: headers from the latest `view_normal`) may be removed before the `start_view` (by `discard_uncommitted_headers`) if there is a gap in them (that the DVC quorum could not fill/repair). So I don't think they _are_ the same thing.

(I think this might be the root of our confusion here, so lmk if I should elaborate).

Comment (jorangreef) [reply src/vsr/replica.zig]: Ah, I was not being precise enough. I was thinking they are the same _ceteris parabus_, but of course if we discard because of gaps then they will differ.

But _canonical_ is all w.r.t. to other possible candidate headers for the slots coming in from older views. That's how I was thinking of _canonical_. All about choosing which headers trump others, not so much about what will end up in the `start_view` message.

Comment (jorangreef) [reply src/vsr/replica.zig:2955]: That's how I was thinking of _canonical_. All about choosing which headers trump others, not so much about what will end up in the `start_view`.

Comment (sentientwaffle) [reply src/vsr/replica.zig]: Gotcha; that makes sense! I will expand on this in the code — it is a useful term to have when explaining/describing view change precedence.

Then for renaming `op_canonical_max()`, something like `leader_op_canonical_max()` (since it is only called by the new leader)?

Comment (jorangreef) [reply src/vsr/replica.zig]: i.e. canonical headers may be uncommitted or committed, so they may still be discarded. They're canonical in the sense that they're ratified by being part of the DVC messages from the latest `view_normal`, and they help to decide which other headers are allowed in via hash chain connection.

Happy to think of another name also. I don't know if saying "base headers" is as clear, although "base" does mean a starting point. We need to capture the sense of "authoritative" or "approved" or "quorum". Maybe "quorum headers"?

Comment (jorangreef) [reply src/vsr/replica.zig]: Let's keep it short with `op_canonical_max()` — we also have other methods only used by the primary, but it's fine if we don't prefix them.

It would be great to rename all the `leader` references to `primary` one day.

File: src/config.zig [hunk 47]
```diff
@@ -94,12 +94,20 @@ pub const connections_max = replicas_max + clients_max;
...
+    .simulation => message_size_max_min,
     else => 1 * 1024 * 1024,
 };
 
+/// The smallest possible message_size_max (for use in the simulator to improve performance).
+/// The message body must have room for pipeline_max headers in the DVC.
+const message_size_max_min = std.math.max(
+    sector_size,
+    std.mem.alignForward(
+        128 + pipeline_max * 128, // 128 == @sizeOf(vsr.Header)
```
Comment (jorangreef) [inline src/config.zig]: Let's always use `@sizeOf(vsr.Header)` instead of a magic number, to always stay in sync through the type system with any Header size changes.

File: src/vsr/replica.zig [hunk 48]
```diff
@@ -2972,75 +2983,26 @@ pub fn ReplicaType(
             );
 
             assert(uncanonical_op_count <= config.pipeline_max);
-            if (uncanonical_op_count == 0) return self.op + 1;
+            if (uncanonical_op_count == 0) return self.op;
 
             // * When uncanonical_op_count = self.op - self.commit_min,
             //   self.op - (uncanonical_op_count - 1) =
             //   (self.op - uncanonical_op_count) + 1 =
```
Comment (jorangreef) [inline src/vsr/replica.zig]: Do we need to update any of these plus-ones or minus-ones?

File: src/vsr/replica.zig [hunk 49]
```diff
@@ -5263,9 +5218,92 @@ pub fn ReplicaType(
                 .view_normal = v.?,
                 .commit_min_max = k.?,
                 .op = n.?,
+                .timestamp = t.?,
             };
         }
 
+        /// Identify uncommitted headers that to discard during a view change before the primary
```
Comment (jorangreef) [inline src/vsr/replica.zig]: "that to discard" -> "to discard"

Would be great also to edit to fit on one line, as a one line summary.

File: src/vsr/replica.zig [hunk 50]
```diff
@@ -5263,9 +5218,92 @@ pub fn ReplicaType(
...
+        /// starts the view.
+        /// This is required to maximize availability in the presence of storage faults.
+        /// Refer to the CTRL protocol from Protocol-Aware Recovery for Consensus-Based Storage.
+        ///
+        /// Returns the highest op that:
+        /// - precedes any hash chain breaks in the uncanonical headers, and
+        /// - precedes any header gaps.
```
Comment (jorangreef) [inline src/vsr/replica.zig]: Nice summary.

File: src/vsr/replica.zig [hunk 51]
```diff
@@ -5263,9 +5218,92 @@ pub fn ReplicaType(
...
+        /// prepared on another replica before the old primary crashes, then this function finds a
+        /// gap for ops=7,8 and will attempt to discard ops 7,8,9.
+        fn do_view_change_op_max(self: *const Self, op_canonical: u64) u64 {
+            assert(self.replica_count > 1);
+            assert(self.status == .view_change);
+            assert(self.leader_index(self.view) == self.replica);
+            assert(self.do_view_change_quorum);
+            assert(!self.repair_timeout.ticking);
+            assert(self.op >= self.commit_max);
+            assert(self.op - self.commit_max <= config.journal_slot_count);
```
Comment (jorangreef) [inline src/vsr/replica.zig:5266]: Is there an off-by-one here? Since we are comparing an _index_ on the left with a _count_ on the right?

File: src/vsr/replica.zig [hunk 52]
```diff
@@ -5263,9 +5218,92 @@ pub fn ReplicaType(
...
+        /// set as the latest op for the quorum.
+        ///
+        /// In this case, it may be impossible for the new primary to repair the missing header as
+        /// the rest of the cluster may have already discarded it. We therefore iterate over our
+        /// uncommitted header gaps to discard any that may be impossible to repair.
+        ///
+        /// For example, if the old primary replicates ops=7,8,9 (all uncommitted) but only op=9 is
+        /// prepared on another replica before the old primary crashes, then this function finds a
+        /// gap for ops=7,8 and will attempt to discard ops 7,8,9.
+        fn do_view_change_op_max(self: *const Self, op_canonical: u64) u64 {
```
Comment (jorangreef) [inline src/vsr/replica.zig:5257]: Great comment.

File: src/vsr/replica.zig [hunk 53]
```diff
@@ -5263,9 +5218,92 @@ pub fn ReplicaType(
...
+            // If there is a hash chain break, none of the headers from the canonical DVCs replaced
+            // the broken op. It is truncated like a gap.
+            //
+            // Removing these is necessary for correctness and liveness, to ensure that
+            // disconnected headers do not remain in place in lieu of gaps.
+            const op_before_break = blk: {
+                var op: u64 = op_canonical;
+                while (op <= self.op) : (op += 1) {
+                    if (self.journal.header_with_op(op)) |header| {
+                        if (self.journal.header_with_op(op + 1)) |next| {
```
Comment (jorangreef) [inline src/vsr/replica.zig]: I think we might be going too far here in the loop, since on the last iteration `op=self.op`  and then we look for the next op, i.e. `self.op+1`?

Comment (jorangreef) [reply src/vsr/replica.zig]: i.e. I would have expected that with `self.op` set, we don't have any headers beyond `self.op` at this stage in the WAL?

File: src/vsr/replica.zig [hunk 54]
```diff
@@ -5263,9 +5218,92 @@ pub fn ReplicaType(
...
+            // (the old primary may have committed the op shortly before crashing), nevertheless,
+            // if it was committed it would have survived into the new view as a header not a gap.
+            const op_before_gap = blk: {
+                // An op cannot be uncommitted if it is definitely outside the pipeline.
+                const op_committed = std.math.max(self.commit_max, self.op -| config.pipeline_max);
+                assert(op_committed <= self.op);
+
+                var op = op_committed + 1;
+                while (op <= self.op) : (op += 1) {
+                    if (self.journal.header_with_op(op) == null) break :blk op - 1;
```
Comment (jorangreef) [inline src/vsr/replica.zig]: It would be great to use the same style w.r.t. where we do the plus-one as we do for `op_before_break`.

i.e. `op_before_break` assigns `var op: u64 = op_canonical;` and then adds one when looking for the next header, wherease `op_before_gap` assigns `var op = op_committed + 1;` and then corrects for this in the loop.

I think we could make both loops symmetrical? And then the first style seems better.

File: src/vsr/replica.zig [hunk 55]
```diff
@@ -5263,9 +5218,92 @@ pub fn ReplicaType(
...
+                } else break :blk self.op;
+            };
+
+            return std.math.min(op_before_break, op_before_gap);
```
Comment (jorangreef) [inline src/vsr/replica.zig:5309]: Nice way to work this whole function, getting to this point.

**Review by jorangreef — COMMENTED** [review]
This new refactor is much cleaner!

**Comment by jorangreef** [comment]
The `do_view_change_op_max()` strategy is great.

File: src/vsr/replica.zig (hunk 51 above)
Comment (sentientwaffle) [reply src/vsr/replica.zig:5266]: :thinking: Borrowing the diagram from `op_checkpoint_next` (where journal_slot_count=8 and lsm_batch_multiple=2):

```
        ///     0   4   8   2   6   0   4  │ 0---4---
        ///   0 ─────✓·%                   │ 01234✓6%   initial log fill
        ///   1 ───────────✓·%             │ 890✓2%45   first wrap of log
```

When `op_checkpoint == 5`, the highest `replica.op` we can reach before another checkpoint (or even commit) is `13`. `13 - 5 = 8 = journal_slot_count`.

File: src/vsr/replica.zig (hunk 54 above)
Comment (sentientwaffle) [reply src/vsr/replica.zig]: Good point! It is cleaner that way.

File: src/vsr/replica.zig (hunk 51 above)
Comment (sentientwaffle) [reply src/vsr/replica.zig:5266]: This is an index vs a count, but we don't actually require that `commit_max` is in the log, i.e. counted by the slot_count (when `commit_max` is equal to `op_checkpoint`). Or rather, we _won't_ require that — I'm fixing that issue in a different branch (via `VSRState.commit_min_checksum`) :sweat_smile:.

Comment (jorangreef) [reply src/vsr/replica.zig:5266]: Great!

**Review by jorangreef — COMMENTED** [review]
LGTM!

I can't Approve because I'm the PR author.

**Review by sentientwaffle — APPROVED** [review]
