### PR TITLE
vsr: prevent old primaries from evicting clients

### LINKED ISSUE #662: Crash: 9315705680320980549
<strong>Commit:</strong> ```46c00e284b7be627fb90a23a0c2d138779a2fadc``` <br><br><strong>Branches:</strong> main<br><br><strong>Duration to run seed in ReleaseSafe mode:</strong> 4s<br><br><strong>Stack Trace:</strong><br>
```
thread panic: session evicted: too many concurrent client sessions
src/vsr/client.zig:313:13: in vsr.client.Client(state_machine.StateMachineType(testing.storage.Storage,(struct constants.StateMachineConfig constant)),testing.cluster.message_bus.MessageBus).on_message (simulator)
@panic(\"session evicted: too many concurrent client sessions\");

src/testing/cluster/network.zig:247:39: in testing.cluster.network.Network.deliver_message (simulator)
target_bus.on_message_callback(target_bus, target_message);

src/testing/packet_simulator.zig:339:49: in testing.cluster.ClusterType(state_machine.StateMachineType).tick (simulator)
link_packet.callback(link_packet.packet, path);

src/simulator.zig:350:31: in main (simulator)
simulator.cluster.tick();

zig/lib/std/start.zig:561:37: in std.start.posixCallMainAndExit (simulator)
const result = root.main() catch |err| {

zig/lib/std/start.zig:322:5: in std.start._start (simulator)
@call(.{ .modifier = .never_inline }, posixCallMainAndExit, .{});

debug: exit with signal: 6. Indicates a crash bug.


```
<br><strong>Debug Logs:</strong><br><details><summary>Tail</summary><br>
```debug: Replaying seed 9315705680320980549 in Debug mode with full debug logging enabled...


SEED=9315705680320980549

replicas=3
standbys=2
clients=5
request_probability=1%
idle_on_probability=12%
idle_off_probability=15%
one_way_delay_mean=7 ticks
one_way_delay_min=0 ticks
packet_loss_probability=16%
path_maximum_capacity=19 messages
path_clog_duration_mean=479 ticks
path_clog_probability=1%
packet_replay_probability=14%
partition_mode=PartitionMode.uniform_partition
partition_symmetry=PartitionSymmetry.symmetric
partition_probability=2%
unpartition_probability=4%
partition_stability=125 ticks
unpartition_stability=18 ticks
read_latency_min=1
read_latency_mean=3
write_latency_min=0
write_latency_mean=7
read_fault_probability=3%
write_fault_probability=6%
crash_probability=0.00002%
crash_stability=861 ticks
restart_probability=0.0002%
restart_stability=899 ticks
 0/ .3V1/__1C0:__4Jo0/_0J!0:4Wo45056Gf4/4Pp0/3Pq
 0/ .3V2/__2C0:__4Jo0/_0J!0:4Wo45056Gf3/4Pp0/3Pq
```
</details>

### PR DESCRIPTION
**Pull request by matklad**
We want to maintain the following invariant:

If the client knows a certain reply, it is aware of a view that committed the corresponding prepare.

Otherwise, the client sends a next request to the old primary and gets kicked out.

To do so, we include current view whenever we send a reply back to the client (we keep the original view on disk for storage determinism).

This creates a problem: replies for the same request now have different checksums. This breaks reply's hashchaining. Fix that by using the `context`

Closes: #662
Seed: 9315705680320980549

## Pre-merge checklist

Performance:

* [x] Compare `zig build benchmark` on linux before and after this pr.

Before:

```
λ ./scripts/benchmark.sh --transfer-count 1000000
++ uname
+ '[' Linux = Linux ']'
+ ZIG_OS=linux
+ target_set=false
+ case "$*" in
+ target_set=true
+ TARGET=
+ '[' true = false ']'
+ ZIG_EXE=./zig/zig
+ BUILD_ROOT=./
+ CACHE_ROOT=./zig-cache
+ GLOBAL_CACHE_ROOT=/home/matklad/.cache/zig
+ ./zig/zig run ./scripts/build_runner.zig -target native-linux --main-pkg-path ./ -- ./zig/zig ./ ./zig-cache /home/matklad/.cache/zig install -Drelease-safe -Dconfig=production -Dtarget=native-linux
Formatting replica 0...
Starting replica 0...

Benchmarking...
++ uname
+ '[' Linux = Linux ']'
+ ZIG_OS=linux
+ target_set=false
+ case "$*" in
+ target_set=true
+ TARGET=
+ '[' true = false ']'
+ ZIG_EXE=./zig/zig
+ BUILD_ROOT=./
+ CACHE_ROOT=./zig-cache
+ GLOBAL_CACHE_ROOT=/home/matklad/.cache/zig
+ ./zig/zig run ./scripts/build_runner.zig -target native-linux --main-pkg-path ./ -- ./zig/zig ./ ./zig-cache /home/matklad/.cache/zig benchmark -Drelease-safe -Dconfig=production -Dtarget=native-linux -- --transfer-count 1000000
error(message_bus): error connecting to replica 0: error.ConnectionRefused
124 batches in 6.11 s
load offered = 1000000 tx/s
load accepted = 163624 tx/s
```

After:
```
λ ./scripts/benchmark.sh --transfer-count 1000000
++ uname
+ '[' Linux = Linux ']'
+ ZIG_OS=linux
+ target_set=false
+ case "$*" in
+ target_set=true
+ TARGET=
+ '[' true = false ']'
+ ZIG_EXE=./zig/zig
+ BUILD_ROOT=./
+ CACHE_ROOT=./zig-cache
+ GLOBAL_CACHE_ROOT=/home/matklad/.cache/zig
+ ./zig/zig run ./scripts/build_runner.zig -target native-linux --main-pkg-path ./ -- ./zig/zig ./ ./zig-cache /home/matklad/.cache/zig install -Drelease-safe -Dconfig=production -Dtarget=native-linux
Formatting replica 0...
Starting replica 0...

Benchmarking...
++ uname
+ '[' Linux = Linux ']'
+ ZIG_OS=linux
+ target_set=false
+ case "$*" in
+ target_set=true
+ TARGET=
+ '[' true = false ']'
+ ZIG_EXE=./zig/zig
+ BUILD_ROOT=./
+ CACHE_ROOT=./zig-cache
+ GLOBAL_CACHE_ROOT=/home/matklad/.cache/zig
+ ./zig/zig run ./scripts/build_runner.zig -target native-linux --main-pkg-path ./ -- ./zig/zig ./ ./zig-cache /home/matklad/.cache/zig benchmark -Drelease-safe -Dconfig=production -Dtarget=native-linux -- --transfer-count 1000000
124 batches in 5.86 s
load offered = 1000000 tx/s
load accepted = 170666 tx/s
```

Sanity checks as "no big regression", and this seems unlikely to affect the results much otherwise.

### CODE REVIEW

**Comment by matklad** [comment]
I need to think whether this needs messages_max bump. I think this should be handled by burst, but I am not sure

**Comment by sentientwaffle** [comment]
I don't think it needs a `messages_max` bump — the original reply can be counted as part of `client_replies_iops_write_max`.

**Comment by matklad** [comment]
But we need to copy the message, so one reply gives us two messages at some code paths?

**Comment by sentientwaffle** [comment]
:thinking: the two messages are only in the case where we are writing a reply. So I think we can consider the reply being written as "owned" by the `client_replies_iops_write_max` — it is already counted.

File: src/vsr/replica.zig [hunk 1]
```diff
@@ -5266,8 +5270,46 @@ pub fn ReplicaType(
             });
         }
 
+        fn send_reply_message_to_client(self: *Self, reply: *Message) void {
+            assert(reply.header.command == .reply);
+            assert(reply.header.view <= self.view);
+
+            // If request committed in a different view than the one it was originally submitted
+            // with, we must inform the client about this newer view before we send it a reply.
```
Comment (sentientwaffle) [inline src/vsr/replica.zig]: Nit: "originally submitted with" should be "originally prepared in". "Originally submitted" implies that what matters is when the client first sent the request, but what actually matters is when it arrived at the replica.

Also, "If _the_ request".

**Review by sentientwaffle — DISMISSED** [review]

**Review by sentientwaffle — APPROVED** [review]
