### PR TITLE
vsr: prevent state sync from breaking hash chain

### LINKED ISSUE #1532: Crash: 17270152460592452540
<strong>Commit:</strong> ```1d1182974a36ec480a79f2300a01d0eb01264283``` <br><br><strong>Branches:</strong> main<br><br><strong>Duration to run seed in ReleaseSafe mode:</strong> 3s<br><br><strong>Stack Trace:</strong><br>
```
thread panic: reached unreachable code
src/vsr/replica.zig:0:76: in valid_hash_chain_between (simulator)
src/vsr/replica.zig:5427:49: in repair (simulator)
assert(self.valid_hash_chain_between(self.op_repair_min(), self.op));

src/vsr/replica.zig:2779:24: in tick (simulator)
self.repair();

src/testing/cluster.zig:356:37: in tick (simulator)
replica.tick();

src/simulator.zig:253:23: in main (simulator)
simulator.tick();

zig/lib/std/start.zig:574:37: in posixCallMainAndExit (simulator)
const result = root.main() catch |err| {

zig/lib/std/start.zig:243:5: in _start (simulator)
asm volatile (switch (native_arch) {

???:?:?: in ??? (???)
Unwind information for `???:0x1` was not available, trace may be incomplete

debug: exit with signal: 6. Indicates a crash bug.


```
<br><strong>Debug Logs:</strong><br><details><summary>Tail</summary><br>
```debug: Replaying seed 17270152460592452540 in Debug mode with full debug logging enabled...


SEED=17270152460592452540

replicas=1
standbys=1
clients=6
request_probability=76%
idle_on_probability=14%
idle_off_probability=18%
one_way_delay_mean=8 ticks
one_way_delay_min=0 ticks
packet_loss_probability=6%
path_maximum_capacity=13 messages
path_clog_duration_mean=368 ticks
path_clog_probability=1%
packet_replay_probability=9%
partition_mode=testing.packet_simulator.PartitionMode.isolate_single
partition_symmetry=testing.packet_simulator.PartitionSymmetry.asymmetric
partition_probability=2%
unpartition_probability=9%
partition_stability=143 ticks
unpartition_stability=13 ticks
read_latency_min=0
read_latency_mean=4
write_latency_min=0
write_latency_mean=77
read_fault_probability=8%
write_fault_probability=9%
crash_probability=0.00002%
crash_stability=337 ticks
restart_probability=0.0002%
restart_stability=431 ticks
 0/ .1V0/__1/__1C0:__4Jo0/_3J!0:_31Wo <__0:__0>0Ga0G!0G?4/4Pp2/3Rq
 0/ .1V0/__2/__2C0:__5Jo0/_3J!0:_31Wo <__0:__0>0Ga0G!0G?4/4Pp2/3Rq
 0/ .1V0/__3/__3C0:__6Jo0/_3J!0:_31Wo <__0:__0>0Ga0G!0G?4/4Pp2/3Rq
 1|.1V0/__1/__3C0:__7Jo0/_7J!0:_31Wo <__0:__0>0Ga0G!0G?
 0/ .1V0/__4/__4C0:__7Jo0/_3J!0:_31Wo <__0:__0>0Ga0G!0G?4/4Pp2/3Rq
 0/ .1V0/__5/__5C0:__8Jo0/_3J!0:_31Wo <__0:__0>0Ga0G!0G?4/4Pp2/3Rq
 0/ .1V0/__6/__6C0:__9Jo0/_3J!0:_31Wo <__0:__0>0Ga0G!0G?4/4Pp2/3Rq
 0/ .1V0/__7/__7C0:_10Jo0/_3J!0:_31Wo <__0:__0>0Ga0G!0G?4/4Pp1/3Rq
 1|.1V0/__2/__6C0:__9Jo0/_3J!0:_31Wo <__0:__0>0Ga0G!0G?
 1|.1V0/__3/__6C0:__9Jo0/_3J!0:_31Wo <__0:__0>0Ga0G!0G?
 1|.1V0/__4/__6C0:__9Jo0/_3J!0:_31Wo <__0:__0>0Ga0G!0G?
 1|.1V0/__5/__6C0:__9Jo0/_3J!0:_31Wo <__0:__0>0Ga0G!0G?
 1|.1V0/__6/__6C0:__9Jo0/_3J!0:_31Wo <__0:__0>0Ga0G!0G?
 1|.1V0/__7/__7C0:__9Jo0/_3J!0:_31Wo <__0:__0>0Ga0G!0G?
 0/ .1V0/__8/__8C0:_11Jo0/_3J!0:_31Wo <__0:__0>0Ga0G!0G?4/4Pp1/3Rq
 1|.1V0/__8/__8C0:_12Jo0/_3J!0:_31Wo <__0:__0>0Ga0G!0G?
 0/ .1V0/__9/__9C0:_12Jo0/_3J!0:_31Wo <__0:__0>0Ga0G!0G?4/4Pp1/3Rq
 0/ .1V0/_10/_10C0:_13Jo0/_3J!0:_31Wo <__0:__0>0Ga0G!0G?4/4Pp0/3Rq
 0/ .1V0/_11/_11C0:_14Jo0/_3J!0:_31Wo <__0:__0>0Ga0G!0G?4/4Pp0/3Rq
 0/ .1V0/_12/_12C0:_15Jo0/_3J!0:_31Wo <__0:__0>0Ga0G!0G?4/4Pp0/3Rq
 1|.1V0/__9/_11C0:_14Jo0/_1J!0:_31Wo <__0:__0>0Ga0G!0G?
 1|.1V0/_10/_11C0:_14Jo0/_1J!0:_31Wo <__0:__0>0Ga0G!0G?
 1|.1V0/_11/_11C0:_14Jo0/_1J!0:_31Wo <__0:__0>0Ga0G!0G?
 0/ .1V0/_13/_13C0:_16Jo0/_3J!0:_31Wo <__0:__0>0Ga0G!0G?4/4Pp0/3Rq
 1|.1V0/_12/_13C0:_14Jo0/_1J!0:_31Wo <__0:__0>0Ga0G!0G?
 0/ .1V0/_14/_14C0:_16Jo0/_2J!0:_31Wo <__0:__0>0Ga0G!0G?3/4Pp0/3Rq
 0/ .1V0/_15/_15C0:_17Jo0/_2J!0:_31Wo <__0:__0>0Ga0G!0G?3/4Pp0/3Rq
 0/ .1V0/_16/_16C0:_17Jo0/_1J!0:_31Wo <__0:__0>0Ga0G!0G?2/4Pp0/3Rq
 0/ .1V0/_17/_17C0:_19Jo0/_2J!0:_31Wo <__0:__0>0Ga0G!0G?3/4Pp0/3Rq
 0/ .1V0/_18/_18C0:_21Jo0/_3J!0:_31Wo <__0:__0>0Ga0G!0G?4/4Pp0/3Rq
 0/ .1V0/_19/_19C0:_21Jo0/_2J!0:_31Wo <__0:__0>8Ga0G!0G?3/4Pp0/3Rq
 0/ .1V0/_20/_20C0:_22Jo0/_2J!0:_31Wo <__0:__0>9Ga0G!0G?3/4Pp0/3Rq
 0/ .1V0/_21/_21C0:_24Jo0/_3J!0:_31Wo <__0:__0>9Ga0G!0G?4/4Pp1/3Rq
 0/ .1V0/_22/_22C0:_25Jo0/_3J!0:_31Wo <__0:__0>9Ga0G!0G?4/4Pp1/3Rq
 0/ .1V0/_23/_23C0:_26Jo0/_3J!0:_31Wo <__0:__0>9Ga0G!0G?4/4Pp0/3Rq
 0/ .1V0/_24/_24C0:_26Jo0/_2J!0:_31Wo <__0:__0>9Ga0G!0G?3/4Pp0/3Rq
 0/ .1V0/_25/_25C0:_26Jo0/_1J!0:_31Wo <__0:__0>9Ga0G!0G?2/4Pp0/3Rq
 0/ .1V0/_26/_26C0:_26Jo0/_0J!0:_31Wo <__0:__0>9Ga0G!0G?1/4Pp0/3Rq
 0/ .1V0/_27/_27C0:_27Jo0/_0J!0:_31Wo <__0:__0>17Ga0G!0G?1/4Pp0/3Rq
 0 [ / .1V0/_27/_27C0:_27Jo0/_0J!0:_31Wo <__0:__0>17Ga0G!0G?0/4Pp0/3Rq
 0 ] / .1V23/_27/_27C0:_29Jo0/_1J!0:_31Wo <__0:__0>17Ga0G!0G?2/4Pp0/3Rq
 0/ .1V23/_28/_28C0:_29Jo0/_1J!0:_31Wo <__0:__0>17Ga0G!0G?2/4Pp0/3Rq
 0/ .1V23/_29/_29C0:_31Jo0/_2J!0:_31Wo <__0:__0>18Ga0G!0G?3/4Pp0/3Rq
 0/ .1V23/_30/_30C0:_31Jo0/_1J!0:_31Wo <__0:__0>18Ga0G!0G?2/4Pp0/3Rq
 0/ .1V23/_31/_31C2:_33Jo0/_2J!0:_31Wo <__0:__0>18Ga0G!0G?3/4Pp0/3Rq
 0/ .1V23/_32/_32C2:_33Jo0/_1J!1:_32Wo <__0:__0>18Ga0G!0G?2/4Pp0/3Rq
 0/ .1V23/_33/_33C5:_36Jo0/_3J!2:_33Wo <__0:__0>18Ga0G!0G?4/4Pp0/3Rq
 0/ .1V23/_34/_34C6:_37Jo0/_3J!3:_34Wo <__0:__0>18Ga0G!0G?4/4Pp0/3Rq
 0/ .1V23/_35/_35C7:_38Jo0/_3J!4:_35Wo <__0:__0>18Ga0G!0G?4/4Pp1/3Rq
 0/ .1V23/_36/_36C8:_39Jo0/_3J!5:_36Wo <__0:__0>18Ga0G!0G?4/4Pp0/3Rq
 0/ .1V23/_37/_37C8:_39Jo0/_2J!6:_37Wo <__0:__0>18Ga0G!0G?3/4Pp0/3Rq
 0/ .1V23/_38/_38C9:_40Jo0/_2J!7:_38Wo <__0:__0>18Ga0G!0G?3/4Pp0/3Rq
 0/ .1V23/_39/_39C10:_41Jo0/_2J!8:_39Wo <__0:__0>18Ga0G!0G?3/4Pp0/3Rq
 0/ .1V23/_40/_40C10:_41Jo0/_1J!9:_40Wo <__0:__0>18Ga0G!0G?2/4Pp0/3Rq
 0/ .1V23/_41/_41C11:_42Jo0/_1J!10:_41Wo <__0:__0>18Ga0G!0G?2/4Pp0/3Rq
 1 < ~.1V0/_12/_41C0:_31Jo0/_6J!0:_31Wo <__0:__0>0Ga0G!0G?
 0/ .1V23/_42/_42C14:_45Jo0/_3J!11:_42Wo <__0:__0>18Ga0G!0G?4/4Pp0/3Rq
 0/ .1V23/_43/_43C15:_46Jo0/_3J!12:_43Wo <__0:__0>18Ga0G!0G?4/4Pp0/3Rq
 1 > |.1V23/_23/_42C0:_31Jo0/_7J!0:_31Wo <__0:_27>nullGa0G!0G?
 0/ .1V23/_44/_44C16:_47Jo0/_3J!13:_44Wo <__0:__0>18Ga0G!0G?4/4Pp0/3Rq
 0/ .1V23/_45/_45C17:_48Jo0/_3J!14:_45Wo <__0:__0>18Ga0G!0G?4/4Pp0/3Rq
 0 $ # #
 0  / r2V23/_23/_42C15:_46Jo0/_0J!15:_46Wo <__0:__0>nullGa0G!0G?
 0/ r2V23/_24/_46C15:_46Jo0/_0J!15:_46Wo <__0:__0>17Ga0G!0G?
 0/ r2V23/_25/_46C15:_46Jo0/_0J!15:_46Wo <__0:__0>17Ga0G!0G?
 0/ r2V23/_26/_46C15:_46Jo0/_0J!15:_46Wo <__0:__0>17Ga0G!0G?
 0/ r2V23/_27/_46C15:_46Jo0/_0J!15:_46Wo <__0:__0>17Ga0G!0G?
 0/ r2V23/_28/_46C15:_46Jo0/_0J!15:_46Wo <__0:__0>17Ga0G!0G?
 0/ r2V23/_29/_46C15:_46Jo0/_0J!15:_46Wo <__0:__0>18Ga0G!0G?
 0/ r2V23/_30/_46C15:_46Jo0/_0J!15:_46Wo <__0:__0>18Ga0G!0G?
 0/ r2V23/_31/_46C15:_46Jo0/_0J!15:_46Wo <__0:__0>18Ga0G!0G?
 0/ r2V23/_32/_46C15:_46Jo0/_0J!15:_46Wo <__0:__0>18Ga0G!0G?
 0/ r2V23/_33/_46C15:_46Jo0/_0J!15:_46Wo <__0:__0>18Ga0G!0G?
 0/ r2V23/_34/_46C15:_46Jo0/_0J!15:_46Wo <__0:__0>18Ga0G!0G?
 0/ r2V23/_35/_46C15:_46Jo0/_0J!15:_46Wo <__0:__0>18Ga0G!0G?
 0/ r2V23/_36/_46C15:_46Jo0/_0J!15:_46Wo <__0:__0>18Ga0G!0G?
 0/ r2V23/_37/_46C15:_46Jo0/_0J!15:_46Wo <__0:__0>18Ga0G!0G?
 0/ r2V23/_38/_46C15:_46Jo0/_0J!15:_46Wo <__0:__0>18Ga0G!0G?
 0/ r2V23/_39/_46C15:_46Jo0/_0J!15:_46Wo <__0:__0>18Ga0G!0G?
 0/ r2V23/_40/_46C15:_46Jo0/_0J!15:_46Wo <__0:__0>18Ga0G!0G?
 0/ r2V23/_41/_46C15:_46Jo0/_0J!15:_46Wo <__0:__0>18Ga0G!0G?
 0/ r2V23/_42/_46C15:_46Jo0/_0J!15:_46Wo <__0:__0>18Ga0G!0G?
 0/ r2V23/_43/_46C15:_46Jo0/_0J!15:_46Wo <__0:__0>18Ga0G!0G?
 0/ r2V23/_44/_46C15:_46Jo0/_0J!15:_46Wo <__0:__0>18Ga0G!0G?
 0/ r2V23/_45/_46C15:_46Jo0/_0J!15:_46Wo <__0:__0>18Ga0G!0G?
 0/ r2V23/_46/_46C15:_46Jo0/_0J!15:_46Wo <__0:__0>18Ga0G!0G?
 0/ .2V23/_47/_47C16:_47Jo0/_0J!16:_47Wo <__0:__0>18Ga0G!0G?1/4Pp0/3Rq
 0/ .2V23/_48/_48C18:_49Jo0/_1J!17:_48Wo <__0:__0>18Ga0G!0G?2/4Pp0/3Rq
 0/ .2V23/_49/_49C19:_50Jo0/_1J!18:_49Wo <__0:__0>18Ga0G!0G?2/4Pp0/3Rq
 0/ .2V23/_50/_50C22:_53Jo0/_3J!19:_50Wo <__0:__0>18Ga0G!0G?4/4Pp0/3Rq
 0/ .2V23/_51/_51C23:_54Jo0/_3J!20:_51Wo <__0:__0>18Ga0G!0G?4/4Pp1/3Rq
 0 [ / .2V23/_51/_51C24:_55Jo0/_4J!20:_51Wo <__0:__0>18Ga0G!0G?4/4Pp0/3Rq
 0 ] / .2V47/_51/_51C24:_55Jo0/_3J!21:_52Wo <__0:__0>17Ga0G!0G?4/4Pp0/3Rq
 0/ .2V47/_52/_52C24:_55Jo0/_3J!21:_52Wo <__0:__0>17Ga0G!0G?4/4Pp0/3Rq
 0/ .2V47/_53/_53C25:_56Jo0/_3J!22:_53Wo <__0:__0>18Ga0G!0G?4/4Pp0/3Rq
 1 < ~.1V23/_23/_45C0:_48Jo0/11J!0:_48Wo <__0:_27>17Ga0G!0G?
 0/ .2V47/_54/_54C25:_56Jo0/_2J!23:_54Wo <__0:__0>18Ga0G!0G?3/4Pp0/3Rq
 0/ .2V47/_55/_55C25:_56Jo0/_1J!24:_55Wo <__0:__0>18Ga0G!0G?2/4Pp0/3Rq
 0/ .2V47/_56/_56C27:_58Jo0/_2J!25:_56Wo <__0:__0>18Ga0G!0G?3/4Pp0/3Rq
 0/ .2V47/_57/_57C28:_59Jo0/_2J!26:_57Wo <__0:__0>18Ga0G!0G?3/4Pp0/3Rq
 0/ .2V47/_58/_58C28:_59Jo0/_1J!27:_58Wo <__0:__0>18Ga0G!0G?2/4Pp0/3Rq
 0/ .2V47/_59/_59C28:_59Jo0/_0J!28:_59Wo <__0:__0>18Ga0G!0G?1/4Pp0/3Rq
 0/ .2V47/_60/_60C30:_61Jo0/_1J!29:_60Wo <__0:__0>18Ga0G!0G?2/4Pp0/3Rq
 0/ .2V47/_61/_61C31:_62Jo0/_1J!30:_61Wo <__0:__0>18Ga0G!0G?2/4Pp0/3Rq
 0/ .2V47/_62/_62C31:_62Jo0/_0J!31:_62Wo <__0:__0>18Ga0G!0G?1/4Pp0/3Rq
 0/ .2V47/_63/_63C34:_65Jo0/_2J!32:_63Wo <__0:__0>18Ga0G!0G?3/4Pp0/3Rq
 0/ .2V47/_64/_64C34:_65Jo0/_1J!33:_64Wo <__0:__0>18Ga0G!0G?2/4Pp0/3Rq
 0/ .2V47/_65/_65C34:_65Jo0/_0J!34:_65Wo <__0:__0>18Ga0G!0G?1/4Pp0/3Rq
 0/ .2V47/_66/_66C35:_66Jo0/_0J!35:_66Wo <__0:__0>18Ga0G!0G?1/4Pp0/3Rq
 1 > |.1V47/_47/_47C0:_48Jo0/20J!0:_48Wo <__0:_51>nullGa0G!0G?
```
</details>

### PR DESCRIPTION
**Pull request by matklad**
The added test is a minimization of https://github.com/tigerbeetle/tigerbeetle/issues/1532.

If replica state-syncs into a newer view, its log may be disconnected
from a checkpoint. To fix this, require that replica jumps view before
jumping sync target.

The effect here is that, after state sync, there's _still_ a break
between the checkpoint and the log, but, as replica is in a view_change
state, it doesn't assume valid hash chain and waits until an SV to
correct the log.

SEED: 17270152460592452540
Closes: https://github.com/tigerbeetle/tigerbeetle/issues/1532

### CODE REVIEW

File: src/vsr/replica_test.zig [hunk 1]
```diff
@@ -1138,6 +1139,83 @@ test "Cluster: sync: slightly lagging replica" {
     try expectEqual(t.replica(.R_).commit(), checkpoint_1_trigger + 3);
 }
 
+test "Cluster: sync: checkpoint from a newer view" {
+    // B1 appends (but does not commit) prepares across a checkpoint boundary.
+    // Then the cluster truncates those prepares and commits past checkpoint the trigger.
```
Comment (sentientwaffle) [inline src/vsr/replica_test.zig]: Does this mean to say "commits past the checkpoint trigger"?

File: src/vsr/replica_test.zig [hunk 2]
```diff
@@ -1138,6 +1139,83 @@ test "Cluster: sync: slightly lagging replica" {
...
+        b1.pass(.A0, .incoming, .prepare);
+        b1.filter(.A0, .incoming, struct {
+            // Force b1 to sync, rather than repair.
+            fn drop_message(message: *Message) bool {
+                switch (message.into_any()) {
+                    .prepare => |prepare| {
+                        return (prepare.header.op == checkpoint_1);
+                    },
+                    else => return false,
+                }
```
Comment (sentientwaffle) [inline src/vsr/replica_test.zig]: Could be written more succinctly as:

```suggestion
                const prepare = message.into(.prepare) orelse return false;
                return prepare.header.op == checkpoint_1;
```

File: src/vsr/replica_test.zig [hunk 3]
```diff
@@ -1138,6 +1139,83 @@ test "Cluster: sync: slightly lagging replica" {
...
+            }
+        }.drop_message);
+        try c.request(checkpoint_1_trigger + 1, checkpoint_1 - 1);
+        try expectEqual(a0.op_head(), checkpoint_1_trigger - 1);
```
Comment (sentientwaffle) [inline src/vsr/replica_test.zig]: :thinking: I was expecting a0's head to be `checkpoint_1_trigger + 1`. But I suppose with a commit-max of `checkpoint_1 - 1` and both a pipeline and batch-multiple of 4 a0 won't prepare that far ahead. But then why request it?

File: src/vsr/replica.zig [hunk 4]
```diff
@@ -8388,6 +8389,17 @@ pub fn ReplicaType(
...
+            if (candidate.view > self.view) {
+                log.debug("{}: on_{s}: jump_sync_target: ignoring, newer view" ++
+                    " (view={} candidate.view={})", .{
+                    self.replica,
+                    @tagName(header.command),
+                    self.view,
+                    candidate.view,
+                });
+                return;
+            }
```
Comment (sentientwaffle) [inline src/vsr/replica.zig:8401]: Checking if I understand how this works:

In `on_start_view()`, we will reject the SV and transition to state sync if all of the SV's headers are beyond our `prepare_max`:

```zig
            for (view_headers.slice) |*header| {
                assert(header.commit <= message.header.commit);

                if (header.op <= self.op_prepare_max()) {
                    if (self.log_view < self.view or
                        (self.log_view == self.view and header.op >= self.op))
                    {
                        self.set_op_and_commit_max(header.op, message.header.commit, @src());
                        assert(self.op == header.op);
                        assert(self.commit_max >= message.header.commit);
                        break;
                    }
                }
            } else {
                // This replica is too far behind, i.e. the new `self.op` is too far ahead of
                // the last checkpoint. If we wrap now, we overwrite un-checkpointed transfers
                // in the WAL, precluding recovery.
                if (self.syncing == .idle) {
                    log.warn("{}: on_start_view: start sync; lagging behind cluster " ++
                        "(op_prepare_max={} quorum_head={})", .{
                        self.replica,
                        self.op_prepare_max(),
                        view_headers.slice[0].op,
                    });
                    self.sync_start_from_committing();
                }
                return;
            }
```

So to advance our view (such that this new `jump_sync_target()` will not drop the message) we rely on pings or other messages that `jump_view()` uses to transition to view-change status (_not_ normal status, since we will ignore the SV that we would request).

And `jump_view()` does indeed precede `jump_sync_target()`, so that can happen with a single ping:

```zig
            self.jump_view(message.header);
            self.jump_sync_target(message.header);
```

File: src/vsr/replica_test.zig (hunk 3 above)
Comment (matklad) [reply src/vsr/replica_test.zig]: >🤔 I was expecting a0's head to be checkpoint_1_trigger + 1.

Huh, I think I expected the same, and ended up with `checkpoint_1_trigger - 1` by accident after fighting unrelated test failures. 

My thinking here is that preparing all the way to past the trigger would be a more interesting test, but, indeed, it seems we can't do that given that pipeline is not longer that batch multiple.

Simplified this to just `checkpoint_1 + 1`, this still triggers the assert.

File: src/vsr/replica.zig (hunk 4 above)
Comment (matklad) [reply src/vsr/replica.zig:8401]: Not exactly! This is related to me saying "the code already has the fix". My _original_ thinking was that, indeed, accepting SV requires to do the state sync first. But to do state sync we need to change view. And when we receive a commit we don't jump view immediately, but wait for SV, which seems to create a deadlock.

So the fix I was planing to implement here was to jump to `view_change` when we receive a checkpoint target from the next log wrap _and_ the next view. 

But, when I started coding, I realised that there's already code to do that! Right here:

https://github.com/tigerbeetle/tigerbeetle/blob/7daa0b6098c6a066ff3dd4d68ee2f35b55da6599/src/vsr/replica.zig#L1933-L1935

That is, even though we don't append any headers from an SV, we still go into view_change! And that resolves the deadlock. 

So the full sequence of events is this:

* we receive a  `.commit` with the next view & checkpoint
* when `jump_view` on this commit, we send out `.request_start_view`
* when `jump_sync_target` on this commit, we ignore the target, as it's in the future view
* sometime later, we receive the requested SV
* if we install anything from that SV, we transition to .normal in the new view and can proceed with state sync
* if we don't install anything, we trantisition to .view_change in the new view, and can still proceed with state sync (and will ask for another SV after sync is done)

Comment (sentientwaffle) [reply src/vsr/replica.zig:8401]: Ahh that makes sense, I forgot that `on_start_view` did that!

**Review by sentientwaffle — DISMISSED** [review]

File: src/vsr/replica.zig (hunk 4 above)
Comment (matklad) [reply src/vsr/replica.zig:8401]: This made merealize that there's a subtlety here! I forgot about `view_durable` and check only for `view`, but this is still correct:

when view_durable is not updated, we _can_ crash and restart into an earlier view, but that also means that we'll restart _without_ newer sync target, so it ends up ok in the end. 

Added a maybe to that effect.

**Review by sentientwaffle — APPROVED** [review]
