### PR TITLE
VOPR: Fix client-request lookup

### LINKED ISSUE #1778: Correctness: 4980538282736526628
<strong>Commit:</strong> ```cd2c8b2ebd404d41bcd43bd40daa751830966a2d``` <br><br><strong>Branches:</strong> main<br><br><strong>Duration to run seed in ReleaseSafe mode:</strong> 4s<br><br><strong>Stack Trace:</strong><br>
```
debug: exit with code: 129


```
<br><strong>Debug Logs:</strong><br><details><summary>Tail</summary><br>
```debug: Replaying seed 4980538282736526628 in Debug mode with full debug logging enabled...


SEED=4980538282736526628

replicas=2
standbys=6
clients=7
request_probability=2%
idle_on_probability=17%
idle_off_probability=19%
one_way_delay_mean=6 ticks
one_way_delay_min=1 ticks
packet_loss_probability=20%
path_maximum_capacity=12 messages
path_clog_duration_mean=7 ticks
path_clog_probability=1%
packet_replay_probability=0%
partition_mode=testing.packet_simulator.PartitionMode.none
partition_symmetry=testing.packet_simulator.PartitionSymmetry.symmetric
partition_probability=2%
unpartition_probability=6%
partition_stability=104 ticks
unpartition_stability=18 ticks
read_latency_min=0
read_latency_mean=4
write_latency_min=1
write_latency_mean=73
read_fault_probability=8%
write_fault_probability=6%
crash_probability=0.00002%
crash_stability=863 ticks
restart_probability=0.0002%
restart_stability=80 ticks
 1/.1V0/__1/__1C0:__4Jo0/_0J!0:_31Wo <__0:__0> v1:10Ga0G!0G?3/4Pp2/3Rq
 1/.1V0/__2/__2C0:__5Jo0/_1J!0:_31Wo <__0:__0> v1:10Ga0G!0G?3/4Pp1/3Rq
 1/.1V0/__3/__3C0:__6Jo0/_2J!0:_31Wo <__0:__0> v1:10Ga0G!0G?3/4Pp0/3Rq
 7|.1V0/__1/__3C0:__4Jo0/_1J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 7|.1V0/__2/__3C0:__4Jo0/_1J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 7|.1V0/__3/__3C0:__4Jo0/_1J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 0\ .1V0/__1/__3C0:__6Jo0/_2J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 2|.1V0/__1/__3C0:__4Jo0/_0J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 6|.1V0/__1/__3C0:__4Jo0/_0J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 0\ .1V0/__2/__3C0:__6Jo0/_2J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 0\ .1V0/__3/__3C0:__6Jo0/_2J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 1/.1V0/__4/__4C0:__7Jo0/_3J!0:_31Wo <__0:__0> v1:10Ga0G!0G?3/4Pp1/3Rq
 2|.1V0/__2/__3C0:__4Jo0/_0J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 2|.1V0/__3/__3C0:__4Jo0/_0J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 6|.1V0/__2/__3C0:__4Jo0/_0J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 6|.1V0/__3/__3C0:__4Jo0/_0J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 4|.1V0/__1/__3C0:__4Jo0/_0J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 4|.1V0/__2/__3C0:__4Jo0/_0J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 4|.1V0/__3/__3C0:__4Jo0/_0J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 3|.1V0/__1/__3C0:__4Jo0/_1J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 5|.1V0/__1/__3C0:__4Jo0/_0J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 3|.1V0/__2/__3C0:__4Jo0/_1J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 3|.1V0/__3/__3C0:__4Jo0/_1J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 5|.1V0/__2/__3C0:__4Jo0/_0J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 5|.1V0/__3/__3C0:__4Jo0/_0J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 0\ .1V0/__4/__4C0:__8Jo0/_4J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 4|.1V0/__4/__4C0:__4Jo0/_0J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 6|.1V0/__4/__4C0:__4Jo0/_0J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 5|.1V0/__4/__4C0:__4Jo0/_0J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 7|.1V0/__4/__4C0:__4Jo0/_1J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 2|.1V0/__4/__4C0:__4Jo0/_0J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 3|.1V0/__4/__4C0:__8Jo0/_4J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 1/.1V0/__5/__5C0:__8Jo0/_1J!0:_31Wo <__0:__0> v1:10Ga0G!0G?3/4Pp1/3Rq
 1/.1V0/__6/__6C0:__9Jo0/_2J!0:_31Wo <__0:__0> v1:10Ga0G!0G?3/4Pp0/3Rq
 0\ .1V0/__5/__5C0:__9Jo0/_1J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 0\ .1V0/__6/__6C0:_10Jo0/_2J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 3|.1V0/__5/__6C0:_10Jo0/_3J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 3|.1V0/__6/__6C0:_10Jo0/_3J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 4|.1V0/__5/__6C0:_10Jo0/_6J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 2|.1V0/__5/__6C0:_10Jo0/_5J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 2|.1V0/__6/__6C0:_10Jo0/_5J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 4|.1V0/__6/__6C0:_10Jo0/_6J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 6|.1V0/__5/__6C0:_10Jo0/_5J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 6|.1V0/__6/__6C0:_10Jo0/_5J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 1/.1V0/__7/__7C0:_10Jo0/_2J!0:_31Wo <__0:__0> v1:10Ga0G!0G?3/4Pp0/3Rq
 1/.1V0/__8/__8C0:_10Jo0/_2J!0:_31Wo <__0:__0> v1:10Ga0G!0G?2/4Pp0/3Rq
 2|.1V0/__7/__8C0:_10Jo0/_3J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 2|.1V0/__8/__8C0:_10Jo0/_3J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 3|.1V0/__7/__8C0:_10Jo0/_1J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 3|.1V0/__8/__8C0:_10Jo0/_1J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 6|.1V0/__7/__8C0:_10Jo0/_5J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 6|.1V0/__8/__8C0:_10Jo0/_5J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 0\ .1V0/__7/__8C0:_11Jo0/_2J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 0\ .1V0/__8/__8C0:_11Jo0/_2J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 4|.1V0/__7/__8C0:_11Jo0/_4J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 4|.1V0/__8/__8C0:_11Jo0/_4J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 5|.1V0/__5/__8C0:_10Jo0/_5J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 5|.1V0/__6/__8C0:_10Jo0/_5J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 5|.1V0/__7/__8C0:_10Jo0/_5J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 5|.1V0/__8/__8C0:_10Jo0/_5J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 1/.1V0/__9/__9C0:_11Jo0/_1J!0:_31Wo <__0:__0> v1:10Ga0G!0G?2/4Pp0/3Rq
 1/.1V0/_10/_10C0:_11Jo0/_1J!0:_31Wo <__0:__0> v1:10Ga0G!0G?1/4Pp0/3Rq
 5|.1V0/__9/_10C0:_10Jo0/_4J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 5|.1V0/_10/_10C0:_10Jo0/_4J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 6|.1V0/__9/_10C0:_10Jo0/_4J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 6|.1V0/_10/_10C0:_10Jo0/_4J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 2|.1V0/__9/_10C0:_10Jo0/_1J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 2|.1V0/_10/_10C0:_10Jo0/_1J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 0\ .1V0/__9/_10C0:_11Jo0/_1J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 0\ .1V0/_10/_10C0:_11Jo0/_1J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 3|.1V0/__9/_10C0:_11Jo0/_1J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 3|.1V0/_10/_10C0:_11Jo0/_1J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 4|.1V0/__9/_10C0:_12Jo0/_4J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 4|.1V0/_10/_10C0:_12Jo0/_4J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 7|.1V0/__5/_10C0:_10Jo0/_5J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 7|.1V0/__6/_10C0:_10Jo0/_5J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 7|.1V0/__7/_10C0:_12Jo0/_7J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 7|.1V0/__8/_10C0:_12Jo0/_7J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 7|.1V0/__9/_10C0:_12Jo0/_7J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 7|.1V0/_10/_10C0:_12Jo0/_7J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 1/.1V0/_11/_11C0:_13Jo0/_2J!0:_31Wo <__0:__0> v1:10Ga0G!0G?2/4Pp0/3Rq
 6|.1V0/_11/_11C0:_13Jo0/_2J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 0\ .1V0/_11/_11C0:_13Jo0/_0J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 5|.1V0/_11/_11C0:_13Jo0/_5J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 7|.1V0/_11/_11C0:_12Jo0/_4J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 3|.1V0/_11/_11C0:_13Jo0/_1J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 4|.1V0/_11/_11C0:_13Jo0/_3J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 1/.1V0/_12/_12C0:_13Jo0/_1J!0:_31Wo <__0:__0> v1:10Ga0G!0G?1/4Pp0/3Rq
 5|.1V0/_12/_12C0:_13Jo0/_5J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 3|.1V0/_12/_12C0:_13Jo0/_0J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 4|.1V0/_12/_12C0:_13Jo0/_2J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 6|.1V0/_12/_12C0:_13Jo0/_1J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 0\ .1V0/_12/_12C0:_14Jo0/_1J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 2|.1V0/_11/_12C0:_14Jo0/_4J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 7|.1V0/_12/_12C0:_14Jo0/_5J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 2|.1V0/_12/_12C0:_14Jo0/_4J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 1/.1V0/_13/_13C0:_16Jo0/_2J!0:_31Wo <__0:__0> v1:10Ga0G!0G?3/4Pp0/3Rq
 1/.1V0/_14/_14C0:_16Jo0/_2J!0:_31Wo <__0:__0> v1:10Ga0G!0G?2/4Pp0/3Rq
 2|.1V0/_13/_14C0:_15Jo0/_1J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 2|.1V0/_14/_14C0:_15Jo0/_1J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 6|.1V0/_13/_14C0:_15Jo0/_1J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 6|.1V0/_14/_14C0:_15Jo0/_1J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 4|.1V0/_13/_14C0:_15Jo0/_1J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 4|.1V0/_14/_14C0:_15Jo0/_1J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 3|.1V0/_13/_14C0:_15Jo0/_1J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 3|.1V0/_14/_14C0:_15Jo0/_1J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 7|.1V0/_13/_14C0:_15Jo0/_1J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 7|.1V0/_14/_14C0:_15Jo0/_1J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 0\ .1V0/_13/_14C0:_15Jo0/_1J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 0\ .1V0/_14/_14C0:_15Jo0/_1J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 5|.1V0/_13/_14C0:_15Jo0/_1J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 5|.1V0/_14/_14C0:_15Jo0/_1J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 1/.1V0/_15/_15C0:_16Jo0/_0J!0:_31Wo <__0:__0> v1:10Ga0G!0G?1/4Pp0/3Rq
```
</details>

### LINKED ISSUE #1780: Correctness: 8579477813168179722
<strong>Commit:</strong> ```cd2c8b2ebd404d41bcd43bd40daa751830966a2d``` <br><br><strong>Branches:</strong> main<br><br><strong>Duration to run seed in ReleaseSafe mode:</strong> 4s<br><br><strong>Stack Trace:</strong><br>
```
debug: exit with code: 129


```
<br><strong>Debug Logs:</strong><br><details><summary>Tail</summary><br>
```debug: Replaying seed 8579477813168179722 in Debug mode with full debug logging enabled...


SEED=8579477813168179722

replicas=3
standbys=5
clients=7
request_probability=2%
idle_on_probability=17%
idle_off_probability=10%
one_way_delay_mean=9 ticks
one_way_delay_min=1 ticks
packet_loss_probability=2%
path_maximum_capacity=12 messages
path_clog_duration_mean=295 ticks
path_clog_probability=0%
packet_replay_probability=3%
partition_mode=testing.packet_simulator.PartitionMode.isolate_single
partition_symmetry=testing.packet_simulator.PartitionSymmetry.symmetric
partition_probability=1%
unpartition_probability=10%
partition_stability=175 ticks
unpartition_stability=11 ticks
read_latency_min=0
read_latency_mean=8
write_latency_min=1
write_latency_mean=30
read_fault_probability=1%
write_fault_probability=6%
crash_probability=0.00002%
crash_stability=229 ticks
restart_probability=0.0002%
restart_stability=984 ticks
 1/.1V0/__1/__1C0:__4Jo0/_0J!0:_31Wo <__0:__0> v1:10Ga0G!0G?3/4Pp0/3Rq
 1/.1V0/__2/__2C0:__4Jo0/_0J!0:_31Wo <__0:__0> v1:10Ga0G!0G?2/4Pp0/3Rq
 1/.1V0/__3/__3C0:__4Jo0/_0J!0:_31Wo <__0:__0> v1:10Ga0G!0G?1/4Pp0/3Rq
 1/.1V0/__4/__4C0:__4Jo0/_0J!0:_31Wo <__0:__0> v1:10Ga0G!0G?0/4Pp0/3Rq
 2\.1V0/__1/__4C0:__4Jo0/_0J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 2\.1V0/__2/__4C0:__4Jo0/_0J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 2\.1V0/__3/__4C0:__4Jo0/_0J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 2\.1V0/__4/__4C0:__4Jo0/_0J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 5|.1V0/__1/__4C0:__4Jo0/_3J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 5|.1V0/__2/__4C0:__4Jo0/_3J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 5|.1V0/__3/__4C0:__4Jo0/_3J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 4|.1V0/__1/__4C0:__4Jo0/_2J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 4|.1V0/__2/__4C0:__4Jo0/_2J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 4|.1V0/__3/__4C0:__4Jo0/_2J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 5|.1V0/__4/__4C0:__4Jo0/_3J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 4|.1V0/__4/__4C0:__4Jo0/_2J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 0\ .1V0/__1/__4C0:__4Jo0/_0J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 0\ .1V0/__2/__4C0:__4Jo0/_0J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 0\ .1V0/__3/__4C0:__4Jo0/_0J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 0\ .1V0/__4/__4C0:__4Jo0/_0J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 3|.1V0/__1/__4C0:__7Jo0/_5J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 3|.1V0/__2/__4C0:__7Jo0/_5J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 3|.1V0/__3/__4C0:__7Jo0/_4J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 7|.1V0/__1/__4C0:__8Jo0/_6J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 3|.1V0/__4/__4C0:__7Jo0/_3J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 7|.1V0/__2/__4C0:__8Jo0/_6J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 7|.1V0/__3/__4C0:__8Jo0/_6J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 1/.1V0/__5/__5C0:__8Jo0/_1J!0:_31Wo <__0:__0> v1:10Ga0G!0G?3/4Pp0/3Rq
 1/.1V0/__6/__6C0:__8Jo0/_1J!0:_31Wo <__0:__0> v1:10Ga0G!0G?2/4Pp0/3Rq
 7|.1V0/__4/__4C0:__8Jo0/_5J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 0\ .1V0/__5/__6C0:__8Jo0/_4J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 0\ .1V0/__6/__6C0:__8Jo0/_4J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 4|.1V0/__5/__6C0:__8Jo0/_4J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 4|.1V0/__6/__6C0:__8Jo0/_4J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 3|.1V0/__5/__6C0:__7Jo0/_2J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 3|.1V0/__6/__6C0:__7Jo0/_2J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 2\.1V0/__5/__6C0:__8Jo0/_1J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 2\.1V0/__6/__6C0:__8Jo0/_1J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 1/.1V0/__7/__7C0:__9Jo0/_0J!0:_31Wo <__0:__0> v1:10Ga0G!0G?2/4Pp0/3Rq
 1/.1V0/__8/__8C0:__9Jo0/_0J!0:_31Wo <__0:__0> v1:10Ga0G!0G?1/4Pp0/3Rq
 2\.1V0/__7/__8C0:__9Jo0/_1J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 2\.1V0/__8/__8C0:__9Jo0/_1J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 4|.1V0/__7/__8C0:__9Jo0/_5J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 4|.1V0/__8/__8C0:__9Jo0/_5J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 5|.1V0/__5/__6C0:__8Jo0/_5J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 5|.1V0/__6/__6C0:__8Jo0/_5J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 0\ .1V0/__7/__8C0:__9Jo0/_3J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 0\ .1V0/__8/__8C0:__9Jo0/_3J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 6|.1V0/__1/__8C0:__9Jo0/_8J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 3|.1V0/__7/__8C0:_10Jo0/_3J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 5|.1V0/__7/__8C0:_10Jo0/_5J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 5|.1V0/__8/__8C0:_10Jo0/_5J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 6|.1V0/__2/__8C0:_10Jo0/_9J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 3|.1V0/__8/__8C0:_10Jo0/_3J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 6|.1V0/__3/__8C0:_10Jo0/_9J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 6|.1V0/__4/__8C0:_10Jo0/_9J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 6|.1V0/__5/__8C0:_10Jo0/_9J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 6|.1V0/__6/__8C0:_10Jo0/_9J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 6|.1V0/__7/__8C0:_10Jo0/_9J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 6|.1V0/__8/__8C0:_10Jo0/_9J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 1/.1V0/__9/__9C0:_10Jo0/_1J!0:_31Wo <__0:__0> v1:10Ga0G!0G?1/4Pp0/3Rq
 1/.1V0/_10/_10C0:_10Jo0/_0J!0:_31Wo <__0:__0> v1:10Ga0G!0G?0/4Pp0/3Rq
 2\.1V0/__9/_10C0:_10Jo0/_2J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 2\.1V0/_10/_10C0:_10Jo0/_2J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 5|.1V0/__9/_10C0:_10Jo0/_5J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 5|.1V0/_10/_10C0:_10Jo0/_5J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 4|.1V0/__9/_10C0:_10Jo0/_4J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 4|.1V0/_10/_10C0:_10Jo0/_4J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 0\ .1V0/__9/_10C0:_10Jo0/_0J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 0\ .1V0/_10/_10C0:_10Jo0/_0J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 3|.1V0/__9/_10C0:_10Jo0/_1J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 3|.1V0/_10/_10C0:_10Jo0/_1J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 6|.1V0/__9/_10C0:_10Jo0/_6J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 6|.1V0/_10/_10C0:_10Jo0/_6J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 1/.1V0/_11/_11C0:_12Jo0/_0J!0:_31Wo <__0:__0> v1:18Ga0G!0G?1/4Pp0/3Rq
 2\.1V0/_11/_11C0:_11Jo0/_0J!0:_31Wo <__0:__0> v1:18Ga0G!0G?
 3|.1V0/_11/_11C0:_13Jo0/_2J!0:_31Wo <__0:__0> v1:18Ga0G!0G?
 4|.1V0/_11/_11C0:_13Jo0/_3J!0:_31Wo <__0:__0> v1:18Ga0G!0G?
 6|.1V0/_11/_11C0:_13Jo0/_3J!0:_31Wo <__0:__0> v1:18Ga0G!0G?
 0\ .1V0/_11/_11C0:_13Jo0/_2J!0:_31Wo <__0:__0> v1:18Ga0G!0G?
 5|.1V0/_11/_11C0:_13Jo0/_2J!0:_31Wo <__0:__0> v1:18Ga0G!0G?
 1/.1V0/_12/_12C0:_14Jo0/_1J!0:_31Wo <__0:__0> v1:19Ga0G!0G?2/4Pp0/3Rq
 1/.1V0/_13/_13C0:_14Jo0/_1J!0:_31Wo <__0:__0> v1:19Ga0G!0G?1/4Pp0/3Rq
 4|.1V0/_12/_13C0:_14Jo0/_2J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 5|.1V0/_12/_13C0:_14Jo0/_2J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 5|.1V0/_13/_13C0:_14Jo0/_2J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 2\.1V0/_12/_13C0:_14Jo0/_0J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 2\.1V0/_13/_13C0:_14Jo0/_0J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 3|.1V0/_12/_13C0:_13Jo0/_0J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 3|.1V0/_13/_13C0:_13Jo0/_0J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 4|.1V0/_13/_13C0:_14Jo0/_1J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 0\ .1V0/_12/_13C0:_14Jo0/_2J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 0\ .1V0/_13/_13C0:_14Jo0/_2J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 6|.1V0/_12/_13C0:_14Jo0/_0J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 6|.1V0/_13/_13C0:_14Jo0/_0J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 1/.1V0/_14/_14C0:_14Jo0/_0J!0:_31Wo <__0:__0> v1:19Ga0G!0G?0/4Pp0/3Rq
 7|.1V0/__5/_13C0:_14Jo0/_6J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 7|.1V0/__6/_13C0:_14Jo0/_6J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 7|.1V0/__7/_13C0:_14Jo0/_6J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 7|.1V0/__8/_13C0:_14Jo0/_6J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 7|.1V0/__9/_13C0:_14Jo0/_5J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 0\ .1V0/_14/_14C0:_14Jo0/_1J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 6|.1V0/_14/_14C0:_14Jo0/_0J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 4|.1V0/_14/_14C0:_14Jo0/_0J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 2\.1V0/_14/_14C0:_14Jo0/_0J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 5|.1V0/_14/_14C0:_14Jo0/_1J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 7|.1V0/_10/_14C0:_14Jo0/_5J!0:_31Wo <__0:__0> v1:10Ga0G!0G?
 3|.1V0/_14/_14C0:_14Jo0/_1J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 1/.1V0/_15/_15C0:_16Jo0/_1J!0:_31Wo <__0:__0> v1:19Ga0G!0G?1/4Pp0/3Rq
 2\.1V0/_15/_15C0:_16Jo0/_0J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 7|.1V0/_11/_14C0:_14Jo0/_0J!0:_31Wo <__0:__0> v1:18Ga0G!0G?
 7|.1V0/_12/_14C0:_14Jo0/_0J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 7|.1V0/_13/_15C0:_14Jo0/_0J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 1/.1V0/_16/_16C0:_16Jo0/_1J!0:_31Wo <__0:__0> v1:19Ga0G!0G?0/4Pp0/3Rq
 2\.1V0/_16/_16C0:_17Jo0/_1J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 7|.1V0/_14/_16C0:_17Jo0/_3J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 0\ .1V0/_15/_16C0:_17Jo0/_2J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 0\ .1V0/_16/_16C0:_17Jo0/_2J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 4|.1V0/_15/_16C0:_17Jo0/_3J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 4|.1V0/_16/_16C0:_17Jo0/_3J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 6|.1V0/_15/_16C0:_17Jo0/_3J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 6|.1V0/_16/_16C0:_17Jo0/_3J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 7|.1V0/_15/_16C0:_17Jo0/_3J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 7|.1V0/_16/_16C0:_17Jo0/_3J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 1/.1V0/_17/_17C0:_18Jo0/_1J!0:_31Wo <__0:__0> v1:19Ga0G!0G?1/4Pp0/3Rq
 6|.1V0/_17/_17C0:_18Jo0/_2J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 7|.1V0/_17/_17C0:_17Jo0/_1J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 4|.1V0/_17/_17C0:_18Jo0/_1J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 2\.1V0/_17/_17C0:_18Jo0/_1J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 0\ .1V0/_17/_17C0:_18Jo0/_1J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 1/.1V0/_18/_18C0:_18Jo0/_1J!0:_31Wo <__0:__0> v1:19Ga0G!0G?0/4Pp0/3Rq
 5|.1V0/_15/_17C0:_18Jo0/_2J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 5|.1V0/_16/_17C0:_18Jo0/_2J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 5|.1V0/_17/_17C0:_18Jo0/_2J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 4|.1V0/_18/_18C0:_18Jo0/_1J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 0\ .1V0/_18/_18C0:_18Jo0/_0J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 6|.1V0/_18/_18C0:_18Jo0/_2J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 2\.1V0/_18/_18C0:_18Jo0/_0J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 7|.1V0/_18/_18C0:_18Jo0/_0J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 5|.1V0/_18/_18C0:_18Jo0/_0J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 3|.1V0/_15/_18C0:_18Jo0/_4J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 3|.1V0/_16/_18C0:_18Jo0/_1J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 3|.1V0/_17/_18C0:_18Jo0/_1J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 3|.1V0/_18/_18C0:_18Jo0/_1J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 1/.1V0/_19/_19C0:_19Jo0/_0J!0:_31Wo <__0:__0> v1:19Ga0G!0G?0/4Pp0/3Rq
 0\ .1V0/_19/_19C0:_19Jo0/_0J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 5|.1V0/_19/_19C0:_19Jo0/_1J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 2\.1V0/_19/_19C0:_19Jo0/_0J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 4|.1V0/_19/_19C0:_19Jo0/_0J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 7|.1V0/_19/_19C0:_20Jo0/_2J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 3|.1V0/_19/_19C0:_20Jo0/_2J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 1/.1V0/_20/_20C0:_20Jo0/_0J!0:_31Wo <__0:__0> v1:19Ga0G!0G?0/4Pp0/3Rq
 7|.1V0/_20/_20C0:_20Jo0/_2J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 5|.1V0/_20/_20C0:_20Jo0/_0J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 0\ .1V0/_20/_20C0:_20Jo0/_0J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 3|.1V0/_20/_20C0:_20Jo0/_2J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 2\.1V0/_20/_20C0:_20Jo0/_1J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 4|.1V0/_20/_20C0:_20Jo0/_0J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 6|.1V0/_19/_20C0:_20Jo0/_1J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 6|.1V0/_20/_20C0:_20Jo0/_1J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 1/.1V0/_21/_21C0:_21Jo0/_0J!0:_31Wo <__0:__0> v1:19Ga0G!0G?0/4Pp0/3Rq
 2\.1V0/_21/_21C0:_21Jo0/_0J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 7|.1V0/_21/_21C0:_21Jo0/_1J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 6|.1V0/_21/_21C0:_21Jo0/_1J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 4|.1V0/_21/_21C0:_21Jo0/_1J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 0\ .1V0/_21/_21C0:_21Jo0/_1J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 5|.1V0/_21/_21C0:_21Jo0/_1J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 3|.1V0/_21/_21C0:_21Jo0/_0J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 1/.1V0/_22/_22C0:_22Jo0/_0J!0:_31Wo <__0:__0> v1:19Ga0G!0G?0/4Pp0/3Rq
 7|.1V0/_22/_22C0:_22Jo0/_1J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 4|.1V0/_22/_22C0:_22Jo0/_0J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 5|.1V0/_22/_22C0:_22Jo0/_0J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 3|.1V0/_22/_22C0:_22Jo0/_1J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 2\.1V0/_22/_22C0:_22Jo0/_0J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 6|.1V0/_22/_22C0:_22Jo0/_0J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 0\ .1V0/_22/_22C0:_22Jo0/_0J!0:_31Wo <__0:__0> v1:19Ga0G!0G?
 1/.1V0/_23/_23C0:_23Jo0/_0J!0:_31Wo <__0:__0> v1:117Ga0G!0G?0/4Pp0/3Rq
```
</details>

### PR DESCRIPTION
**Pull request by sentientwaffle**
Fixes https://github.com/tigerbeetle/tigerbeetle/issues/1778
Fixes https://github.com/tigerbeetle/tigerbeetle/issues/1780

See also https://github.com/tigerbeetle/tigerbeetle/pull/1640

### CODE REVIEW

File: src/testing/cluster/state_checker.zig [hunk 1]
```diff
@@ -179,7 +179,9 @@ pub fn StateCheckerType(comptime Client: type, comptime Replica: type) type {
                     if (client.id == header_b.?.client) break client;
                 } else unreachable;
 
-                if (client.request_inflight == null) {
+                if (client.register_inflight == null and
+                    client.request_inflight == null)
```
Comment (kprotty) [inline src/testing/cluster/state_checker.zig:183]: Would you want to merge this check with the extraction of the `const request` message down below?

Comment (sentientwaffle) [reply src/testing/cluster/state_checker.zig:183]: Since `client.register_inflight` and `client.request_inflight` are different types, I don't think it would simplify things.

**Review by kprotty — APPROVED** [review]
