### PR TITLE
Reapply "vsr: liveness, nack prepares from before log view"

### LINKED ISSUE #1529: Crash: 8898210122747839118
<strong>Commit:</strong> ```5056ced0ef550823e40f94eae710db847e642cb9``` <br><br><strong>Branches:</strong> main<br><br><strong>Duration to run seed in ReleaseSafe mode:</strong> 6s<br><br><strong>Stack Trace:</strong><br>
```
thread panic: reached unreachable code
src/vsr/replica.zig:0:0: in quorum_headers (simulator)
src/vsr/replica.zig:1780:51: in on_message (simulator)
var headers = DVCQuorum.quorum_headers(

src/testing/cluster/network.zig:305:39: in deliver_message (simulator)
target_bus.on_message_callback(target_bus, target_message);

src/testing/packet_simulator.zig:395:45: in tick (simulator)
link_packet.callback(link_packet.packet, path);

src/simulator.zig:253:23: in main (simulator)
simulator.tick();

zig/lib/std/start.zig:574:37: in posixCallMainAndExit (simulator)
const result = root.main() catch |err| {

zig/lib/std/start.zig:243:5: in _start (simulator)
asm volatile (switch (native_arch) {

???:?:?: in ??? (???)
Unwind information for `???:0x1` was not available, trace may be incomplete

debug: exit with signal: 6. Indicates a crash bug.


```
<br><strong>Debug Logs:</strong><br><details><summary>Tail</summary><br>
```debug: Replaying seed 8898210122747839118 in Debug mode with full debug logging enabled...


SEED=8898210122747839118

replicas=3
standbys=6
clients=6
request_probability=44%
idle_on_probability=4%
idle_off_probability=13%
one_way_delay_mean=12 ticks
one_way_delay_min=0 ticks
packet_loss_probability=8%
path_maximum_capacity=20 messages
path_clog_duration_mean=323 ticks
path_clog_probability=1%
packet_replay_probability=9%
partition_mode=testing.packet_simulator.PartitionMode.uniform_partition
partition_symmetry=testing.packet_simulator.PartitionSymmetry.symmetric
partition_probability=2%
unpartition_probability=7%
partition_stability=153 ticks
unpartition_stability=4 ticks
read_latency_min=0
read_latency_mean=9
write_latency_min=0
write_latency_mean=38
read_fault_probability=1%
write_fault_probability=5%
crash_probability=0.00002%
crash_stability=818 ticks
restart_probability=0.0002%
restart_stability=195 ticks
 1/.1V0/__1/__1C0:__4Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?4/4Pp2/3Rq
 1/.1V0/__2/__2C0:__5Jo0/_1J!0:_31Wo <__0:__0>0Ga0G!0G?4/4Pp1/3Rq
 1/.1V0/__3/__3C0:__6Jo0/_2J!0:_31Wo <__0:__0>0Ga0G!0G?4/4Pp0/3Rq
 3|.1V0/__1/__3C0:__4Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.1V0/__2/__3C0:__4Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
 3|.1V0/__3/__3C0:__4Jo0/_0J!0:_31Wo <__0:__0>0Ga0G!0G?
```
</details>

### PR DESCRIPTION
**Pull request by matklad**
This reapplies https://github.com/tigerbeetle/tigerbeetle/pull/1528, which was reverted due to https://github.com/tigerbeetle/tigerbeetle/issues/1529. 

The crash was due to this reasoning error in the previous PR:

> log-view=v means that a replica accepted an SV
message for that view (or the replica was a
primary for that view). In any case, the starting
headers for that view were durably persisted by
the replica.
>
> So all those headers must be a part of DVC the
replica subsequently sends.

The second paragraph above is wrong: replicas used to construct a DVC from their journal, but, crucially, not all headers from an SV were added to the journal. Headers >prepare_max were skipped. 

That was corrected in #1552: now replicas guarantee that any headers from an SV would survive into a DVC, which makes  the reasoning of #1528 correct. 

On top of the revert, strengthen asserts somewhat. 

closes https://github.com/tigerbeetle/tigerbeetle/issues/1529

### CODE REVIEW

File: src/vsr/replica.zig [hunk 1]
```diff
@@ -5109,6 +5109,11 @@ pub fn ReplicaType(
                     if (self.op_checkpoint() == self.op) {
                         // Don't allow "op_repair_min > op_head".
```
Comment (matklad) [inline src/vsr/replica.zig]: This feels a bit odd --- after state sync, while we are in a recovering head state (op < op_checkpoint), we  do violate this invariant.

File: src/vsr/replica.zig [hunk 2]
```diff
@@ -5109,6 +5109,15 @@ pub fn ReplicaType(
...
                         break :op self.op_checkpoint();
+                    } else if (self.commit_min == 0) {
+                        // Prevent repair from clearing journal of all committed ops. For
+                        // op_checkpoint>0 this happens naturally: there's at least the trigger op.
```
Comment (sentientwaffle) [inline src/vsr/replica.zig]: Nit, but 
> there's at least the trigger op

isn't there at least `op_checkpoint() + 1 ... trigger`?

File: src/vsr/replica.zig [hunk 3]
```diff
@@ -5109,6 +5109,15 @@ pub fn ReplicaType(
...
+                        //
+                        // When op>0 and commit_min=0, it's important to _not_ mark faulty op=0 as
+                        // blank. Otherwise, ops>0 can all be truncated, and there won't be any ops
+                        // left at th replica.
```
Comment (sentientwaffle) [inline src/vsr/replica.zig]:
```suggestion
                        // left at the replica.
```

File: src/vsr/replica.zig (hunk 1 above)
Comment (sentientwaffle) [reply src/vsr/replica.zig]: But do we ever call `op_repair_min()` while in that state? It asserts `assert(op <= self.op);` before returning.

File: src/vsr/replica.zig [hunk 4]
```diff
@@ -8968,13 +8981,21 @@ const DVCQuorum = struct {
...
-                {
-                    // The op is nacked implicitly, because the replica has a different header.
-                    nacks += 1;
+                } else if (vsr.Headers.dvc_header_type(header) == .valid) {
+                    if (header_canonical != null and header_canonical.?.checksum != header.checksum) {
+                        // The op is nacked implicitly, because the replica has a different header.
+                        nacks += 1;
+                    }
+                    if (header_canonical == null and header.view < log_view_canonical) {
+                        assert(dvc.header.log_view < log_view_canonical);
```
Comment (sentientwaffle) [inline src/vsr/replica.zig:9022]: This assert can be copied to the `if (header_canonical != null and header_canonical.?.checksum != header.checksum) {` branch too -- if the DVC has an uncanonical header, then it must be an uncanonical DVC.

**Comment by matklad** [comment]
https://github.com/tigerbeetle/tigerbeetle/issues/1545 is a legit issue with this PR. That should be solved by

https://github.com/tigerbeetle/tigerbeetle/pull/1552

Want to land that change separately, as it makes sense in isolation as well

**Comment by matklad** [comment]
Dropped https://github.com/tigerbeetle/tigerbeetle/commit/56e315035b4039ff630e5293d3974327bc80aec6 --- now that SV headers are guaranteed to survive into DVC, I think we should no longer worry about cleaning up the slot for the root prepare for this particular issue. 

Let's see if the vopr finds anything problematic here.

**Comment by sentientwaffle** [comment]
> Let's see if the vopr finds anything problematic here.

Did you mean to re-add the `vopr` label to this PR?

**Comment by matklad** [comment]
Ah, absolutely, thanks dj!

File: src/vsr/replica.zig (hunk 4 above)
Comment (matklad) [reply src/vsr/replica.zig:9022]: Right! And, taking a second look here, `and header.view < log_view_canonical` is also an assert, rather than a condition! if we don't have a canonical header, then the header we have must be from before!

**Review by sentientwaffle — APPROVED** [review]
