### PR TITLE
vsr: preallocate reads for commits

### LINKED ISSUE #739: Crash: 17672865029551265853
<strong>Commit:</strong> ```7b34b600fcec5145a6dba898845101ace601aed6``` <br><br><strong>Branches:</strong> main<br><br><strong>Duration to run seed in ReleaseSafe mode:</strong> 4s<br><br><strong>Stack Trace:</strong><br>
```
thread panic: cannot recover corrupt prepare
src/vsr/replica.zig:2490:34: in vsr.replica.ReplicaType(state_machine.StateMachineType(testing.storage.Storage,(struct constants.StateMachineConfig constant)),testing.cluster.message_bus.MessageBus,testing.storage.Storage,testing.time.Time,testing.aof.AOF).commit_journal_next_callback (simulator)
if (self.solo()) @panic(\"cannot recover corrupt prepare\");

src/vsr/journal.zig:771:25: in vsr.journal.JournalType(vsr.replica.ReplicaType(state_machine.StateMachineType(testing.storage.Storage,(struct constants.StateMachineConfig constant)),testing.cluster.message_bus.MessageBus,testing.storage.Storage,testing.time.Time,testing.aof.AOF),testing.storage.Storage).read_prepare_with_op_and_checksum (simulator)
callback(replica, null, null);

src/testing/storage.zig:274:31: in testing.storage.Storage.tick (simulator)
next_tick.callback(next_tick);

src/testing/cluster.zig:312:59: in testing.cluster.ClusterType(state_machine.StateMachineType).tick (simulator)
for (cluster.storages) |*storage| storage.tick();

src/simulator.zig:352:31: in main (simulator)
simulator.cluster.tick();

zig/lib/std/start.zig:561:37: in std.start.posixCallMainAndExit (simulator)
const result = root.main() catch |err| {

zig/lib/std/start.zig:322:5: in std.start._start (simulator)
@call(.{ .modifier = .never_inline }, posixCallMainAndExit, .{});

debug: exit with signal: 6. Indicates a crash bug.


```
<br><strong>Debug Logs:</strong><br><details><summary>Tail</summary><br>
```debug: Replaying seed 17672865029551265853 in Debug mode with full debug logging enabled...


SEED=17672865029551265853

replicas=1
standbys=3
clients=1
request_probability=58%
idle_on_probability=6%
idle_off_probability=16%
one_way_delay_mean=10 ticks
one_way_delay_min=2 ticks
packet_loss_probability=11%
path_maximum_capacity=11 messages
path_clog_duration_mean=279 ticks
path_clog_probability=1%
packet_replay_probability=9%
partition_mode=PartitionMode.uniform_partition
partition_symmetry=PartitionSymmetry.asymmetric
partition_probability=2%
unpartition_probability=7%
partition_stability=153 ticks
unpartition_stability=12 ticks
read_latency_min=2
read_latency_mean=11
write_latency_min=2
write_latency_mean=4
read_fault_probability=4%
write_fault_probability=7%
crash_probability=0.00002%
crash_stability=84 ticks
restart_probability=0.0002%
restart_stability=589 ticks
 0/ .1V1/__1C0:__1Jo0/_0J!0:1Wo40960Gf1/4Pp0/3Pq
 3|.1V1/__1C0:__1Jo0/_0J!0:1Wo40960Gf
 0/ .1V2/__2C0:__2Jo0/_0J!0:2Wo40960Gf1/4Pp0/3Pq
 0/ .1V3/__3C0:__3Jo0/_0J!0:3Wo40960Gf1/4Pp0/3Pq
 0/ .1V4/__4C0:__4Jo0/_0J!0:4Wo40960Gf1/4Pp0/3Pq
 0/ .1V5/__5C0:__5Jo0/_0J!0:5Wo40960Gf1/4Pp0/3Pq
 1|.1V1/__4C0:__5Jo0/_3J!0:2Wo40960Gf
 1|.1V2/__4C0:__5Jo0/_3J!0:2Wo40960Gf
 1|.1V3/__4C0:__5Jo0/_0J!0:5Wo40960Gf
 1|.1V4/__4C0:__5Jo0/_0J!0:5Wo40960Gf
 1|.1V5/__5C0:__5Jo0/_0J!0:5Wo40960Gf
 2|.1V1/__5C0:__5Jo0/_3J!0:5Wo40960Gf
 2|.1V2/__5C0:__5Jo0/_2J!0:5Wo40960Gf
 2|.1V3/__5C0:__5Jo0/_2J!0:5Wo40960Gf
 2|.1V4/__5C0:__5Jo0/_2J!0:5Wo40960Gf
 2|.1V5/__5C0:__5Jo0/_2J!0:5Wo40960Gf
 0/ .1V6/__6C0:__6Jo0/_0J!0:6Wo40960Gf1/4Pp0/3Pq
 2|.1V6/__6C0:__6Jo0/_0J!0:6Wo40960Gf
 0/ .1V7/__7C0:__7Jo0/_0J!0:7Wo40960Gf1/4Pp0/3Pq
 1|.1V6/__6C0:__6Jo0/_0J!0:6Wo40960Gf
 2|.1V7/__7C0:__7Jo0/_0J!0:7Wo40960Gf
 0/ .1V8/__8C0:__8Jo0/_0J!0:8Wo40960Gf1/4Pp0/3Pq
 0/ .1V9/__9C0:__9Jo0/_0J!0:9Wo40960Gf1/4Pp0/3Pq
 2|.1V8/__8C0:__9Jo0/_1J!0:8Wo40960Gf
 0/ .1V10/_10C0:_10Jo0/_0J!0: 10Wo40960Gf1/4Pp0/3Pq
 2|.1V9/__9C0:_10Jo0/_1J!0:9Wo40960Gf
 2|.1V10/_10C0:_10Jo0/_0J!0: 10Wo40960Gf
 3|.1V2/_10C0:_10Jo0/_3J!0:7Wo40960Gf
 3|.1V3/_10C0:_10Jo0/_3J!0:7Wo40960Gf
 3|.1V4/_10C0:_10Jo0/_3J!0:7Wo40960Gf
 3|.1V5/_10C0:_10Jo0/_3J!0:7Wo40960Gf
 3|.1V6/_10C0:_10Jo0/_3J!0:7Wo40960Gf
 3|.1V7/_10C0:_10Jo0/_3J!0:7Wo40960Gf
 3|.1V8/_10C0:_10Jo0/_1J!0:9Wo40960Gf
 3|.1V9/_10C0:_10Jo0/_1J!0:9Wo40960Gf
 0/ .1V11/_11C0:_11Jo0/_0J!0: 11Wo40920Gf1/4Pp0/3Pq
 1|.1V7/_10C0:__7Jo0/_0J!0:7Wo40960Gf
 2|.1V11/_11C0:_11Jo0/_0J!0: 11Wo40920Gf
 0/ .1V12/_12C0:_12Jo0/_0J!0: 12Wo40920Gf1/4Pp0/3Pq
 2|.1V12/_12C0:_12Jo0/_0J!0: 12Wo40920Gf
 3|.1V10/_12C0:_12Jo0/_1J!0: 12Wo40960Gf
 3|.1V11/_12C0:_12Jo0/_0J!0: 12Wo40920Gf
 3|.1V12/_12C0:_12Jo0/_0J!0: 12Wo40920Gf
 0/ .1V13/_13C0:_13Jo0/_0J!0: 13Wo40920Gf1/4Pp0/3Pq
 0/ .1V14/_14C0:_14Jo0/_0J!0: 14Wo40920Gf1/4Pp0/3Pq
 0/ .1V15/_15C0:_15Jo0/_0J!0: 15Wo40920Gf1/4Pp0/3Pq
 0/ .1V16/_16C0:_16Jo0/_0J!0: 16Wo40920Gf1/4Pp0/3Pq
 0/ .1V17/_17C0:_17Jo0/_0J!0: 17Wo40920Gf1/4Pp0/3Pq
 0/ .1V18/_18C0:_18Jo0/_0J!0: 18Wo40920Gf1/4Pp0/3Pq
 0/ .1V19/_19C0:_19Jo0/_0J!0: 19Wo40920Gf1/4Pp0/3Pq
 2|.1V13/_19C0:_19Jo0/_1J!0: 19Wo40920Gf
 2|.1V14/_19C0:_19Jo0/_0J!0: 19Wo40920Gf
 2|.1V15/_19C0:_19Jo0/_0J!0: 19Wo40920Gf
 2|.1V16/_19C0:_19Jo0/_0J!0: 19Wo40920Gf
 2|.1V17/_19C0:_19Jo0/_0J!0: 19Wo40920Gf
 2|.1V18/_19C0:_19Jo0/_0J!0: 19Wo40920Gf
 2|.1V19/_19C0:_19Jo0/_0J!0: 19Wo40920Gf
 0/ .1V20/_20C0:_20Jo0/_0J!0: 20Wo40920Gf1/4Pp0/3Pq
 1|.1V8/_20C0:_20Jo0/_9J!0: 12Wo40960Gf
 1|.1V9/_20C0:_20Jo0/_9J!0: 16Wo40960Gf
 1|.1V10/_20C0:_20Jo0/_9J!0: 16Wo40960Gf
 1|.1V11/_20C0:_20Jo0/_9J!0: 16Wo40960Gf
 1|.1V12/_20C0:_20Jo0/_5J!0: 16Wo40920Gf
 1|.1V13/_20C0:_20Jo0/_2J!0: 20Wo40920Gf
 1|.1V14/_20C0:_20Jo0/_2J!0: 20Wo40920Gf
 1|.1V15/_20C0:_20Jo0/_2J!0: 20Wo40920Gf
 1|.1V16/_20C0:_20Jo0/_2J!0: 20Wo40920Gf
 1|.1V17/_20C0:_20Jo0/_2J!0: 20Wo40920Gf
 0/ .1V21/_21C0:_21Jo0/_0J!0: 21Wo40920Gf1/4Pp0/3Pq
 1|.1V18/_21C0:_21Jo0/_2J!0: 20Wo40920Gf
 1|.1V19/_21C0:_21Jo0/_1J!0: 20Wo40920Gf
 1|.1V20/_21C0:_21Jo0/_1J!0: 20Wo40920Gf
 1|.1V21/_21C0:_21Jo0/_1J!0: 20Wo40920Gf
 0/ .1V22/_22C0:_22Jo0/_0J!0: 22Wo40920Gf1/4Pp0/3Pq
 2|.1V20/_22C0:_22Jo0/_2J!0: 22Wo40920Gf
 2|.1V21/_22C0:_22Jo0/_2J!0: 22Wo40920Gf
 2|.1V22/_22C0:_22Jo0/_2J!0: 22Wo40920Gf
 3|.1V13/_22C0:_22Jo0/_1J!0: 22Wo40920Gf
 3|.1V14/_22C0:_22Jo0/_1J!0: 22Wo40920Gf
 3|.1V15/_22C0:_22Jo0/_1J!0: 22Wo40920Gf
 3|.1V16/_22C0:_22Jo0/_1J!0: 22Wo40920Gf
 3|.1V17/_22C0:_22Jo0/_1J!0: 22Wo40920Gf
 3|.1V18/_22C0:_22Jo0/_1J!0: 22Wo40920Gf
 3|.1V19/_22C0:_22Jo0/_1J!0: 22Wo40920Gf
 3|.1V20/_22C0:_22Jo0/_1J!0: 22Wo40920Gf
 0/ .1V23/_23C0:_23Jo0/_0J!0: 23Wo40920Gf1/4Pp0/3Pq
 0/ .1V24/_24C0:_24Jo0/_0J!0: 24Wo40920Gf1/4Pp0/3Pq
 2|.1V23/_23C0:_24Jo0/_1J!0: 23Wo40920Gf
 0/ .1V25/_25C0:_25Jo0/_0J!0: 25Wo40920Gf1/4Pp0/3Pq
 2|.1V24/_24C0:_25Jo0/_1J!0: 24Wo40920Gf
 2|.1V25/_25C0:_25Jo0/_1J!0: 25Wo40920Gf
 0/ .1V26/_26C0:_26Jo0/_0J!0: 26Wo40920Gf1/4Pp0/3Pq
 2|.1V26/_26C0:_26Jo0/_0J!0: 26Wo40920Gf
 0/ .1V27/_27C0:_27Jo0/_0J!0: 27Wo40920Gf1/4Pp0/3Pq
 2|.1V27/_27C0:_28Jo0/_1J!0: 27Wo40920Gf
 0/ .1V28/_28C0:_28Jo0/_0J!0: 28Wo40920Gf1/4Pp0/3Pq
 2|.1V28/_28C0:_28Jo0/_0J!0: 28Wo40920Gf
 3|.1V21/_28C0:_28Jo0/_6J!0: 22Wo40920Gf
 3|.1V22/_28C0:_28Jo0/_6J!0: 22Wo40920Gf
 0/ .1V29/_29C0:_29Jo0/_0J!0: 29Wo40920Gf1/4Pp0/3Pq
 3|.1V23/_28C0:_28Jo0/_0J!0: 28Wo40920Gf
 3|.1V24/_28C0:_28Jo0/_0J!0: 28Wo40920Gf
 3|.1V25/_28C0:_28Jo0/_0J!0: 28Wo40920Gf
 3|.1V26/_28C0:_28Jo0/_0J!0: 28Wo40920Gf
 3|.1V27/_28C0:_28Jo0/_0J!0: 28Wo40920Gf
 3|.1V28/_28C0:_28Jo0/_0J!0: 28Wo40920Gf
 2|.1V29/_29C0:_29Jo0/_0J!0: 29Wo40920Gf
 1|.1V22/_29C0:_29Jo0/_8J!0: 21Wo40920Gf
 1|.1V23/_29C0:_29Jo0/_7J!0: 25Wo40920Gf
 1|.1V24/_29C0:_29Jo0/_6J!0: 25Wo40920Gf
 1|.1V25/_29C0:_29Jo0/_6J!0: 25Wo40920Gf
 1|.1V26/_29C0:_29Jo0/_4J!0: 26Wo40920Gf
 0/ .1V30/_30C0:_30Jo0/_0J!0: 30Wo40920Gf1/4Pp0/3Pq
 2|.1V30/_30C0:_31Jo0/_1J!0: 30Wo40920Gf
 0/ .1V31/_31C0:_31Jo0/_0J!0: 31Wo40920Gf1/4Pp0/3Pq
 2|.1V31/_31C0:_32Jo0/_1J!0: 31Wo40920Gf
 0/ .1V32/_32C0:_32Jo0/_0J!0: 32Wo40920Gf1/4Pp0/3Pq
 2|.1V32/_32C0:_32Jo0/_0J!0: 32Wo40920Gf
 3|.1V29/_32C0:_32Jo0/_2J!0: 31Wo40920Gf
 3|.1V30/_32C0:_32Jo0/_2J!0: 31Wo40920Gf
 3|.1V31/_32C0:_32Jo0/_2J!0: 31Wo40920Gf
 3|.1V32/_32C0:_32Jo0/_0J!0: 32Wo40920Gf
 0/ .1V33/_33C0:_33Jo0/_0J!0: 33Wo40920Gf1/4Pp0/3Pq
 2|.1V33/_33C0:_34Jo0/_1J!0: 33Wo40920Gf
 3|.1V33/_33C0:_34Jo0/_2J!0: 32Wo40920Gf
 0/ .1V34/_34C0:_34Jo0/_0J!0: 34Wo40920Gf1/4Pp0/3Pq
 0/ .1V35/_35C0:_35Jo0/_0J!0: 35Wo40920Gf1/4Pp0/3Pq
 2|.1V34/_34C0:_34Jo0/_0J!0: 34Wo40920Gf
 3|.1V34/_35C0:_34Jo0/_0J!0: 34Wo40920Gf
 0/ .1V36/_36C0:_36Jo0/_0J!0: 36Wo40920Gf1/4Pp0/3Pq
 0/ .1V37/_37C0:_37Jo0/_0J!0: 37Wo40920Gf1/4Pp0/3Pq
 0/ .1V38/_38C0:_38Jo0/_0J!0: 38Wo40920Gf1/4Pp0/3Pq
 0/ .1V39/_39C0:_39Jo0/_0J!0: 39Wo40890Gf1/4Pp0/3Pq
 0/ .1V40/_40C0:_40Jo0/_0J!0: 40Wo40890Gf1/4Pp0/3Pq
 0/ .1V41/_41C0:_41Jo0/_0J!0: 41Wo40890Gf1/4Pp0/3Pq
 0/ .1V42/_42C0:_42Jo0/_0J!0: 42Wo40890Gf1/4Pp0/3Pq
 0/ .1V43/_43C0:_43Jo0/_0J!0: 43Wo40835Gf1/4Pp0/3Pq
 0/ .1V44/_44C0:_44Jo0/_0J!0: 44Wo40835Gf1/4Pp0/3Pq
 0/ .1V45/_45C0:_45Jo0/_0J!0: 45Wo40835Gf1/4Pp0/3Pq
 0/ .1V46/_46C0:_46Jo0/_0J!0: 46Wo40835Gf1/4Pp0/3Pq
 0/ .1V47/_47C0:_47Jo0/_0J!0: 47Wo40835Gf1/4Pp0/3Pq
 0/ .1V48/_48C0:_48Jo0/_0J!0: 48Wo40835Gf1/4Pp0/3Pq
 3|.1V35/_48C0:_48Jo0/_7J!0: 47Wo40920Gf
 3|.1V36/_48C0:_48Jo0/_7J!0: 47Wo40920Gf
 3|.1V37/_48C0:_48Jo0/_5J!0: 47Wo40920Gf
 3|.1V38/_48C0:_48Jo0/_1J!0: 47Wo40920Gf
 3|.1V39/_48C0:_48Jo0/_1J!0: 47Wo40920Gf
 3|.1V40/_48C0:_48Jo0/_0J!0: 48Wo40890Gf
 3|.1V41/_48C0:_48Jo0/_0J!0: 48Wo40890Gf
 3|.1V42/_48C0:_48Jo0/_0J!0: 48Wo40890Gf
 3|.1V43/_48C0:_48Jo0/_0J!0: 48Wo40835Gf
 3|.1V44/_48C0:_48Jo0/_0J!0: 48Wo40835Gf
 3|.1V45/_48C0:_48Jo0/_0J!0: 48Wo40835Gf
 3|.1V46/_48C0:_48Jo0/_0J!0: 48Wo40835Gf
 3|.1V47/_48C0:_48Jo0/_0J!0: 48Wo40835Gf
 3|.1V48/_48C0:_48Jo0/_0J!0: 48Wo40835Gf
 1|.1V27/_48C0:_48Jo0/19J!0: 38Wo40920Gf
 1|.1V28/_48C0:_48Jo0/12J!0: 38Wo40920Gf
 0/ .1V49/_49C0:_49Jo0/_0J!0: 49Wo40835Gf1/4Pp0/3Pq
 1|.1V29/_48C0:_48Jo0/10J!0: 44Wo40920Gf
 1|.1V30/_48C0:_48Jo0/10J!0: 44Wo40920Gf
 1|.1V31/_48C0:_48Jo0/10J!0: 44Wo40920Gf
 1|.1V32/_48C0:_48Jo0/_9J!0: 44Wo40920Gf
 1|.1V33/_48C0:_48Jo0/_9J!0: 44Wo40920Gf
 1|.1V34/_48C0:_48Jo0/_8J!0: 44Wo40920Gf
 1|.1V35/_48C0:_48Jo0/_8J!0: 44Wo40920Gf
 1|.1V36/_48C0:_48Jo0/_8J!0: 44Wo40920Gf
 1|.1V37/_49C0:_49Jo0/_3J!0: 48Wo40920Gf
 1|.1V38/_49C0:_49Jo0/_1J!0: 48Wo40920Gf
 1|.1V39/_49C0:_49Jo0/_1J!0: 48Wo40890Gf
 1|.1V40/_49C0:_49Jo0/_1J!0: 48Wo40890Gf
 1|.1V41/_49C0:_49Jo0/_1J!0: 48Wo40890Gf
 1|.1V42/_49C0:_49Jo0/_1J!0: 48Wo40890Gf
 1|.1V43/_49C0:_49Jo0/_1J!0: 48Wo40835Gf
 0/ .1V50/_50C0:_50Jo0/_0J!0: 50Wo40835Gf1/4Pp0/3Pq
 1|.1V44/_49C0:_49Jo0/_1J!0: 48Wo40835Gf
 1|.1V45/_49C0:_49Jo0/_1J!0: 48Wo40835Gf
 1|.1V46/_49C0:_49Jo0/_1J!0: 48Wo40835Gf
 1|.1V47/_49C0:_49Jo0/_1J!0: 48Wo40835Gf
 1|.1V48/_49C0:_49Jo0/_1J!0: 48Wo40835Gf
 1|.1V49/_50C0:_50Jo0/_1J!0: 49Wo40835Gf
 3|.1V49/_50C0:_50Jo0/_2J!0: 48Wo40835Gf
 3|.1V50/_50C0:_50Jo0/_2J!0: 48Wo40835Gf
 1|.1V50/_50C0:_50Jo0/_1J!0: 49Wo40835Gf
 0/ .1V51/_51C0:_51Jo0/_0J!0: 51Wo40805Gf1/4Pp0/3Pq
 0/ .1V52/_52C0:_52Jo0/_0J!0: 52Wo40805Gf1/4Pp0/3Pq
 0/ .1V53/_53C0:_53Jo0/_0J!0: 53Wo40805Gf1/4Pp0/3Pq
 0/ .1V54/_54C0:_54Jo0/_0J!0: 54Wo40805Gf1/4Pp0/3Pq
 0/ .1V55/_55C0:_55Jo0/_0J!0: 55Wo40745Gf1/4Pp0/3Pq
 0/ .1V56/_56C0:_56Jo0/_0J!0: 56Wo40745Gf1/4Pp0/3Pq
 1|.1V51/_56C0:_56Jo0/_2J!0: 54Wo40805Gf
 1|.1V52/_56C0:_56Jo0/_2J!0: 54Wo40805Gf
 1|.1V53/_56C0:_56Jo0/_2J!0: 54Wo40805Gf
 1|.1V54/_56C0:_56Jo0/_2J!0: 54Wo40805Gf
 1|.1V55/_56C0:_56Jo0/_1J!0: 55Wo40745Gf
 1|.1V56/_56C0:_56Jo0/_1J!0: 56Wo40745Gf
 0/ .1V57/_57C0:_57Jo0/_0J!0: 57Wo40745Gf1/4Pp0/3Pq
 0/ .1V58/_58C0:_58Jo0/_0J!0: 58Wo40745Gf1/4Pp0/3Pq
 0/ .1V59/_59C0:_59Jo0/_0J!0: 59Wo40715Gf1/4Pp0/3Pq
 0/ .1V60/_60C0:_60Jo0/_0J!0: 60Wo40715Gf1/4Pp0/3Pq
 0/ .1V61/_61C0:_61Jo0/_0J!0: 61Wo40715Gf1/4Pp0/3Pq
 0/ .1V62/_62C0:_62Jo0/_0J!0: 62Wo40715Gf1/4Pp0/3Pq
 0/ .1V63/_63C0:_63Jo0/_0J!0: 63Wo40655Gf1/4Pp0/3Pq
 0 [ / .1V63/_63C0:_63Jo0/_0J!0: 63Wo40655Gf0/4Pp0/3Pq
 0 ] / .1V63/_63C0:_63Jo0/_0J!0: 63Wo40796Gf0/4Pp0/3Pq
 0/ .1V64/_64C1:_64Jo0/_0J!1: 64Wo40796Gf1/4Pp0/3Pq
 3|.1V51/_64C0:_63Jo0/_9J!0: 62Wo40805Gf
 3|.1V52/_64C0:_63Jo0/_8J!0: 62Wo40805Gf
 3|.1V53/_64C0:_63Jo0/_8J!0: 62Wo40805Gf
 3|.1V54/_64C0:_63Jo0/_8J!0: 62Wo40805Gf
 3|.1V55/_64C0:_63Jo0/_8J!0: 62Wo40745Gf
 0/ .1V65/_65C2:_65Jo0/_0J!2: 65Wo40792Gf1/4Pp0/3Pq
 0/ .1V66/_66C3:_66Jo0/_0J!3: 66Wo40776Gf1/4Pp0/3Pq
 0/ .1V67/_67C4:_67Jo0/_0J!4: 67Wo40776Gf1/4Pp0/3Pq
 0/ .1V68/_68C5:_68Jo0/_0J!5: 68Wo40776Gf1/4Pp0/3Pq
 0/ .1V69/_69C6:_69Jo0/_0J!6: 69Wo40776Gf1/4Pp0/3Pq
 3|.1V56/_69C0:_63Jo0/_1J!0: 63Wo40745Gf
 3|.1V57/_69C0:_63Jo0/_1J!0: 63Wo40745Gf
 3|.1V58/_69C0:_63Jo0/_0J!0: 63Wo40745Gf
 3|.1V59/_69C0:_63Jo0/_0J!0: 63Wo40715Gf
 3|.1V60/_69C0:_63Jo0/_0J!0: 63Wo40715Gf
 3|.1V61/_69C0:_63Jo0/_0J!0: 63Wo40715Gf
 3|.1V62/_69C0:_63Jo0/_0J!0: 63Wo40715Gf
 3|.1V63/_69C0:_63Jo0/_0J!0: 63Wo40655Gf
 3 [ |.1V63/_69C0:_63Jo0/_0J!0: 63Wo40655Gf
 3 ] |.1V63/_69C0:_63Jo0/_0J!0: 63Wo40796Gf
 1|.1V57/_69C0:_63Jo0/_4J!0: 59Wo40745Gf
 1|.1V58/_69C0:_63Jo0/_4J!0: 59Wo40745Gf
 1|.1V59/_69C0:_63Jo0/_4J!0: 59Wo40715Gf
 2|.1V35/_69C0:_63Jo0/13J!0: 63Wo40920Gf
 2|.1V36/_69C0:_63Jo0/_4J!0: 63Wo40920Gf
 2|.1V37/_69C0:_63Jo0/_3J!0: 63Wo40920Gf
 2|.1V38/_69C0:_63Jo0/_3J!0: 63Wo40920Gf
 2|.1V39/_69C0:_63Jo0/_2J!0: 63Wo40890Gf
 2|.1V40/_69C0:_63Jo0/_1J!0: 63Wo40890Gf
 2|.1V41/_69C0:_63Jo0/_0J!0: 63Wo40890Gf
 0/ .1V70/_70C7:_70Jo0/_0J!7: 70Wo40776Gf1/4Pp0/3Pq
 2|.1V42/_69C0:_63Jo0/_0J!0: 63Wo40890Gf
 2|.1V43/_69C0:_63Jo0/_0J!0: 63Wo40835Gf
 2|.1V44/_69C0:_63Jo0/_0J!0: 63Wo40835Gf
 2|.1V45/_69C0:_63Jo0/_0J!0: 63Wo40835Gf
 2|.1V46/_69C0:_63Jo0/_0J!0: 63Wo40835Gf
 2|.1V47/_70C0:_63Jo0/_0J!0: 63Wo40835Gf
 2|.1V48/_70C0:_63Jo0/_0J!0: 63Wo40835Gf
 0/ .1V71/_71C8:_71Jo0/_0J!8: 71Wo40746Gf1/4Pp0/3Pq
 2|.1V49/_71C0:_63Jo0/_0J!0: 63Wo40835Gf
 2|.1V50/_71C0:_63Jo0/_0J!0: 63Wo40835Gf
 2|.1V51/_71C0:_63Jo0/_0J!0: 63Wo40805Gf
 0/ .1V72/_72C9:_72Jo0/_0J!9: 72Wo40746Gf1/4Pp0/3Pq
 2|.1V52/_71C0:_63Jo0/_0J!0: 63Wo40805Gf
 2|.1V53/_71C0:_63Jo0/_0J!0: 63Wo40805Gf
 2|.1V54/_71C0:_63Jo0/_0J!0: 63Wo40805Gf
 2|.1V55/_71C0:_63Jo0/_0J!0: 63Wo40748Gf
 2|.1V56/_71C0:_63Jo0/_0J!0: 63Wo40745Gf
 2|.1V57/_72C0:_63Jo0/_0J!0: 63Wo40745Gf
 2|.1V58/_72C0:_63Jo0/_0J!0: 63Wo40745Gf
 2|.1V59/_72C0:_63Jo0/_0J!0: 63Wo40715Gf
 2|.1V60/_72C0:_63Jo0/_0J!0: 63Wo40715Gf
 2|.1V61/_72C0:_63Jo0/_0J!0: 63Wo40715Gf
 2|.1V62/_72C0:_63Jo0/_0J!0: 63Wo40715Gf
 2|.1V63/_72C0:_63Jo0/_0J!0: 63Wo40655Gf
 2 [ |.1V63/_72C0:_63Jo0/_0J!0: 63Wo40655Gf
 2 ] |.1V63/_72C0:_63Jo0/_0J!0: 63Wo40796Gf
 0/ .1V73/_73C10:_73Jo0/_0J!10: 73Wo40746Gf1/4Pp0/3Pq
 1|.1V60/_73C0:_63Jo0/_1J!0: 63Wo40715Gf
 1|.1V61/_73C0:_63Jo0/_1J!0: 63Wo40715Gf
 1|.1V62/_73C0:_63Jo0/_0J!0: 63Wo40715Gf
 1|.1V63/_73C0:_63Jo0/_0J!0: 63Wo40655Gf
 1 [ |.1V63/_73C0:_63Jo0/_0J!0: 63Wo40655Gf
 1 ] |.1V63/_73C0:_63Jo0/_0J!0: 63Wo40796Gf
 0 $ # #
 0  / r2V59/_69C10:_73Jo0/_0J!10: 73Wo40796Gf
 0/ r2V60/_73C10:_73Jo0/_0J!10: 73Wo40796Gf
 0/ r2V61/_73C10:_73Jo0/_0J!10: 73Wo40796Gf
 0/ r2V62/_73C10:_73Jo0/_0J!10: 73Wo40796Gf
 0/ r2V63/_73C10:_73Jo0/_0J!10: 73Wo40796Gf
 0/ r2V64/_73C10:_73Jo0/_0J!10: 73Wo40796Gf
 0/ r2V65/_73C10:_73Jo0/_0J!10: 73Wo40792Gf
 0/ r2V66/_73C10:_73Jo0/_0J!10: 73Wo40776Gf
 0/ r2V67/_73C10:_73Jo0/_0J!10: 73Wo40776Gf
 0/ r2V68/_73C10:_73Jo0/_0J!10: 73Wo40776Gf
 0/ r2V69/_73C10:_73Jo0/_0J!10: 73Wo40776Gf
 0/ r2V70/_73C10:_73Jo0/_0J!10: 73Wo40776Gf
 0/ r2V71/_73C10:_73Jo0/_0J!10: 73Wo40755Gf
 2|.1V64/_73C10:_73Jo0/_8J!1: 73Wo40796Gf
```
</details>

### PR DESCRIPTION
**Pull request by matklad**
There are two reasons to read prepares from the journal:

* commit path via `commit_journal_next` and `primary_repair_pipeline`
* repair path via `on_request_prepare`

Previously, the two paths shared read IOPS, so repair might actually starve commit (in a situation with a sole replica and a bunch of standbys, that actually triggered an erroneous panic, see the VOPR seed).

Now, we reserve one IOP for commit path, so that it can always proceed normally.

SEED: 17672865029551265853
Closes: #739

## Pre-merge checklist

Performance:

* [X] I am very sure this PR could not affect performance.

### CODE REVIEW

File: src/vsr/journal.zig [hunk 1]
```diff
@@ -225,6 +225,17 @@ pub fn JournalType(comptime Replica: type, comptime Storage: type) type {
...
+        /// Count of reads currently acquired on the repair path.
+        reads_repair_count: u6 = 0,
+        /// Limit on the number of repair reads.
+        /// This keeps at least one commit read available, so that an assymetrically
+        /// partitioned replica cannot starve the cluster with request_prepare messages.
+        reads_repair_count_max: u6 = constants.journal_iops_read_max - 1,
+        /// Count of reads currently acquired on the commit path.
+        reads_commit_count: u6 = 0,
+        /// We need at most one read on the commit path, so this is used only for asserting.
+        reads_commit_count_max: u6 = 1,
```
Comment (sentientwaffle) [inline src/vsr/journal.zig]: Maybe the `_max` values should be file-level constants? (not `constants.zig`)

File: src/vsr/journal.zig [hunk 2]
```diff
@@ -706,6 +717,9 @@ pub fn JournalType(comptime Replica: type, comptime Storage: type) type {
         ) void {
             assert(journal.status == .recovered);
             assert(checksum != 0);
+            if (destination_replica == null) {
+                assert(journal.reads.available() > 0);
```
Comment (sentientwaffle) [inline src/vsr/journal.zig:724]: Or maybe `journal.reads.available() >= reads_commit_count_max`? Effectively the same thing, but I think it a little more self-explanatory.

File: src/vsr/journal.zig [hunk 3]
```diff
@@ -766,11 +783,21 @@ pub fn JournalType(comptime Replica: type, comptime Storage: type) type {
...
+                    callback(replica, null, null);
+                    return;
+                }
+                journal.reads_repair_count += 1;
+            }
+
+            assert(journal.reads_repair_count <= journal.reads_repair_count_max);
+            assert(journal.reads_commit_count <= journal.reads_commit_count_max);
+
+            const read = journal.reads.acquire() orelse unreachable;
```
Comment (sentientwaffle) [inline src/vsr/journal.zig]: Is `orelse unreachable` instead of `acquire().?` to draw attention to its unreachable-ness?

**Comment by sentientwaffle** [comment]
Interesting, it looks like `assert(journal.reads_commit_count <= journal.reads_commit_count_max);` is triggered in the Cluster tests: https://github.com/tigerbeetledb/tigerbeetle/actions/runs/4833199625/jobs/8612910133?pr=740

**Comment by matklad** [comment]
>Interesting, it looks like assert(journal.reads_commit_count <= journal.reads_commit_count_max); is triggered in the Cluster tests: https://github.com/tigerbeetledb/tigerbeetle/actions/runs/4833199625/jobs/8612910133?pr=740

Yeah, see the second commit. This actually a pre-existing perf issue -- we release the read in defer, _after_ we invoke callback, so the callback doesn't get as much available iops as we can give to it.

File: src/vsr/journal.zig (hunk 2 above)
Comment (matklad) [reply src/vsr/journal.zig:724]: should be

```
assert(journal.reads.available() >= reads_commit_count_max - reads_commit_count);
```

right?

Comment (sentientwaffle) [reply src/vsr/journal.zig:724]: I think it is the latter outside of `destination_replica == null`, or it is the former inside. I think I prefer your version, to avoid the if block.

File: src/vsr/journal.zig (hunk 3 above)
Comment (matklad) [reply src/vsr/journal.zig]: Heh, I actually wrote `.?` originally, but then it occured to me to check if there are other places where we branch on read IOP availability (as it seems nice to eliminate those), and all those places used `orelse unreachable`. But one wirte is using `.?`, and we use `.?` elsewhere, so that's what I am normalizing this to

Comment (sentientwaffle) [reply src/vsr/journal.zig]: `orelse unreachable` was probably past-me not remembering that `.?` exists. :sweat_smile:

**Review by sentientwaffle — DISMISSED** [review]

File: src/vsr/journal.zig (hunk 2 above)
Comment (matklad) [reply src/vsr/journal.zig:724]: Hm, I think we are on different pages so far. I think this is what is fully explicit here: 

```
            if (destination_replica == null) {
                assert(journal.reads.available() >=
                    reads_commit_count_max - journal.reads_commit_count);
            }
```

"If we are on the commit path, we have enough commit reads available sans already in-progress commit"

The `journal.reads.available() >= reads_commit_count_max` version would be wrong I think? You might spend `< reads_commit_count_max` reads.

Now that I look at it, I think I like 

```
            if (destination_replica == null) {
                assert(journal.reads.available() > 0);
```

most actually


We are not asserting that the count is precise (there are other assertions for that). Rather we assert that a commit path cant' be dropped due to lack of iops. Will switch back to that

Comment (sentientwaffle) [reply src/vsr/journal.zig:724]: > Will switch back to that

:+1: Yeah I've confused myself sufficiently that the original is probably simpler.

Agreed that my version was wrong.
But just for my understanding:

> "If we are on the commit path, we have enough commit reads available sans already in-progress commit"

In that version, if `reads.available() == 0` and `reads_commit_count_max == 1` and `journal.reads_commit_count == 1` (there is already a commit in progress) then the assertion would succeed. Which is not what we want?

**Review by sentientwaffle — APPROVED** [review]

File: src/vsr/journal.zig (hunk 2 above)
Comment (matklad) [reply src/vsr/journal.zig:724]: > Which is not what we want?

Yes. There are two things we might want to assert: 

* that the counts are right -- we have at least max - count reads available (this is true 
 for both the commit and the repair path)
* that we have a spare read (this is true for commit path, but not for repair path)


```
                assert(journal.reads.available() >=
                    reads_commit_count_max - journal.reads_commit_count);
```

is the assert for the frist point, the `> 0` is for the second point. 

Now that I think about it, the appropriate generalization would actually be

```
assert(journal.reads_commit_count < reads_commit_count_max)
```

but `available > 0` still feels like a harder to confuse thing.

Comment (sentientwaffle) [reply src/vsr/journal.zig:724]: Makes sense, thanks!
