### PR TITLE
VSR/Journal: Carefully truncate out-of-view prepares during recovery

### LINKED ISSUE #783: Crash: 14295907088955483715
<strong>Commit:</strong> ```fd94fadf804e6ce612372106093d168fe128e6d7``` <br><br><strong>Branches:</strong> main<br><br><strong>Duration to run seed in ReleaseSafe mode:</strong> 8s<br><br><strong>Stack Trace:</strong><br>
```
thread panic: reached unreachable code
src/simulator.zig:0:0: in Simulator.tick (simulator)
src/simulator.zig:243:23: in main (simulator)
simulator.tick();

zig/lib/std/start.zig:561:37: in std.start.posixCallMainAndExit (simulator)
const result = root.main() catch |err| {

zig/lib/std/start.zig:322:5: in std.start._start (simulator)
@call(.{ .modifier = .never_inline }, posixCallMainAndExit, .{});

debug: exit with signal: 6. Indicates a crash bug.


```
<br><strong>Debug Logs:</strong><br><details><summary>Tail</summary><br>
```debug: Replaying seed 14295907088955483715 in Debug mode with full debug logging enabled...


SEED=14295907088955483715

replicas=3
standbys=3
clients=1
request_probability=64%
idle_on_probability=1%
idle_off_probability=10%
one_way_delay_mean=4 ticks
one_way_delay_min=1 ticks
packet_loss_probability=16%
path_maximum_capacity=4 messages
path_clog_duration_mean=341 ticks
path_clog_probability=1%
packet_replay_probability=40%
partition_mode=PartitionMode.uniform_partition
partition_symmetry=PartitionSymmetry.symmetric
partition_probability=1%
unpartition_probability=3%
partition_stability=156 ticks
unpartition_stability=6 ticks
read_latency_min=2
read_latency_mean=3
write_latency_min=0
write_latency_mean=99
read_fault_probability=8%
write_fault_probability=6%
crash_probability=0.00002%
crash_stability=160 ticks
restart_probability=0.0002%
restart_stability=539 ticks
 2/.8V1/__1C0:__1Jo0/_0J!0:1Wo45056Gf1/4Pp0/3Pq
 0\ .8V1/__1C0:__1Jo0/_0J!0:1Wo45056Gf
 4|.8V1/__1C0:__1Jo0/_0J!0:1Wo45056Gf
 5|.8V1/__1C0:__1Jo0/_0J!0:1Wo45056Gf
 1\.8V1/__1C0:__1Jo0/_0J!0:1Wo45056Gf
 3|.8V1/__1C0:__1Jo0/_0J!0:1Wo45056Gf
 2/.8V2/__2C0:__2Jo0/_0J!0:2Wo45056Gf1/4Pp0/3Pq
 1\.8V2/__2C0:__3Jo0/_2J!0:1Wo45056Gf
 4|.8V2/__2C0:__3Jo0/_2J!0:1Wo45056Gf
 0\ .8V2/__2C0:__2Jo0/_0J!0:2Wo45056Gf
 5|.8V2/__2C0:__3Jo0/_2J!0:1Wo45056Gf
 2/.8V3/__3C0:__3Jo0/_0J!0:3Wo45056Gf1/4Pp0/3Pq
 0\ .8V3/__3C0:__3Jo0/_0J!0:3Wo45056Gf
 1\.8V3/__3C0:__3Jo0/_0J!0:3Wo45056Gf
 4|.8V3/__3C0:__3Jo0/_0J!0:3Wo45056Gf
 5|.8V3/__3C0:__3Jo0/_0J!0:3Wo45056Gf
 3|.8V2/__3C0:__3Jo0/_2J!0:2Wo45056Gf
 3|.8V3/__3C0:__3Jo0/_1J!0:2Wo45056Gf
 2/.8V4/__4C0:__4Jo0/_1J!0:4Wo45056Gf1/4Pp0/3Pq
 0\ .8V4/__4C0:__4Jo0/_0J!0:4Wo45056Gf
 1\.8V4/__4C0:__5Jo0/_1J!0:4Wo45056Gf
 2/.8V5/__5C0:__5Jo0/_0J!0:5Wo45056Gf1/4Pp0/3Pq
 1\.8V5/__5C0:__5Jo0/_0J!0:5Wo45056Gf
 0\ .8V5/__5C0:__6Jo0/_2J!0:4Wo45056Gf
 3|.8V4/__4C0:__5Jo0/_2J!0:4Wo45056Gf
 2/.8V6/__6C0:__6Jo0/_0J!0:6Wo45056Gf1/4Pp0/3Pq
 0\ .8V6/__6C0:__6Jo0/_1J!0:6Wo45056Gf
 3|.8V5/__6C0:__5Jo0/_1J!0:4Wo45056Gf
 5|.8V4/__4C0:__5Jo0/_1J!0:5Wo45056Gf
 4|.8V4/__6C0:__6Jo0/_2J!0:5Wo45056Gf
 4|.8V5/__6C0:__6Jo0/_2J!0:5Wo45056Gf
 1\.8V6/__6C0:__6Jo0/_1J!0:5Wo45056Gf
 5|.8V5/__6C0:__6Jo0/_2J!0:5Wo45056Gf
 4|.8V6/__6C0:__6Jo0/_1J!0:6Wo45056Gf
 5|.8V6/__6C0:__6Jo0/_1J!0:5Wo45056Gf
 3|.8V6/__6C0:__6Jo0/_1J!0:6Wo45056Gf
 2/.8V7/__7C0:__7Jo0/_0J!0:7Wo45026Gf1/4Pp0/3Pq
 3|.8V7/__7C0:__7Jo0/_1J!0:6Wo45026Gf
 4|.8V7/__7C0:__7Jo0/_0J!0:7Wo45026Gf
 1\.8V7/__7C0:__7Jo0/_0J!0:7Wo45026Gf
 5|.8V7/__7C0:__7Jo0/_0J!0:7Wo45026Gf
 0/ v9V7/__7C0:__7Jo0/_0J!0:7Wo45026Gf
 1/.16V8/__8C0:__8Jo0/_0J!0:8Wo45016Gf1/4Pp0/3Pq
 0\ .16V8/__8C0:__8Jo0/_0J!0:8Wo45016Gf
 5|.16V8/__8C0:__9Jo0/_1J!0:8Wo45016Gf
 2\.16V8/__8C0:__9Jo0/_1J!0:8Wo45016Gf
 4|.16V8/__8C0:__8Jo0/_0J!0:8Wo45016Gf
 1/.16V9/__9C0:__9Jo0/_0J!0:9Wo45016Gf1/4Pp0/3Pq
 2\.16V9/__9C0:__9Jo0/_0J!0:9Wo45016Gf
 5|.16V9/__9C0:__9Jo0/_0J!0:9Wo45016Gf
 0\ .16V9/__9C0:__9Jo0/_0J!0:9Wo45016Gf
 4|.16V9/__9C0:_10Jo0/_2J!0:8Wo45016Gf
 3|.16V8/__9C0:__9Jo0/_2J!0:7Wo45016Gf
 3|.16V9/__9C0:__9Jo0/_2J!0:7Wo45016Gf
 2/.17V10/_10C0:_10Jo0/_0J!0: 10Wo45016Gf1/4Pp0/3Pq
 1\.17V10/_10C0:_10Jo0/_0J!0: 10Wo45016Gf
 5|.17V10/_10C0:_10Jo0/_1J!0:9Wo45016Gf
 4|.17V10/_10C0:_10Jo0/_0J!0: 10Wo45016Gf
 2/.17V11/_11C0:_11Jo0/_0J!0: 11Wo45016Gf1/4Pp0/3Pq
 0\ .17V10/_11C0:_12Jo0/_1J!0: 12Wo45016Gf
 0\ .17V11/_11C0:_12Jo0/_1J!0: 12Wo45016Gf
 3|.17V10/_11C0:_12Jo0/_2J!0: 12Wo45016Gf
 2/.17V12/_12C0:_12Jo0/_0J!0: 12Wo45016Gf1/4Pp0/3Pq
 0\ .17V12/_12C0:_12Jo0/_0J!0: 12Wo45016Gf
 3|.17V11/_12C0:_12Jo0/_1J!0: 12Wo45016Gf
 3|.17V12/_12C0:_12Jo0/_1J!0: 12Wo45016Gf
 1\.17V11/_12C0:_12Jo0/_1J!0: 12Wo45016Gf
 1\.17V12/_12C0:_12Jo0/_1J!0: 12Wo45016Gf
 4|.17V11/_12C0:_12Jo0/_1J!0: 12Wo45016Gf
 4|.17V12/_12C0:_12Jo0/_1J!0: 12Wo45016Gf
 5|.17V11/_12C0:_12Jo0/_1J!0: 12Wo45016Gf
 5|.17V12/_12C0:_12Jo0/_1J!0: 12Wo45016Gf
 2/.20V13/_13C0:_13Jo0/_0J!0: 13Wo45016Gf1/4Pp0/3Pq
 0\ .20V13/_13C0:_13Jo0/_0J!0: 13Wo45016Gf
 1/v22V13/_13C0:_14Jo0/_1J!0: 13Wo45016Gf
 5|.24V13/_13C0:_14Jo0/_1J!0: 13Wo45016Gf
 4|.24V13/_13C0:_14Jo0/_2J!0: 12Wo45016Gf
 3|.24V13/_13C0:_14Jo0/_2J!0: 12Wo45016Gf
 0/ .30V14/_14C0:_14Jo0/_0J!0: 14Wo45016Gf1/4Pp0/3Pq
 2\.30V14/_14C0:_14Jo0/_0J!0: 14Wo45016Gf
 1\.30V14/_14C0:_14Jo0/_0J!0: 14Wo45016Gf
 5|.30V14/_14C0:_14Jo0/_1J!0: 13Wo45016Gf
 3|.30V14/_14C0:_14Jo0/_0J!0: 14Wo45016Gf
 4|.32V14/_14C0:_14Jo0/_0J!0: 14Wo45016Gf
 2/.32V15/_15C0:_15Jo0/_0J!0: 15Wo45016Gf1/4Pp0/3Pq
 0\ .32V15/_15C0:_15Jo0/_0J!0: 15Wo45016Gf
 1\.32V15/_15C0:_15Jo0/_0J!0: 15Wo45016Gf
 3|.32V15/_15C0:_15Jo0/_1J!0: 14Wo45016Gf
 5|.32V15/_15C0:_15Jo0/_1J!0: 15Wo45016Gf
 4|.32V15/_15C0:_16Jo0/_2J!0: 14Wo45016Gf
 2/.32V16/_16C0:_16Jo0/_0J!0: 16Wo45016Gf1/4Pp0/3Pq
 0\ .32V16/_16C0:_16Jo0/_0J!0: 16Wo45016Gf
 3|.32V16/_16C0:_16Jo0/_1J!0: 15Wo45016Gf
 4|.32V16/_16C0:_16Jo0/_0J!0: 16Wo45016Gf
 1\.32V16/_16C0:_16Jo0/_1J!0: 15Wo45016Gf
 2/.32V17/_17C0:_17Jo0/_0J!0: 17Wo45016Gf1/4Pp0/3Pq
 0\ .32V17/_17C0:_17Jo0/_0J!0: 17Wo45016Gf
 4|.32V17/_17C0:_18Jo0/_2J!0: 16Wo45016Gf
 1\.32V17/_17C0:_18Jo0/_2J!0: 16Wo45016Gf
 5|.32V16/_17C0:_18Jo0/_3J!0: 15Wo45016Gf
 2/.32V18/_18C0:_18Jo0/_0J!0: 18Wo45016Gf1/4Pp0/3Pq
 4|.32V18/_18C0:_18Jo0/_0J!0: 18Wo45016Gf
 1\.32V18/_18C0:_18Jo0/_0J!0: 18Wo45016Gf
 0\ .32V18/_18C0:_18Jo0/_0J!0: 18Wo45016Gf
 2/.32V19/_19C0:_19Jo0/_0J!0: 19Wo45016Gf1/4Pp0/3Pq
 1\.32V19/_19C0:_19Jo0/_0J!0: 19Wo45016Gf
 0\ .32V19/_19C0:_19Jo0/_0J!0: 19Wo45016Gf
 5|.32V17/_19C0:_18Jo0/_2J!0: 18Wo45016Gf
 5|.32V18/_19C0:_19Jo0/_1J!0: 18Wo45016Gf
 3|.32V17/_19C0:_19Jo0/_2J!0: 19Wo45016Gf
 3|.32V18/_19C0:_19Jo0/_2J!0: 19Wo45016Gf
 3|.32V19/_19C0:_19Jo0/_2J!0: 19Wo45016Gf
 5|.32V19/_19C0:_19Jo0/_1J!0: 18Wo45016Gf
 4|.32V19/_19C0:_19Jo0/_1J!0: 18Wo45016Gf
 2/.32V20/_20C0:_20Jo0/_0J!0: 20Wo45016Gf1/4Pp0/3Pq
 5|.32V20/_20C0:_20Jo0/_1J!0: 19Wo45016Gf
 1\.32V20/_20C0:_21Jo0/_1J!0: 20Wo45016Gf
 4|.32V20/_20C0:_21Jo0/_2J!0: 19Wo45016Gf
 2/.32V21/_21C0:_21Jo0/_0J!0: 21Wo45016Gf1/4Pp0/3Pq
 4|.32V21/_21C0:_21Jo0/_2J!0: 21Wo45016Gf
 3|.32V20/_21C0:_21Jo0/_2J!0: 20Wo45016Gf
 3|.32V21/_21C0:_21Jo0/_2J!0: 20Wo45016Gf
 1\.32V21/_21C0:_21Jo0/_0J!0: 21Wo45016Gf
 0\ .32V20/_21C0:_22Jo0/_3J!0: 19Wo45016Gf
 0\ .32V21/_21C0:_22Jo0/_3J!0: 19Wo45016Gf
 2/.32V22/_22C0:_22Jo0/_0J!0: 22Wo45016Gf1/4Pp0/3Pq
 1\.32V22/_22C0:_22Jo0/_1J!0: 21Wo45016Gf
 0\ .32V22/_22C0:_22Jo0/_0J!0: 22Wo45016Gf
 3|.32V22/_22C0:_22Jo0/_1J!0: 21Wo45016Gf
 4|.32V22/_22C0:_23Jo0/_2J!0: 21Wo45016Gf
 5|.32V21/_22C0:_23Jo0/_2J!0: 21Wo45016Gf
 5|.32V22/_22C0:_23Jo0/_2J!0: 21Wo45016Gf
 0/ .51V23/_23C0:_23Jo0/_0J!0: 23Wo45016Gf1/4Pp0/3Pq
 5|.51V23/_23C0:_23Jo0/_0J!0: 23Wo45016Gf
 3|.51V23/_23C0:_23Jo0/_0J!0: 23Wo45016Gf
 1\.51V23/_23C0:_23Jo0/_0J!0: 23Wo45016Gf
 4|.51V23/_23C0:_23Jo0/_0J!0: 23Wo45016Gf
 2/v53V23/_23C0:_23Jo0/_0J!0: 23Wo45016Gf
 1/.61V24/_24C0:_24Jo0/_0J!0: 24Wo45016Gf1/4Pp0/3Pq
 4|.61V24/_24C0:_24Jo0/_0J!0: 24Wo45016Gf
 0\ .61V24/_24C0:_24Jo0/_0J!0: 24Wo45016Gf
 5|.61V24/_24C0:_24Jo0/_0J!0: 24Wo45016Gf
 3|.61V24/_24C0:_24Jo0/_0J!0: 24Wo45016Gf
 2\.61V24/_24C0:_24Jo0/_0J!0: 24Wo45016Gf
 1/.61V25/_25C0:_25Jo0/_0J!0: 25Wo45016Gf1/4Pp0/3Pq
 2\.61V25/_25C0:_25Jo0/_0J!0: 25Wo45016Gf
 3|.61V25/_25C0:_25Jo0/_0J!0: 25Wo45016Gf
 0\ .61V25/_25C0:_25Jo0/_0J!0: 25Wo45016Gf
 5|.61V25/_25C0:_25Jo0/_0J!0: 25Wo45016Gf
 4|.61V25/_25C0:_25Jo0/_0J!0: 25Wo45016Gf
 1/.61V26/_26C0:_26Jo0/_0J!0: 26Wo45016Gf1/4Pp0/3Pq
 5|.61V26/_26C0:_26Jo0/_1J!0: 26Wo45016Gf
 0\ .61V26/_26C0:_26Jo0/_0J!0: 26Wo45016Gf
 4|.61V26/_26C0:_26Jo0/_0J!0: 26Wo45016Gf
 3|.61V26/_26C0:_26Jo0/_1J!0: 26Wo45016Gf
 1/.61V27/_27C0:_27Jo0/_0J!0: 27Wo45016Gf1/4Pp0/3Pq
 4|.61V27/_27C0:_27Jo0/_0J!0: 27Wo45016Gf
 0\ .61V27/_27C0:_27Jo0/_0J!0: 27Wo45016Gf
 3|.61V27/_27C0:_28Jo0/_2J!0: 26Wo45016Gf
 2\.61V26/_27C0:_28Jo0/_2J!0: 26Wo45016Gf
 2\.61V27/_27C0:_28Jo0/_2J!0: 28Wo45016Gf
 5|.61V27/_27C0:_28Jo0/_2J!0: 26Wo45016Gf
 1/.61V28/_28C0:_28Jo0/_0J!0: 28Wo45016Gf1/4Pp0/3Pq
 3|.61V28/_28C0:_28Jo0/_0J!0: 28Wo45016Gf
 4|.61V28/_28C0:_28Jo0/_1J!0: 28Wo45016Gf
 0\ .61V28/_28C0:_28Jo0/_0J!0: 28Wo45016Gf
 5|.61V28/_28C0:_28Jo0/_1J!0: 27Wo45016Gf
 2\.61V28/_28C0:_28Jo0/_0J!0: 28Wo45016Gf
 1/.61V29/_29C0:_29Jo0/_0J!0: 29Wo45016Gf1/4Pp0/3Pq
 0\ .61V29/_29C0:_29Jo0/_0J!0: 29Wo45016Gf
 2\.61V29/_29C0:_29Jo0/_0J!0: 29Wo45016Gf
 4|.61V29/_29C0:_30Jo0/_1J!0: 30Wo45016Gf
 3|.61V29/_29C0:_30Jo0/_2J!0: 28Wo45016Gf
 1/.64V30/_30C0:_30Jo0/_0J!0: 30Wo45016Gf1/4Pp0/3Pq
 2\.64V30/_30C0:_30Jo0/_0J!0: 30Wo45016Gf
 0\ .64V30/_30C0:_30Jo0/_0J!0: 30Wo45016Gf
 5|.64V29/_29C0:_30Jo0/_1J!0: 30Wo45016Gf
 4|.64V30/_30C0:_30Jo0/_0J!0: 30Wo45016Gf
 1/.64V31/_31C0:_31Jo0/_0J!0: 31Wo45016Gf1/4Pp0/3Pq
 2\.64V31/_31C0:_31Jo0/_0J!0: 31Wo45016Gf
 3|.64V30/_31C0:_31Jo0/_1J!0: 30Wo45016Gf
 0\ .64V31/_31C0:_32Jo0/_2J!0: 30Wo45016Gf
 3|.64V31/_31C0:_31Jo0/_1J!0: 31Wo45016Gf
 4|.64V31/_31C0:_32Jo0/_2J!0: 30Wo45016Gf
 5|.67V30/_31C0:_32Jo0/_2J!0: 30Wo45016Gf
 5|.67V31/_31C0:_32Jo0/_2J!0: 32Wo45016Gf
 0/ .72V32/_32C0:_32Jo0/_0J!0: 32Wo45016Gf1/4Pp0/3Pq
 1\.72V32/_32C0:_32Jo0/_0J!0: 32Wo45016Gf
 3|.72V32/_32C0:_32Jo0/_0J!0: 32Wo45016Gf
 2\.72V32/_32C0:_32Jo0/_0J!0: 32Wo45016Gf
 4|.72V32/_32C0:_32Jo0/_0J!0: 32Wo45016Gf
 5|.72V32/_32C0:_32Jo0/_0J!0: 32Wo45016Gf
 0/ .72V33/_33C0:_33Jo0/_0J!0: 33Wo45016Gf1/4Pp0/3Pq
 3|.72V33/_33C0:_33Jo0/_0J!0: 33Wo45016Gf
 2\.72V33/_33C0:_33Jo0/_0J!0: 33Wo45016Gf
 1\.72V33/_33C0:_33Jo0/_0J!0: 33Wo45016Gf
 4|.72V33/_33C0:_34Jo0/_2J!0: 33Wo45016Gf
 5|.72V33/_33C0:_34Jo0/_2J!0: 34Wo45016Gf
 0/ .75V34/_34C0:_34Jo0/_0J!0: 34Wo45016Gf1/4Pp0/3Pq
 1\.75V34/_34C0:_34Jo0/_0J!0: 34Wo45016Gf
 5|.75V34/_34C0:_34Jo0/_0J!0: 34Wo45016Gf
 4|.75V34/_34C0:_34Jo0/_0J!0: 34Wo45016Gf
 2\.75V34/_34C0:_34Jo0/_0J!0: 34Wo45016Gf
 3|.75V34/_34C0:_34Jo0/_1J!0: 33Wo45016Gf
 0/ .78V35/_35C0:_35Jo0/_0J!0: 35Wo45016Gf1/4Pp0/3Pq
 2\.78V35/_35C0:_35Jo0/_0J!0: 35Wo45016Gf
 3|.78V35/_35C0:_36Jo0/_1J!0: 35Wo45016Gf
 1\.78V35/_35C0:_36Jo0/_1J!0: 35Wo45016Gf
 5|.78V35/_35C0:_36Jo0/_1J!0: 35Wo45016Gf
 0/ .78V36/_36C0:_36Jo0/_0J!0: 36Wo45016Gf1/4Pp0/3Pq
 1\.78V36/_36C0:_36Jo0/_0J!0: 36Wo45016Gf
 2\.78V36/_36C0:_36Jo0/_0J!0: 36Wo45016Gf
 3|.78V36/_36C0:_36Jo0/_1J!0: 36Wo45016Gf
 4|.78V35/_36C0:_36Jo0/_1J!0: 36Wo45016Gf
 4|.78V36/_36C0:_36Jo0/_1J!0: 36Wo45016Gf
 5|.78V36/_36C0:_36Jo0/_1J!0: 35Wo45016Gf
 0/ .78V37/_37C0:_37Jo0/_0J!0: 37Wo45016Gf1/4Pp0/3Pq
 2\.78V37/_37C0:_37Jo0/_0J!0: 37Wo45016Gf
 1\.78V37/_37C0:_37Jo0/_0J!0: 37Wo45016Gf
 0/ .78V38/_38C0:_38Jo0/_0J!0: 38Wo45016Gf1/4Pp0/3Pq
 1\.78V38/_38C0:_38Jo0/_0J!0: 38Wo45016Gf
 5|.78V37/_38C0:_38Jo0/_2J!0: 37Wo45016Gf
 4|.78V37/_38C0:_38Jo0/_2J!0: 38Wo45016Gf
 4|.78V38/_38C0:_38Jo0/_2J!0: 38Wo45016Gf
 5|.78V38/_38C0:_38Jo0/_1J!0: 37Wo45016Gf
 3|.78V37/_38C0:_39Jo0/_3J!0: 36Wo45016Gf
 3|.79V38/_38C0:_38Jo0/_1J!0: 39Wo45016Gf
 2\.79V38/_38C0:_39Jo0/_1J!0: 39Wo45016Gf
 1/.79V39/_39C0:_39Jo0/_0J!0: 39Wo45016Gf1/4Pp0/3Pq
 0\ .79V39/_39C0:_39Jo0/_0J!0: 39Wo45016Gf
 4|.79V39/_39C0:_40Jo0/_2J!0: 38Wo45016Gf
 1/.79V40/_40C0:_40Jo0/_0J!0: 40Wo45016Gf1/4Pp0/3Pq
 2\.79V39/_39C0:_40Jo0/_1J!0: 39Wo45016Gf
 4|.79V40/_40C0:_40Jo0/_0J!0: 40Wo45016Gf
 2\.79V40/_40C0:_40Jo0/_1J!0: 39Wo45016Gf
 5|.79V39/_40C0:_40Jo0/_1J!0: 40Wo45016Gf
 5|.79V40/_40C0:_40Jo0/_1J!0: 40Wo45016Gf
 0/ v81V40/_40C0:_41Jo0/_1J!0: 40Wo45016Gf
 1/.82V41/_41C0:_41Jo0/_0J!0: 41Wo45016Gf1/4Pp0/3Pq
 0\ .82V41/_41C0:_41Jo0/_0J!0: 41Wo45016Gf
 3|.82V39/_41C0:_42Jo0/_3J!0: 41Wo45016Gf
 4|.82V41/_41C0:_41Jo0/_1J!0: 41Wo45016Gf
 1/.82V42/_42C0:_42Jo0/_0J!0: 42Wo45016Gf1/4Pp0/3Pq
 5|.82V41/_41C0:_41Jo0/_1J!0: 40Wo45016Gf
 4|.82V42/_42C0:_42Jo0/_0J!0: 42Wo45016Gf
 5|.82V42/_42C0:_42Jo0/_1J!0: 41Wo45016Gf
 2/v83V41/_41C0:_42Jo0/_1J!0: 41Wo45016Gf
 0/ v84V42/_42C0:_42Jo0/_0J!0: 42Wo45016Gf
 3|.82V40/_42C0:_42Jo0/_2J!0: 42Wo45016Gf
 3|.82V41/_42C0:_42Jo0/_2J!0: 42Wo45016Gf
 3|.82V42/_42C0:_42Jo0/_2J!0: 42Wo45016Gf
 2/v86V42/_42C0:_42Jo0/_0J!0: 42Wo45016Gf
 0/ .96V43/_43C0:_43Jo0/_0J!0: 43Wo44977Gf1/4Pp0/3Pq
 2/v98V43/_43C0:_43Jo0/_0J!0: 43Wo44977Gf
 1\.98V43/_43C0:_43Jo0/_0J!0: 43Wo44977Gf
 3|.98V43/_43C0:_43Jo0/_1J!0: 42Wo44977Gf
 4|.98V43/_43C0:_43Jo0/_0J!0: 43Wo44977Gf
 5|.98V43/_43C0:_43Jo0/_1J!0: 42Wo44977Gf
 2/.98V44/_44C0:_44Jo0/_0J!0: 44Wo44967Gf1/4Pp0/3Pq
 1\.98V44/_44C0:_44Jo0/_0J!0: 44Wo44967Gf
 0\ .98V44/_44C0:_44Jo0/_0J!0: 44Wo44967Gf
 3|.98V44/_44C0:_44Jo0/_1J!0: 44Wo44967Gf
 5|.98V44/_44C0:_44Jo0/_1J!0: 43Wo44967Gf
 4|.98V44/_44C0:_44Jo0/_1J!0: 43Wo44967Gf
 0/ .99V45/_45C0:_45Jo0/_0J!0: 45Wo44967Gf1/4Pp0/3Pq
 1\.99V45/_45C0:_45Jo0/_0J!0: 45Wo44967Gf
 3|.99V45/_45C0:_45Jo0/_0J!0: 45Wo44967Gf
 2\.99V45/_45C0:_45Jo0/_0J!0: 45Wo44967Gf
 4|.99V45/_45C0:_45Jo0/_1J!0: 45Wo44967Gf
 0/ .99V46/_46C0:_46Jo0/_0J!0: 46Wo44967Gf1/4Pp0/3Pq
 5|.99V45/_46C0:_46Jo0/_2J!0: 44Wo44967Gf
 1\.99V46/_46C0:_46Jo0/_0J!0: 46Wo44967Gf
 2\.99V46/_46C0:_46Jo0/_0J!0: 46Wo44967Gf
 3|.99V46/_46C0:_46Jo0/_0J!0: 46Wo44967Gf
 5|.99V46/_46C0:_46Jo0/_1J!0: 45Wo44967Gf
 0/ .99V47/_47C0:_47Jo0/_0J!0: 47Wo44928Gf1/4Pp0/3Pq
 2\.99V47/_47C0:_47Jo0/_0J!0: 47Wo44928Gf
 4|.99V46/_46C0:_46Jo0/_1J!0: 46Wo44967Gf
 0/ .99V48/_48C0:_48Jo0/_0J!0: 48Wo44928Gf1/4Pp0/3Pq
 4|.99V47/_47C0:_48Jo0/_2J!0: 46Wo44928Gf
 3|.99V47/_48C0:_48Jo0/_1J!0: 48Wo44928Gf
 3|.99V48/_48C0:_48Jo0/_1J!0: 48Wo44928Gf
 1\.99V47/_48C0:_48Jo0/_1J!0: 48Wo44928Gf
 1\.99V48/_48C0:_48Jo0/_1J!0: 48Wo44928Gf
 2\.99V48/_48C0:_48Jo0/_0J!0: 48Wo44928Gf
 4|.99V48/_48C0:_48Jo0/_0J!0: 48Wo44928Gf
 1/.103V49/_49C0:_49Jo0/_0J!0: 49Wo44928Gf1/4Pp0/3Pq
 3|.103V49/_49C0:_49Jo0/_1J!0: 48Wo44928Gf
 0\ .103V49/_49C0:_49Jo0/_0J!0: 49Wo44928Gf
 2\.103V49/_49C0:_49Jo0/_0J!0: 49Wo44928Gf
 5|.103V47/_49C0:_50Jo0/_2J!0: 50Wo44928Gf
 5|.103V48/_49C0:_50Jo0/_2J!0: 50Wo44928Gf
 5|.103V49/_49C0:_50Jo0/_2J!0: 50Wo44928Gf
 4|.104V49/_49C0:_50Jo0/_1J!0: 49Wo44928Gf
 0/ .114V50/_50C0:_50Jo0/_0J!0: 50Wo44928Gf1/4Pp0/3Pq
 4|.114V50/_50C0:_50Jo0/_0J!0: 50Wo44928Gf
 2\.114V50/_50C0:_50Jo0/_0J!0: 50Wo44928Gf
 3|.114V50/_50C0:_50Jo0/_0J!0: 50Wo44928Gf
 5|.114V50/_50C0:_50Jo0/_0J!0: 50Wo44928Gf
 1\.114V50/_50C0:_50Jo0/_0J!0: 50Wo44928Gf
 0/ .114V51/_51C0:_51Jo0/_0J!0: 51Wo44889Gf1/4Pp0/3Pq
 2/v116V51/_51C0:_51Jo0/_1J!0: 51Wo44889Gf
 1/v118V51/_51C0:_52Jo0/_1J!0: 51Wo44889Gf
 3|.119V51/_51C0:_52Jo0/_2J!0: 50Wo44889Gf
 5|.119V51/_51C0:_52Jo0/_1J!0: 52Wo44889Gf
 4|.119V51/_51C0:_52Jo0/_2J!0: 50Wo44889Gf
 3 $ ##
 1/.139V52/_52C0:_52Jo0/_0J!0: 52Wo44889Gf1/4Pp0/3Pq
 0\ .139V52/_52C0:_52Jo0/_0J!0: 52Wo44889Gf
 5|.139V52/_52C0:_52Jo0/_0J!0: 52Wo44889Gf
 4|.139V52/_52C0:_52Jo0/_0J!0: 52Wo44889Gf
 2\.139V52/_52C0:_52Jo0/_0J!0: 52Wo44889Gf
 2/.140V53/_53C0:_53Jo0/_0J!0: 53Wo44889Gf1/4Pp0/3Pq
 0\ .140V53/_53C0:_53Jo0/_0J!0: 53Wo44889Gf
 1\.140V53/_53C0:_53Jo0/_0J!0: 53Wo44889Gf
 5|.140V53/_53C0:_54Jo0/_2J!0: 52Wo44889Gf
 4|.145V53/_53C0:_54Jo0/_2J!0: 52Wo44889Gf
 2/.146V54/_54C0:_54Jo0/_0J!0: 54Wo44889Gf1/4Pp0/3Pq
 0\ .146V54/_54C0:_54Jo0/_0J!0: 54Wo44889Gf
 4|.146V54/_54C0:_54Jo0/_0J!0: 54Wo44889Gf
 1\.146V54/_54C0:_54Jo0/_0J!0: 54Wo44889Gf
 5|.146V54/_54C0:_55Jo0/_1J!0: 54Wo44889Gf
 2/.146V55/_55C0:_55Jo0/_0J!0: 55Wo44889Gf1/4Pp0/3Pq
 0\ .146V55/_55C0:_55Jo0/_0J!0: 55Wo44889Gf
 5|.146V55/_55C0:_55Jo0/_0J!0: 55Wo44889Gf
 1\.146V55/_55C0:_55Jo0/_0J!0: 55Wo44889Gf
 4|.146V55/_55C0:_56Jo0/_2J!0: 54Wo44889Gf
 1/.148V56/_56C0:_56Jo0/_0J!0: 56Wo44889Gf1/4Pp0/3Pq
 5|.148V56/_56C0:_56Jo0/_0J!0: 56Wo44889Gf
 4|.151V56/_56C0:_56Jo0/_0J!0: 56Wo44889Gf
 0/ v153V56/_56C0:_56Jo0/_0J!0: 56Wo44889Gf
 2\.154V56/_56C0:_57Jo0/_1J!0: 56Wo44889Gf
 1/.157V57/_57C0:_57Jo0/_0J!0: 57Wo44889Gf1/4Pp0/3Pq
 5|.157V57/_57C0:_57Jo0/_0J!0: 57Wo44889Gf
 4|.158V57/_57C0:_57Jo0/_1J!0: 56Wo44889Gf
 0/ .159V57/_57C0:_57Jo0/_0J!0: 57Wo44889Gf1/4Pp0/3Pq
 0/ .159V58/_58C0:_58Jo0/_0J!0: 58Wo44889Gf1/4Pp0/3Pq
 1\.159V58/_58C0:_58Jo0/_0J!0: 58Wo44889Gf
 1/.160V59/_59C0:_59Jo0/_0J!0: 59Wo44844Gf1/4Pp0/3Pq
 0\ .160V59/_59C0:_59Jo0/_0J!0: 59Wo44844Gf
 4|.160V58/_58C0:_59Jo0/_2J!0: 57Wo44889Gf
 2\.160V57/_59C0:_60Jo0/_3J!0: 57Wo44889Gf
 2\.160V58/_59C0:_60Jo0/_3J!0: 57Wo44889Gf
 4|.160V59/_59C0:_59Jo0/_1J!0: 58Wo44844Gf
 1/.160V60/_60C0:_60Jo0/_0J!0: 60Wo44844Gf1/4Pp0/3Pq
 0\ .160V60/_60C0:_60Jo0/_0J!0: 60Wo44844Gf
 1/.160V61/_61C0:_61Jo0/_0J!0: 61Wo44844Gf1/4Pp0/3Pq
 2\.160V59/_60C0:_61Jo0/_2J!0: 60Wo44844Gf
 2\.160V60/_60C0:_61Jo0/_2J!0: 60Wo44844Gf
 0\ .160V61/_61C0:_61Jo0/_0J!0: 61Wo44844Gf
 2\.160V61/_61C0:_61Jo0/_2J!0: 60Wo44844Gf
 4|.160V60/_61C0:_62Jo0/_3J!0: 61Wo44844Gf
 4|.160V61/_61C0:_62Jo0/_3J!0: 61Wo44844Gf
 0/ .162V62/_62C0:_62Jo0/_0J!0: 62Wo44844Gf1/4Pp0/3Pq
 1\.162V62/_62C0:_62Jo0/_0J!0: 62Wo44844Gf
 4|.162V62/_62C0:_62Jo0/_0J!0: 62Wo44844Gf
 2\.162V62/_62C0:_62Jo0/_0J!0: 62Wo44844Gf
 5|.162V58/_62C0:_62Jo0/_5J!0: 57Wo44889Gf
 5|.162V59/_62C0:_62Jo0/_5J!0: 57Wo44889Gf
 5|.162V60/_62C0:_62Jo0/_0J!0: 62Wo44844Gf
 5|.162V61/_62C0:_62Jo0/_0J!0: 62Wo44844Gf
 5|.162V62/_62C0:_62Jo0/_0J!0: 62Wo44844Gf
 0/ .162V63/_63C0:_63Jo0/_0J!0: 63Wo44805Gf1/4Pp0/3Pq
 0 [ / .162V63/_63C0:_63Jo0/_0J!0: 63Wo44805Gf0/4Pp0/3Pq
 2\.162V63/_63C0:_63Jo0/_1J!0: 63Wo44805Gf
 2 [ \.162V63/_63C0:_63Jo0/_1J!0: 63Wo44805Gf
 1\.162V63/_63C0:_63Jo0/_0J!0: 63Wo44805Gf
 1 [ \.162V63/_63C0:_63Jo0/_0J!0: 63Wo44805Gf
 5|.162V63/_63C0:_63Jo0/_0J!0: 63Wo44805Gf
 5 [ |.162V63/_63C0:_63Jo0/_0J!0: 63Wo44805Gf
 4|.162V63/_63C0:_63Jo0/_1J!0: 62Wo44805Gf
 4 [ |.162V63/_63C0:_63Jo0/_1J!0: 62Wo44805Gf
 2 ] \.162V63/_63C0:_63Jo0/_0J!0: 63Wo44886Gf
 1 ] \.162V63/_63C0:_63Jo0/_0J!0: 63Wo44886Gf
 0 ] / .162V63/_63C0:_63Jo0/_0J!0: 63Wo44886Gf0/4Pp0/3Pq
 5 ] |.162V63/_63C0:_63Jo0/_0J!0: 63Wo44886Gf
 4 ] |.162V63/_63C0:_63Jo0/_0J!0: 63Wo44886Gf
 2/.164V64/_64C1:_64Jo0/_0J!1: 64Wo44886Gf1/4Pp0/3Pq
 4|.164V64/_64C1:_64Jo0/_0J!1: 64Wo44886Gf
 0\ .164V64/_64C1:_64Jo0/_0J!1: 64Wo44886Gf
 1\.164V64/_64C1:_64Jo0/_0J!1: 64Wo44886Gf
 5|.164V64/_64C2:_65Jo0/_1J!1: 64Wo44886Gf
 1/.172V65/_65C2:_65Jo0/_0J!2: 65Wo44866Gf1/4Pp0/3Pq
 0\ .172V65/_65C2:_65Jo0/_0J!2: 65Wo44866Gf
 5|.172V65/_65C2:_65Jo0/_0J!2: 65Wo44866Gf
 2\.174V65/_65C2:_65Jo0/_0J!2: 65Wo44866Gf
 4|.174V65/_65C2:_65Jo0/_0J!2: 65Wo44866Gf
 0/ .174V66/_66C3:_66Jo0/_0J!3: 66Wo44866Gf1/4Pp0/3Pq
 1\.174V66/_66C3:_66Jo0/_1J!3: 66Wo44866Gf
 2\.174V66/_66C3:_66Jo0/_0J!3: 66Wo44866Gf
 4|.174V66/_66C3:_66Jo0/_1J!2: 65Wo44866Gf
 5|.174V66/_66C3:_66Jo0/_1J!2: 65Wo44866Gf
 0/ .174V67/_67C4:_67Jo0/_0J!4: 67Wo44866Gf1/4Pp0/3Pq
 1\.174V67/_67C5:_68Jo0/_1J!4: 67Wo44866Gf
 2\.174V67/_67C5:_68Jo0/_2J!3: 68Wo44866Gf
 0/ .174V68/_68C5:_68Jo0/_0J!5: 68Wo44866Gf1/4Pp0/3Pq
 2\.174V68/_68C5:_68Jo0/_1J!3: 68Wo44866Gf
 1\.174V68/_68C5:_68Jo0/_0J!5: 68Wo44866Gf
 4|.174V67/_68C5:_68Jo0/_1J!3: 68Wo44866Gf
 4|.174V68/_68C5:_68Jo0/_1J!3: 68Wo44866Gf
 5|.174V67/_68C5:_68Jo0/_2J!4: 67Wo44866Gf
 5|.174V68/_68C5:_68Jo0/_1J!4: 67Wo44866Gf
 0/ .174V69/_69C6:_69Jo0/_0J!6: 69Wo44866Gf1/4Pp0/3Pq
 2\.174V69/_69C6:_69Jo0/_0J!6: 69Wo44866Gf
 4|.174V69/_69C7:_70Jo0/_2J!6: 69Wo44866Gf
 1/v175V69/_69C6:_69Jo0/_1J!6: 69Wo44866Gf
 5|.181V69/_69C6:_69Jo0/_1J!5: 68Wo44866Gf
 0/ .183V70/_70C7:_70Jo0/_0J!7: 70Wo44866Gf1/4Pp0/3Pq
 4|.183V70/_70C7:_70Jo0/_0J!7: 70Wo44866Gf
 1\.183V70/_70C7:_70Jo0/_0J!7: 70Wo44866Gf
 5|.183V70/_70C7:_70Jo0/_1J!6: 69Wo44866Gf
 2\.183V70/_70C8:_71Jo0/_1J!7: 70Wo44866Gf
 1/.187V71/_71C8:_71Jo0/_0J!8: 71Wo44866Gf1/4Pp0/3Pq
 2\.187V71/_71C8:_71Jo0/_0J!8: 71Wo44866Gf
 0\ .187V71/_71C8:_71Jo0/_0J!8: 71Wo44866Gf
 5|.187V71/_71C8:_71Jo0/_1J!7: 70Wo44866Gf
 1/.187V72/_72C9:_72Jo0/_0J!9: 72Wo44866Gf1/4Pp0/3Pq
 2\.187V72/_72C9:_72Jo0/_0J!9: 72Wo44866Gf
 0\ .187V72/_72C9:_72Jo0/_0J!9: 72Wo44866Gf
 1/.187V73/_73C10:_73Jo0/_0J!10: 73Wo44866Gf1/4Pp0/3Pq
 2\.187V73/_73C10:_73Jo0/_0J!10: 73Wo44866Gf
 5|.187V72/_72C10:_73Jo0/_2J!8: 73Wo44866Gf
 5|.187V73/_73C10:_73Jo0/_0J!10: 73Wo44866Gf
 4|.187V71/_73C10:_73Jo0/_3J!7: 70Wo44866Gf
 4|.187V72/_73C10:_73Jo0/_3J!7: 70Wo44866Gf
 4|.187V73/_73C10:_73Jo0/_3J!7: 70Wo44866Gf
 0\ .187V73/_73C10:_73Jo0/_0J!10: 73Wo44866Gf
 1/.193V74/_74C11:_74Jo0/_0J!11: 74Wo44866Gf1/4Pp0/3Pq
 2\.193V74/_74C11:_74Jo0/_0J!11: 74Wo44866Gf
 4|.193V74/_74C11:_74Jo0/_0J!11: 74Wo44866Gf
 0\ .193V74/_74C11:_74Jo0/_0J!11: 74Wo44866Gf
 5|.193V74/_74C11:_74Jo0/_0J!11: 74Wo44866Gf
 1/.205V75/_75C12:_75Jo0/_0J!12: 75Wo44866Gf1/4Pp0/3Pq
 2\.205V75/_75C12:_75Jo0/_0J!12: 75Wo44866Gf
 0\ .205V75/_75C12:_75Jo0/_1J!12: 75Wo44866Gf
 4|.205V75/_75C12:_75Jo0/_1J!12: 75Wo44866Gf
 5|.205V75/_75C12:_75Jo0/_1J!11: 74Wo44866Gf
 0/ .207V76/_76C13:_76Jo0/_0J!13: 76Wo44866Gf1/4Pp0/3Pq
 2\.207V76/_76C13:_76Jo0/_0J!13: 76Wo44866Gf
 5|.207V76/_76C13:_76Jo0/_1J!12: 75Wo44866Gf
 1\.207V76/_76C13:_76Jo0/_0J!13: 76Wo44866Gf
 4|.207V76/_76C14:_77Jo0/_1J!13: 76Wo44866Gf
 2/.212V77/_77C14:_77Jo0/_0J!14: 77Wo44866Gf1/4Pp0/3Pq
 0\ .212V77/_77C14:_77Jo0/_0J!14: 77Wo44866Gf
 5|.212V77/_77C14:_77Jo0/_1J!13: 76Wo44866Gf
 4|.212V77/_77C15:_78Jo0/_1J!13: 78Wo44866Gf
 0/ .216V78/_78C15:_78Jo0/_0J!15: 78Wo44866Gf1/4Pp0/3Pq
 4|.216V78/_78C15:_78Jo0/_0J!15: 78Wo44866Gf
 1/v217V77/_77C15:_78Jo0/_0J!15: 78Wo44866Gf
 5|.216V78/_78C15:_78Jo0/_1J!15: 78Wo44866Gf
 1/.217V78/_78C15:_78Jo0/_0J!15: 78Wo44866Gf1/4Pp0/3Pq
 2\.217V78/_78C15:_78Jo0/_0J!15: 78Wo44866Gf
 2/.221V79/_79C16:_79Jo0/_0J!16: 79Wo44866Gf1/4Pp0/3Pq
 0\ .221V79/_79C16:_79Jo0/_0J!16: 79Wo44866Gf
 5|.221V79/_79C16:_79Jo0/_0J!16: 79Wo44866Gf
 4|.221V79/_79C16:_79Jo0/_1J!15: 78Wo44866Gf
 1\.221V79/_79C16:_79Jo0/_0J!16: 79Wo44866Gf
 0/ .228V80/_80C17:_80Jo0/_0J!17: 80Wo44866Gf1/4Pp0/3Pq
 2\.228V80/_80C17:_80Jo0/_1J!17: 80Wo44866Gf
 1\.228V80/_80C17:_80Jo0/_0J!17: 80Wo44866Gf
 5|.228V80/_80C17:_80Jo0/_1J!16: 79Wo44866Gf
 4|.228V80/_80C17:_80Jo0/_0J!17: 80Wo44866Gf
 0/ .228V81/_81C18:_81Jo0/_0J!18: 81Wo44866Gf1/4Pp0/3Pq
 1/v229V81/_81C18:_81Jo0/_0J!18: 81Wo44866Gf
 1/.229V82/_82C19:_82Jo0/_0J!19: 82Wo44866Gf1/4Pp0/3Pq
 2/v230V81/_82C19:_82Jo0/_1J!18: 81Wo44866Gf
 2/v230V82/_82C19:_82Jo0/_1J!19: 82Wo44866Gf
 5|.229V81/_82C19:_82Jo0/_1J!17: 82Wo44866Gf
 5|.229V82/_82C19:_82Jo0/_1J!17: 82Wo44866Gf
 0/ v231V82/_82C20:_83Jo0/_1J!19: 82Wo44866Gf
 4|.229V81/_82C19:_82Jo0/_2J!17: 82Wo44866Gf
 4|.229V82/_82C19:_82Jo0/_2J!17: 82Wo44866Gf
 0/ .234V83/_83C20:_83Jo0/_0J!20: 83Wo44866Gf1/4Pp0/3Pq
 1\.234V83/_83C20:_83Jo0/_0J!20: 83Wo44866Gf
 2\.234V83/_83C20:_83Jo0/_0J!20: 83Wo44866Gf
 4|.234V83/_83C20:_83Jo0/_1J!19: 82Wo44866Gf
 5|.234V83/_83C21:_84Jo0/_2J!19: 82Wo44866Gf
 1/.235V84/_84C21:_84Jo0/_0J!21: 84Wo44866Gf1/4Pp0/3Pq
 0/ v237V84/_84C21:_84Jo0/_0J!21: 84Wo44866Gf
 1 $ ##
 2/v239V84/_84C22:_85Jo0/_1J!21: 84Wo44866Gf
 5|.240V84/_84C22:_85Jo0/_1J!21: 84Wo44866Gf
 0/ .240V85/_85C22:_85Jo0/_0J!22: 85Wo44866Gf1/4Pp0/3Pq
 2\.240V85/_85C22:_85Jo0/_0J!22: 85Wo44866Gf
 5|.240V85/_85C22:_85Jo0/_1J!21: 84Wo44866Gf
 4|.240V84/_85C22:_85Jo0/_2J!20: 83Wo44866Gf
 4|.240V85/_85C22:_85Jo0/_2J!20: 83Wo44866Gf
 0/ .240V86/_86C23:_86Jo0/_0J!23: 86Wo44866Gf1/4Pp0/3Pq
 2\.240V86/_86C23:_86Jo0/_0J!23: 86Wo44866Gf
 0/ .240V87/_87C24:_87Jo0/_0J!24: 87Wo44866Gf1/4Pp0/3Pq
 2\.240V87/_87C24:_87Jo0/_0J!24: 87Wo44866Gf
 5|.240V86/_87C24:_87Jo0/_2J!22: 85Wo44866Gf
 5|.240V87/_87C24:_87Jo0/_2J!22: 85Wo44866Gf
 4|.240V86/_87C25:_88Jo0/_2J!22: 87Wo44866Gf
 4|.240V87/_87C25:_88Jo0/_2J!22: 87Wo44866Gf
 0/ .240V88/_88C25:_88Jo0/_0J!25: 88Wo44866Gf1/4Pp0/3Pq
 4|.240V88/_88C25:_88Jo0/_0J!25: 88Wo44866Gf
 2\.240V88/_88C25:_88Jo0/_0J!25: 88Wo44866Gf
 5|.240V88/_88C25:_88Jo0/_1J!24: 87Wo44866Gf
 0/ .240V89/_89C26:_89Jo0/_0J!26: 89Wo44866Gf1/4Pp0/3Pq
 2\.240V89/_89C26:_89Jo0/_0J!26: 89Wo44866Gf
 5|.240V89/_89C27:_90Jo0/_2J!25: 88Wo44866Gf
 4|.240V89/_89C27:_90Jo0/_0J!27: 90Wo44866Gf
 0/ .240V90/_90C27:_90Jo0/_0J!27: 90Wo44866Gf1/4Pp0/3Pq
 2\.240V90/_90C27:_90Jo0/_0J!27: 90Wo44866Gf
 5|.240V90/_90C27:_90Jo0/_0J!27: 90Wo44866Gf
 4|.240V90/_90C27:_90Jo0/_0J!27: 90Wo44866Gf
 0/ .240V91/_91C28:_91Jo0/_0J!28: 91Wo44827Gf1/4Pp0/3Pq
 2\.240V91/_91C28:_91Jo0/_0J!28: 91Wo44827Gf
 4|.240V91/_91C28:_91Jo0/_1J!27: 90Wo44827Gf
 5|.240V91/_91C29:_92Jo0/_2J!27: 90Wo44827Gf
 0/ .240V92/_92C29:_92Jo0/_0J!29: 92Wo44827Gf1/4Pp0/3Pq
 5|.240V92/_92C29:_92Jo0/_0J!29: 92Wo44827Gf
 2\.240V92/_92C29:_92Jo0/_0J!29: 92Wo44827Gf
 4|.240V92/_92C29:_92Jo0/_1J!29: 92Wo44827Gf
 0/ .240V93/_93C30:_93Jo0/_0J!30: 93Wo44827Gf1/4Pp0/3Pq
 4|.240V93/_93C30:_93Jo0/_1J!29: 92Wo44827Gf
 2\.240V93/_93C30:_93Jo0/_0J!30: 93Wo44827Gf
 5|.240V93/_93C30:_93Jo0/_1J!29: 92Wo44827Gf
 0/ .240V94/_94C31:_94Jo0/_0J!31: 94Wo44827Gf1/4Pp0/3Pq
 2\.240V94/_94C31:_94Jo0/_0J!31: 94Wo44827Gf
 5|.240V94/_94C31:_94Jo0/_1J!30: 93Wo44827Gf
 4|.240V94/_94C31:_94Jo0/_1J!30: 93Wo44827Gf
 0/ .240V95/_95C32:_95Jo0/_0J!32: 95Wo44788Gf1/4Pp0/3Pq
 2\.240V95/_95C32:_95Jo0/_0J!32: 95Wo44788Gf
 5|.240V95/_95C32:_95Jo0/_1J!31: 94Wo44788Gf
 4|.240V95/_95C32:_95Jo0/_0J!32: 95Wo44788Gf
 0/ .240V96/_96C33:_96Jo0/_0J!33: 96Wo44788Gf1/4Pp0/3Pq
 2\.240V96/_96C33:_96Jo0/_0J!33: 96Wo44788Gf
 5|.240V96/_96C33:_96Jo0/_1J!32: 95Wo44788Gf
 4|.240V96/_96C34:_97Jo0/_2J!32: 95Wo44788Gf
 0/ .240V97/_97C34:_97Jo0/_0J!34: 97Wo44788Gf1/4Pp0/3Pq
 2\.240V97/_97C34:_97Jo0/_0J!34: 97Wo44788Gf
 4|.240V97/_97C34:_97Jo0/_0J!34: 97Wo44788Gf
 5|.240V97/_97C35:_98Jo0/_2J!33: 96Wo44788Gf
 0/ .240V98/_98C35:_98Jo0/_0J!35: 98Wo44788Gf1/4Pp0/3Pq
 2\.240V98/_98C35:_98Jo0/_0J!35: 98Wo44788Gf
 5|.240V98/_98C35:_98Jo0/_0J!35: 98Wo44788Gf
 4|.240V98/_98C35:_98Jo0/_1J!34: 97Wo44788Gf
 0/ .240V99/_99C36:_99Jo0/_0J!36: 99Wo44788Gf1/4Pp0/3Pq
 4|.240V99/_99C37:100Jo0/_2J!36: 99Wo44788Gf
 2\.240V99/_99C36:_99Jo0/_0J!36: 99Wo44788Gf
 5|.240V99/_99C37:100Jo0/_2J!35: 98Wo44788Gf
 0/ .240V 100/100C37:100Jo0/_0J!37:100Wo44788Gf1/4Pp0/3Pq
 4|.240V 100/100C37:100Jo0/_0J!37:100Wo44788Gf
 2\.240V 100/100C37:100Jo0/_0J!37:100Wo44788Gf
 5|.240V 100/100C37:100Jo0/_0J!37:100Wo44788Gf
 0/ .240V 101/101C38:101Jo0/_0J!38:101Wo44788Gf1/4Pp0/3Pq
 2\.240V 101/101C38:101Jo0/_0J!38:101Wo44788Gf
 5|.240V 101/101C38:101Jo0/_1J!37:100Wo44788Gf
 4|.240V 101/101C38:101Jo0/_1J!38:101Wo44788Gf
 0/ .240V 102/102C39:102Jo0/_0J!39:102Wo44788Gf1/4Pp0/3Pq
 2\.240V 102/102C39:102Jo0/_0J!39:102Wo44788Gf
 4|.240V 102/102C39:102Jo0/_1J!39:102Wo44788Gf
 5|.240V 102/102C40:103Jo0/_2J!38:101Wo44788Gf
 0/ .240V 103/103C40:103Jo0/_0J!40:103Wo44788Gf1/4Pp0/3Pq
 5|.240V 103/103C40:103Jo0/_0J!40:103Wo44788Gf
 4|.240V 103/103C41:104Jo0/_2J!39:102Wo44788Gf
 2\.240V 103/103C40:103Jo0/_0J!40:103Wo44788Gf
 0/ .240V 104/104C41:104Jo0/_0J!41:104Wo44788Gf1/4Pp0/3Pq
 4|.240V 104/104C41:104Jo0/_0J!41:104Wo44788Gf
 2\.240V 104/104C41:104Jo0/_0J!41:104Wo44788Gf
 5|.240V 104/104C42:105Jo0/_1J!40:105Wo44788Gf
 0/ .240V 105/105C42:105Jo0/_0J!42:105Wo44788Gf1/4Pp0/3Pq
 2\.240V 105/105C42:105Jo0/_0J!42:105Wo44788Gf
 4|.240V 105/105C42:105Jo0/_1J!41:104Wo44788Gf
 5|.240V 105/105C42:105Jo0/_0J!42:105Wo44788Gf
 0/ .240V 106/106C43:106Jo0/_0J!43:106Wo44788Gf1/4Pp0/3Pq
 4|.240V 106/106C43:106Jo0/_1J!43:106Wo44788Gf
 2\.240V 106/106C43:106Jo0/_0J!43:106Wo44788Gf
 5|.240V 106/106C44:107Jo0/_2J!43:106Wo44788Gf
 0/ .240V 107/107C44:107Jo0/_0J!44:107Wo44788Gf1/4Pp0/3Pq
 5|.240V 107/107C44:107Jo0/_0J!44:107Wo44788Gf
 2\.240V 107/107C44:107Jo0/_0J!44:107Wo44788Gf
 4|.240V 107/107C45:108Jo0/_2J!43:106Wo44788Gf
 0/ .240V 108/108C45:108Jo0/_0J!45:108Wo44788Gf1/4Pp0/3Pq
 4|.240V 108/108C45:108Jo0/_0J!45:108Wo44788Gf
 2\.240V 108/108C45:108Jo0/_0J!45:108Wo44788Gf
 0/ .240V 109/109C46:109Jo0/_0J!46:109Wo44788Gf1/4Pp0/3Pq
 2\.240V 109/109C46:109Jo0/_0J!46:109Wo44788Gf
 5|.240V 108/109C46:109Jo0/_2J!44:109Wo44788Gf
 5|.240V 109/109C46:109Jo0/_2J!44:109Wo44788Gf
 4|.240V 109/109C47:110Jo0/_2J!46:109Wo44788Gf
 0/ .240V 110/110C47:110Jo0/_0J!47:110Wo44788Gf1/4Pp0/3Pq
 2\.240V 110/110C47:110Jo0/_0J!47:110Wo44788Gf
 4|.240V 110/110C47:110Jo0/_1J!46:109Wo44788Gf
 5|.240V 110/110C48:111Jo0/_2J!47:110Wo44788Gf
 4 $ ##
 0/ .240V 111/111C48:111Jo0/_0J!48:111Wo44788Gf1/4Pp0/3Pq
 5|.240V 111/111C48:111Jo0/_0J!48:111Wo44788Gf
 2\.240V 111/111C48:111Jo0/_0J!48:111Wo44788Gf
 0/ .240V 112/112C49:112Jo0/_0J!49:112Wo44788Gf1/4Pp0/3Pq
 2\.240V 112/112C49:112Jo0/_0J!49:112Wo44788Gf
 5|.240V 112/112C50:113Jo0/_2J!48:111Wo44788Gf
 0/ .240V 113/113C50:113Jo0/_0J!50:113Wo44788Gf1/4Pp0/3Pq
 5|.240V 113/113C50:113Jo0/_2J!48:111Wo44788Gf
 2\.240V 113/113C50:113Jo0/_0J!50:113Wo44788Gf
 0/ .240V 114/114C51:114Jo0/_0J!51:114Wo44788Gf1/4Pp0/3Pq
 2\.240V 114/114C51:114Jo0/_0J!51:114Wo44788Gf
 5|.240V 114/114C52:115Jo0/_2J!50:113Wo44788Gf
 0/ .240V 115/115C52:115Jo0/_0J!52:115Wo44788Gf1/4Pp0/3Pq
 5|.240V 115/115C52:115Jo0/_0J!52:115Wo44788Gf
 2\.240V 115/115C52:115Jo0/_0J!52:115Wo44788Gf
 1  /h238V59/_84C22:_84Jo1/_1J!22: 85Wo44886Gf
```
</details>

### PR DESCRIPTION
**Pull request by sentientwaffle**
Fixes https://github.com/tigerbeetledb/tigerbeetle/issues/783.

### Bug

In the seed reference in the above issue (`14295907088955483715` on `fd94fadf804e6ce612372106093d168fe128e6d7`), the simulator fails in `simulator.zig` on

    assert(replica.status != .recovering_head or fault);

Specifically, replica `1` restarts into `recovering_head` even though storage faults were disabled during its recovery. Slot 21 of the WAL is the problem:

    [warn] (journal): 1: recover_slot: recovered slot=0021 label=@H decision=vsr command=Command.reserved op=21

Case `@H` is:
- the redundant header is a valid prepare, but
- the prepare is reserved.

The prepare is actually present in the log. It is being converted to `reserved` by `recover_slots()`:

    // Discard headers which we are certain do not belong in the current log_view.

### Fix

There are two possible fixes here.
The first is to remove the redundant header at the same time we remove the prepare. The second is to defer the removal, and modify the recovery decision directly.

There was originally a note that this code should precede `prepare_op_max`'s computation. But I think that is actually not right — even if we are pretending those last messages don't exist because they don't belong in our newer view, it doesn't mean that the earlier message should be treated as op-max for the purposes of the recovery decision table.

## Pre-merge checklist

Performance:

* [x] I am very sure this PR could not affect performance.

### CODE REVIEW

File: src/vsr/journal.zig [hunk 1]
```diff
@@ -1459,9 +1462,8 @@ pub fn JournalType(comptime Replica: type, comptime Storage: type) type {
                 },
                 .cut => {
                     assert(header != null);
-                    assert(prepare == null);
-                    assert(!journal.prepare_inhabited[slot.index]);
-                    assert(journal.prepare_checksums[slot.index] == 0);
+                    // If `prepare` is non-null, it is being truncated due to the view range.
```
Comment (matklad) [inline src/vsr/journal.zig]: Might split out `.cut_view_range` for tighter asserts?

File: src/vsr/journal.zig [hunk 2]
```diff
@@ -1303,6 +1279,33 @@ pub fn JournalType(comptime Replica: type, comptime Storage: type) type {
                 });
             }
 
+            // Discard headers which we are certain do not belong in the current log_view.
```
Comment (matklad) [inline src/vsr/journal.zig:1282]: Is there some comment somewhere which explains how prepares with a wrong view can arise in the first place?

Comment (sentientwaffle) [reply src/vsr/journal.zig:1282]: I'll add this explanation:
```
            // (These headers can originate if we join a view, write some prepares from the new
            // view, and then crash before the view_durable_update() finished.)
```

**Review by matklad — COMMENTED** [review]
This looks reasonable to me, but, tbh, I don't yet fully understand this reasoning: 

>But I think that is actually not right — even if we are pretending those last messages don't exist because they don't belong in our newer view, it doesn't mean that the earlier message should be treated as op-max for the purposes of the recovery decision table.

What would be the case where it matters whether we compute `prepare_op_max` before or after cutting out-of-view prepares? 

Is it something like this: 

* `R0` is the primary
* `R0` prepares `op` and crashes
* `R0` restarts, and joints the new view
* `R1`, the new primary sends `op+1` to `R0`
* `R0` writes `op+1`, but not its `log_view`, and crashes again
* `R0` restarts. It wants to truncate `op+1` as out-of-view.
* depending on whether we truncate before or after, `prepare_op_max` might be `op` or `op + 1`
* So, if the header for `op` gets corrupted, we might end up in `@E` or `@F` case (we either trust prepare and replace header locally, or mark slot as faulty)

Does it matter which we choose?

In particular, what if `op+1` is a super trainsient op. THat is, `R1` crashes after sending prepare for `op+1`, so, from the prespective of the cluster, this op just doesn't exist, and `R2`, the next primary, should pick `op` as the head?

**Comment by sentientwaffle** [comment]
As I was I was writing up an explanation, I finally realized what I was thinking when I wrote this originally:

```
            // It is essential that this is performed before we compute the op_max so that the
            // recovery cases apply correctly.
```

Which means that this code still isn't right. The problem is that `recover_torn_prepare` computes the op-max itself from the headers/prepares. But if this is done _after_ the view-range truncation, then this calculation is incorrect, and might end up truncating a "torn prepare" that wasn't actually torn. Which could then lead to the replica nacking a prepare that it shouldn't nack.

**Comment by sentientwaffle** [comment]
Actually nevermind, now I think it was broken before but correct now. :thinking:

**Review by matklad — APPROVED** [review]
I think everything makes sense to me know, thanks for extra comments!
